//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Core.Alessi.DAO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.Core.Alessi.DAO.Resources.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cast(T0.SalPackUn as int) as Qtd from OITM T0 Where T0.ItemCode = &apos;{0}&apos;.
        /// </summary>
        internal static string BuscaQtdEmbalagem {
            get {
                return ResourceManager.GetString("BuscaQtdEmbalagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select U_CVA_ForaMultiplo From ORDR Where DocNum = &apos;{0}&apos;.
        /// </summary>
        internal static string BuscaRegraPedido {
            get {
                return ResourceManager.GetString("BuscaRegraPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [@CVA_IMP_DEFAULT]
        ///WHERE U_ObjType = {0} AND U_Layout = &apos;{1}&apos;.
        /// </summary>
        internal static string DefaultValues_Get {
            get {
                return ResourceManager.GetString("DefaultValues_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [@CVA_DOC_MAP]
        ///WHERE U_ObjType = {0} AND U_Layout = &apos;{1}&apos;.
        /// </summary>
        internal static string DocumentMapping_Get {
            get {
                return ResourceManager.GetString("DocumentMapping_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [@CVA_DOC_MAP_ITEM]
        ///WHERE Code = &apos;{0}&apos;.
        /// </summary>
        internal static string DocumentMappingItem_GetByCode {
            get {
                return ResourceManager.GetString("DocumentMappingItem_GetByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT U_Layout FROM [@CVA_DOC_MAP]
        ///WHERE U_ObjType = {0}.
        /// </summary>
        internal static string DocumentMappingLayout_GetByObjType {
            get {
                return ResourceManager.GetString("DocumentMappingLayout_GetByObjType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AcctCode FROM OACT
        ///WHERE U_CodRed = &apos;{0}&apos;.
        /// </summary>
        internal static string FolhaPagamento_GetAccount {
            get {
                return ResourceManager.GetString("FolhaPagamento_GetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CardCode FROM OCRD
        ///WHERE U_PN_CodRed = &apos;{0}&apos;.
        /// </summary>
        internal static string FolhaPagamento_GetBP {
            get {
                return ResourceManager.GetString("FolhaPagamento_GetBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec scp_CVA_ResFiAbertoGrupo&apos;{0}&apos;.
        /// </summary>
        internal static string GetAbertoGrupo {
            get {
                return ResourceManager.GetString("GetAbertoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec Spc_ResFiAcumulo &apos;{0}&apos;,&apos;{1}&apos;.
        /// </summary>
        internal static string GetAcumulo {
            get {
                return ResourceManager.GetString("GetAcumulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec Spc_ResFiAcumuloGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetAcumuloGrupo {
            get {
                return ResourceManager.GetString("GetAcumuloGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec Spc_ResFiAtividadesPN &apos;{0}&apos;.
        /// </summary>
        internal static string GetAtividadesPN {
            get {
                return ResourceManager.GetString("GetAtividadesPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec  scp_CVA_ResFiAtrsadosGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetAtrasadosGrupo {
            get {
                return ResourceManager.GetString("GetAtrasadosGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select CreateDate from [@CVA_GRUPOECON] where code = &apos;{0}&apos;.
        /// </summary>
        internal static string GetDataCadastroGrupo {
            get {
                return ResourceManager.GetString("GetDataCadastroGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select CreateDate from OCRD where CardCode = &apos;{0}&apos;.
        /// </summary>
        internal static string GetDataCadastroPN {
            get {
                return ResourceManager.GetString("GetDataCadastroPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select DocEntry from oinv where Serial = &apos;{0}&apos;.
        /// </summary>
        internal static string GetDocEntry {
            get {
                return ResourceManager.GetString("GetDocEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select U_Juros from [@CVA_Juros].
        /// </summary>
        internal static string GetJuros {
            get {
                return ResourceManager.GetString("GetJuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spc_CVA_ResFi_ColLimite_Grupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetLimiteGrupo {
            get {
                return ResourceManager.GetString("GetLimiteGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec scp_CVA_ResFiLiquidadosGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetLiquidadosGrupo {
            get {
                return ResourceManager.GetString("GetLiquidadosGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spc_CVA_ResFi_MaiorCompraGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetMaiorCompra {
            get {
                return ResourceManager.GetString("GetMaiorCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spc_CVA_ResFi_UltimaCompraGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetUltimaCompraGrupo {
            get {
                return ResourceManager.GetString("GetUltimaCompraGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec  scp_CVA_ResFiAbertoAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValorAberto {
            get {
                return ResourceManager.GetString("GetValorAberto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec  scp_CVA_ResFiAtrasadosAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValorAtrsado {
            get {
                return ResourceManager.GetString("GetValorAtrsado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec  scp_CVA_ResFiBoletoAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValorBoleto {
            get {
                return ResourceManager.GetString("GetValorBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec  scp_CVA_ResFiChequeAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValorCheque {
            get {
                return ResourceManager.GetString("GetValorCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec  scp_CVA_ResFiEmCarteiraAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValorEmCarteira {
            get {
                return ResourceManager.GetString("GetValorEmCarteira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiAbertoAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresAbertoGrupo {
            get {
                return ResourceManager.GetString("GetValoresAbertoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiAtrasadosAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresAtrasadosGrupo {
            get {
                return ResourceManager.GetString("GetValoresAtrasadosGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiBoletoAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresBoletoGrupo {
            get {
                return ResourceManager.GetString("GetValoresBoletoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiChequeAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresChequeGrupo {
            get {
                return ResourceManager.GetString("GetValoresChequeGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiEmCarteiraAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresEmcarteiraGrupo {
            get {
                return ResourceManager.GetString("GetValoresEmcarteiraGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec scp_CVA_ResFiLiquidadosAberto &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosAberto {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosAberto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosAbertoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosAbertoGrupo {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosAbertoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosAtrasadosAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosAtrasados {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosAtrasados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosAtrasadosAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosAtrasadosGrupo {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosAtrasadosGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosBoletoAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosBoleto {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosBoletoAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosBoletoGrupo {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosBoletoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosChequeAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosCheque {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosChequeAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosChequeGrupo {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosChequeGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosEmCarteiraAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosEmCarteira {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosEmCarteira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosEmCarteiraAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosEmCarteiraGrupo {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosEmCarteiraGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosTotalAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosTotal {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiLiquidadosTotalAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresLiquidadosTotalGrupo {
            get {
                return ResourceManager.GetString("GetValoresLiquidadosTotalGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scp_CVA_ResFiTotalAnaliticoGrupo &apos;{0}&apos;.
        /// </summary>
        internal static string GetValoresTotalGrupo {
            get {
                return ResourceManager.GetString("GetValoresTotalGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec  scp_CVA_ResFiTotalAnalitico &apos;{0}&apos;.
        /// </summary>
        internal static string GetValorTotal {
            get {
                return ResourceManager.GetString("GetValorTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 1 FROM [@CVA_NFE_FRETE] WHERE U_DocEntry = {0}.
        /// </summary>
        internal static string NotaEntradaFrete_ExistsByDocEntry {
            get {
                return ResourceManager.GetString("NotaEntradaFrete_ExistsByDocEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	OCRD.CardCode + &apos; - &apos; + OCRD.CardName
        ///FROM INV12 WITH(NOLOCK)
        ///	INNER JOIN OCRD WITH(NOLOCK)
        ///		ON OCRD.CardCode = INV12.Carrier
        ///WHERE INV12.DocEntry = {0}.
        /// </summary>
        internal static string NotaSaida_GetCarrier {
            get {
                return ResourceManager.GetString("NotaSaida_GetCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec  scp_CVA_ResFiAtrsados &apos;{0}&apos;,&apos;{1}&apos;.
        /// </summary>
        internal static string PegaDadosAtrasados {
            get {
                return ResourceManager.GetString("PegaDadosAtrasados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec  scp_CVA_ResFiAberto &apos;{0}&apos;,&apos;{1}&apos;.
        /// </summary>
        internal static string PegaDadosColunaAberto {
            get {
                return ResourceManager.GetString("PegaDadosColunaAberto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spc_CVA_ResFi_ColLimite &apos;{0}&apos;,&apos;{1}&apos;.
        /// </summary>
        internal static string PegaDadosColunaLimite {
            get {
                return ResourceManager.GetString("PegaDadosColunaLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec scp_CVA_ResFiLiquidados &apos;{0}&apos;,&apos;{1}&apos;.
        /// </summary>
        internal static string PegaDadosColunaLiquidados {
            get {
                return ResourceManager.GetString("PegaDadosColunaLiquidados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spc_CVA_ResFi_MaiorCompra &apos;{0}&apos;,&apos;{1}&apos;.
        /// </summary>
        internal static string PegaDadosMaiorCompra {
            get {
                return ResourceManager.GetString("PegaDadosMaiorCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec spc_CVA_ResFi_UltimaCompra &apos;{0}&apos;,&apos;{1}&apos;.
        /// </summary>
        internal static string PegaDadosUltimaCompra {
            get {
                return ResourceManager.GetString("PegaDadosUltimaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 t1.code, T1.NAME from OCRD T0 inner join [@CVA_GRUPOECON] T1 ON T1.CODE = T0.U_CVA_GRUPOECON WHERE T1.CODE = &apos;{0}&apos;.
        /// </summary>
        internal static string PegaDescricaoGrupo {
            get {
                return ResourceManager.GetString("PegaDescricaoGrupo", resourceCulture);
            }
        }
    }
}
