USE [CVA_Gestao_TESTE]
GO

/****** Object:  Table [dbo].[CVA_PERIODOS]    Script Date: 22/02/2019 15:47:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVA_PERIODOS](
	[YEAR] [smallint] NOT NULL,
	[MONTH] [tinyint] NOT NULL,
 CONSTRAINT [PK_CVA_PERIODOS] PRIMARY KEY CLUSTERED 
(
	[YEAR] ASC,
	[MONTH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

