IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_DIME_ST')
	DROP PROCEDURE SP_CVA_DIME_ST
GO
CREATE PROCEDURE SP_CVA_DIME_ST
(
	@Code NVARCHAR(50)
)
AS
BEGIN
	
	SELECT
		PDN12.StateS UF,
		SUM(TaxSum) TaxSum,
		SUM(BaseSum) BaseSum
	FROM [@CVA_DIME] DIME WITH(NOLOCK)
		INNER JOIN OPDN WITH(NOLOCK)
			ON OPDN.BPLId = DIME.U_Filial OR DIME.U_Filial = 0
		INNER JOIN PDN1 WITH(NOLOCK)
			ON PDN1.DocEntry = OPDN.DocEntry
		INNER JOIN PDN12 WITH(NOLOCK)
			ON PDN12.DocEntry = OPDN.DocEntry
		LEFT JOIN (
			SELECT PDN4.DocEntry, PDN4.LineNum, SUM(TaxSum) TaxSum, SUM(BaseSum) BaseSum FROM PDN4 WITH(NOLOCK)
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PDN4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY PDN4.DocEntry, PDN4.LineNum
		) PDN4
			ON PDN4.DocEntry = PDN1.DocEntry
			AND PDN4.LineNum = PDN1.LineNum
	WHERE DIME.Code = @Code
	AND OPDN.DocDate BETWEEN DIME.U_DtDe AND DIME.U_DtAte
	AND ISNULL(PDN1.TrgetEntry, 0) = 0
	AND OPDN.CANCELED = 'N'
	GROUP BY
		PDN12.StateS

	UNION ALL

	SELECT 
		PCH12.StateS UF,
		SUM(TaxSum) TaxSum,
		SUM(BaseSum) BaseSum
	FROM [@CVA_DIME] DIME WITH(NOLOCK)
		INNER JOIN OPCH WITH(NOLOCK)
			ON OPCH.BPLId = DIME.U_Filial OR DIME.U_Filial = 0
		INNER JOIN PCH1 WITH(NOLOCK)
			ON PCH1.DocEntry = OPCH.DocEntry
		INNER JOIN PCH12 WITH(NOLOCK)
			ON PCH12.DocEntry = OPCH.DocEntry
		LEFT JOIN (
			SELECT PCH4.DocEntry, PCH4.LineNum, SUM(TaxSum) TaxSum, SUM(BaseSum) BaseSum FROM PCH4 WITH(NOLOCK)
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PCH4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY PCH4.DocEntry, PCH4.LineNum
		) PCH4
			ON PCH4.DocEntry = PCH1.DocEntry
			AND PCH4.LineNum = PCH1.LineNum
	WHERE DIME.Code = @Code
	AND OPCH.DocDate BETWEEN DIME.U_DtDe AND DIME.U_DtAte
	AND OPCH.CANCELED = 'N'
	GROUP BY
		PCH12.StateS

END