IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_DIME_SALDO_CREDOR')
	DROP PROCEDURE SP_CVA_DIME_SALDO_CREDOR
GO
CREATE PROCEDURE SP_CVA_DIME_SALDO_CREDOR
(
	@BPLId INT,
	@Mes INT,
	@Ano INT
)
AS
BEGIN	
	DECLARE @Data AS DATETIME
	SET @Data = CAST(CAST(@Ano AS NVARCHAR(4)) + REPLACE(STR(@Mes, 2), SPACE(1), '0') + '01' AS DATETIME)
	SET @Data = DATEADD(MONTH, -1, @Data)

	SELECT  U_Saldo
	FROM [@SKILL_005_APR1] T0  WITH (NOLOCK)
	WHERE T0.U_DtInicio = @Data
	AND (T0.U_BPLId = @BPLId OR @BPLId = 0)
	AND U_TipoImposto = 'ICMS'

	--SELECT U_VL_SLD_CREDOR_TRAN FROM [@AGL_APU_ICMS]
	--WHERE U_BPLId = @BPLId
	--AND DATEPART(MONTH, DATEADD(MONTH, 1, U_DT_INI)) = @Mes
	--AND DATEPART(YEAR, DATEADD(MONTH, 1, U_DT_INI)) = @Ano
END