IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_DCIP_ENERGIA')
	DROP PROCEDURE SP_CVA_DCIP_ENERGIA
GO
CREATE PROCEDURE SP_CVA_DCIP_ENERGIA
(
	@Filial		INT,
	@DataDe		DATETIME,
	@DataAte	DATETIME
)
AS
BEGIN
	SELECT
		OBPL.TaxIdNum2		IE,
		SUM(PCH4.TaxSum)	ICMS
	FROM OPCH WITH(NOLOCK)
		INNER JOIN OBPL WITH(NOLOCK)
			ON OBPL.BPLId = OPCH.BPLId
		INNER JOIN PCH1 WITH(NOLOCK)
			ON PCH1.DocEntry = OPCH.DocEntry
			--AND PCH1.CFOPCode IN ('1253', '1252', '2253', '2252')
		INNER JOIN PCH4 WITH(NOLOCK) 
			ON PCH4.DocEntry = PCH1.DocEntry
			AND PCH1.LineNum = PCH1.LineNum
		INNER JOIN OSTT WITH(NOLOCK) 
			ON OSTT.AbsId = PCH4.StaType
		INNER JOIN ONFT WITH(NOLOCK) 
			ON ONFT.AbsId = OSTT.NfTaxId 
			AND ONFT.Code = 'ICMS'
	WHERE OPCH.BPLId = @Filial
	AND OPCH.DocDate BETWEEN @DataDe AND @DataAte
	AND OPCH.CANCELED <> 'C'
	AND NOT EXISTS
	(
		SELECT * FROM ORPC WITH(NOLOCK)
			INNER JOIN RPC1 WITH(NOLOCK)
				ON RPC1.DocEntry = ORPC.DocEntry
		WHERE ORPC.CANCELED <> 'C' 
		AND RPC1.BaseType = 18
		AND RPC1.BaseEntry = PCH1.DocEntry
		AND RPC1.BaseLine = PCH1.LineNum
	)
	GROUP BY
		OBPL.TaxIdNum2
END

