IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SIMULADOR_OP')
	DROP PROCEDURE SP_CVA_SIMULADOR_OP
GO
CREATE PROCEDURE SP_CVA_SIMULADOR_OP
(
	@ItemCode		NVARCHAR(60)
)
AS
BEGIN
	SELECT
		AUPT.BELNR_ID	[Nr. OP],
		POS.MENGE_VERBRAUCH Qtde,
		SUM(CASE WHEN APL.ABGKZ = 'J' THEN 1.00 ELSE 0.00 END) / COUNT(APL.ABGKZ) * 100 [% Concluído],
		AUPT.BELDAT		[Dt. Cadastro],
		AUPT.LFGDAT		[Dt. Entrega],
		AUPT.ANFZEIT	[Dt. Início],
		AUPT.KNDNAME	[Cliente]
	FROM BEAS_FTHAUPT AUPT WITH(NOLOCK)
		INNER JOIN BEAS_FTPOS POS WITH(NOLOCK)
			ON POS.BELNR_ID = AUPT.BELNR_ID
			AND POS.STUFE = 0
		INNER JOIN BEAS_FTAPL APL WITH(NOLOCK)
			ON APL.BELNR_ID = AUPT.BELNR_ID
			AND APL.BELPOS_ID = POS.BELPOS_ID
	WHERE AUPT.ABGKZ = 'N'
	--AND POS.ItemCode = '30111056007'
	AND POS.ItemCode = @ItemCode
	GROUP BY
		AUPT.BELNR_ID,
		AUPT.BELDAT,
		AUPT.LFGDAT,
		AUPT.ANFZEIT,
		AUPT.KNDNAME,
		POS.MENGE_VERBRAUCH
END