IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SIMULADOR_PEDIDO')
	DROP PROCEDURE SP_CVA_SIMULADOR_PEDIDO
GO
CREATE PROCEDURE SP_CVA_SIMULADOR_PEDIDO
AS
BEGIN
	SELECT
		ORDR.DocNum,
		ORDR.DocDate,
		ORDR.CardCode,
		ORDR.CardName,
		RDR1.ItemCode,
		RDR1.Dscription ItemName,
		RDR1.OpenQty	Quantity
	FROM ORDR WITH(NOLOCK)
		INNER JOIN RDR1 WITH(NOLOCK)
			ON RDR1.DocEntry = ORDR.DocEntry
			AND RDR1.LineStatus = 'O'
	WHERE ORDR.DocStatus = 'O' AND ORDR.CANCELED <> 'Y'
	AND NOT EXISTS
	(
		SELECT TOP 1 1 FROM BEAS_FTHAUPT AUPT WITH(NOLOCK)
		WHERE AUPT.DocEntry = RDR1.DocEntry
		AND AUPT.AUFTRAGPOS = RDR1.LineNum
	)
	ORDER BY ORDR.DocNum
END

