IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SIMULADOR_ENTRADA')
	DROP PROCEDURE SP_CVA_SIMULADOR_ENTRADA
GO
CREATE PROCEDURE SP_CVA_SIMULADOR_ENTRADA
(
	@ItemCode		NVARCHAR(60)
)
AS
BEGIN
	SELECT
		'OP'			Tipo,
		AUPT.BELNR_ID	[Nr. Doc],
		AUPT.LFGDAT		[Dt. Entrega],
		POS.MENGE_VERBRAUCH Qtde
	FROM BEAS_FTHAUPT AUPT WITH(NOLOCK)
		INNER JOIN BEAS_FTPOS POS WITH(NOLOCK)
			ON POS.BELNR_ID = AUPT.BELNR_ID
			AND POS.ItemCode = AUPT.ItemCode 
			AND POS.STUFE = 0
	WHERE AUPT.ABGKZ = 'N'
	AND AUPT.ItemCode = @ItemCode

	UNION ALL

	SELECT 
		'OC',
		OPOR.DocNum,
		OPOR.DocDueDate,
		POR1.OpenQty QtdeCompra
	FROM OPOR WITH(NOLOCK)
		INNER JOIN POR1 WITH(NOLOCK)
			ON POR1.DocEntry = OPOR.DocEntry
			AND POR1.ItemCode = @ItemCode
	WHERE OPOR.DocStatus = 'O'
END