IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SIMULADOR_ROTEIRO')
	DROP PROCEDURE SP_CVA_SIMULADOR_ROTEIRO
GO
CREATE PROCEDURE SP_CVA_SIMULADOR_ROTEIRO
(
	@OP				INT,
	@ItemCode		NVARCHAR(60)
)
AS
BEGIN
	SELECT
		APL.POS_ID			[N Proc.],
		MIN(ZEIT.ANFZEIT)	[Dt. Inicial],
		MAX(ZEIT.ENDZEIT)	[Dt. Final],
		SUM(ZEIT.MENGE_GUT)	[Qtde],
		APLATZ.BEZ			[G.M.],
		CAST(APL.BEZ AS NVARCHAR(MAX))	[Instrução]
	FROM BEAS_FTHAUPT AUPT WITH(NOLOCK)
		INNER JOIN BEAS_FTPOS POS WITH(NOLOCK)
			ON POS.BELNR_ID = AUPT.BELNR_ID
			AND POS.STUFE = 0
		INNER JOIN BEAS_FTAPL APL WITH(NOLOCK)
			ON APL.BELNR_ID = AUPT.BELNR_ID
			AND APL.BELPOS_ID = POS.BELPOS_ID
		INNER JOIN BEAS_APLATZ APLATZ WITH(NOLOCK)
			ON APLATZ.APLATZ_ID = APL.APLATZ_ID
		LEFT JOIN BEAS_ARBZEIT ZEIT WITH(NOLOCK)
			ON ZEIT.BELNR_ID = AUPT.BELNR_ID
			AND ZEIT.BELPOS_ID = POS.BELPOS_ID
			AND ZEIT.APLATZ_ID = APLATZ.APLATZ_ID
	WHERE AUPT.ABGKZ = 'N'
	--AND POS.ItemCode = '30111056007'
	AND POS.ItemCode = @ItemCode
	AND POS.BELNR_ID = @OP
	GROUP BY
		APL.POS_ID,
		APLATZ.BEZ,
		CAST(APL.BEZ AS NVARCHAR(MAX))
END