//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Core.ControlCommon.MODEL.CVACommon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVACommonEDM : DbContext
    {
        public CVACommonEDM()
            : base("name=CVACommonEDM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base> CVA_BAS { get; set; }
        public virtual DbSet<Funcao> CVA_FUNC { get; set; }
        public virtual DbSet<Objeto> CVA_OBJ { get; set; }
        public virtual DbSet<Registro> CVA_REG { get; set; }
        public virtual DbSet<RegistroLog> CVA_REG_LOG { get; set; }
        public virtual DbSet<Status> CVA_STU { get; set; }
        public virtual DbSet<Timer> CVA_TIM { get; set; }
        public virtual DbSet<TipoRegistro> CVA_TIP_REG { get; set; }
    }
}
