//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Core.ControlCommon.MODEL.CVACommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registro()
        {
            this.CVA_REG_LOG = new HashSet<RegistroLog>();
        }
    
        public int ID { get; set; }
        public System.DateTime INS { get; set; }
        public Nullable<System.DateTime> UPD { get; set; }
        public Nullable<int> STU { get; set; }
        public Nullable<int> BAS { get; set; }
        public string CODE { get; set; }
        public Nullable<int> OBJ { get; set; }
        public Nullable<int> FUNC { get; set; }
        public Nullable<int> BAS_ERR { get; set; }
    
        public virtual Base CVA_BAS { get; set; }
        public virtual Base CVA_BAS1 { get; set; }
        public virtual Funcao CVA_FUNC { get; set; }
        public virtual Objeto CVA_OBJ { get; set; }
        public virtual Status CVA_STU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroLog> CVA_REG_LOG { get; set; }
    }
}
