INSERT INTO CVA_STU(INS, STU) VALUES((SELECT GETDATE()), 'Inativo');
INSERT INTO CVA_STU(INS, STU) VALUES((SELECT GETDATE()), 'Ativo');
INSERT INTO CVA_STU(INS, STU) VALUES((SELECT GETDATE()), 'Aguardando');
INSERT INTO CVA_STU(INS, STU) VALUES((SELECT GETDATE()), 'Replicado');
INSERT INTO CVA_STU(INS, STU) VALUES((SELECT GETDATE()), 'Erro');
