//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.AddOn.Hub.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.AddOn.Hub.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;update&quot;&gt;
        ///      &lt;form uid=&quot;&quot; left=&quot;100&quot; top=&quot;0&quot; width=&quot;892&quot; height=&quot;538&quot; client_width=&quot;858&quot; client_height=&quot;499&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/DataTables&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/dbdatasources&gt;
        ///          &lt;userdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/userdatasources&gt;
        ///        &lt;/datasources&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string x150 {
            get {
                return ResourceManager.GetString("x150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;update&quot;&gt;
        ///      &lt;form uid=&quot;&quot; left=&quot;256&quot; top=&quot;123&quot; width=&quot;722&quot; height=&quot;292&quot; client_width=&quot;706&quot; client_height=&quot;253&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/DataTables&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/dbdatasources&gt;
        ///          &lt;userdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/userdatasources&gt;
        ///        &lt;/datasource [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string x2105 {
            get {
                return ResourceManager.GetString("x2105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;update&quot;&gt;
        ///      &lt;form uid=&quot;&quot; left=&quot;256&quot; top=&quot;123&quot; width=&quot;722&quot; height=&quot;292&quot; client_width=&quot;706&quot; client_height=&quot;253&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/DataTables&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/dbdatasources&gt;
        ///          &lt;userdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/userdatasources&gt;
        ///        &lt;/datasource [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string x82105 {
            get {
                return ResourceManager.GetString("x82105", resourceCulture);
            }
        }
    }
}
