//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA_Rep_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVA_ATL_REPEntities : DbContext
    {
        public CVA_ATL_REPEntities()
            : base("name=CVA_ATL_REPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CVA_BAS> CVA_BAS { get; set; }
        public virtual DbSet<CVA_FUNC> CVA_FUNC { get; set; }
        public virtual DbSet<CVA_OBJ> CVA_OBJ { get; set; }
        public virtual DbSet<CVA_REG> CVA_REG { get; set; }
        public virtual DbSet<CVA_REG_LOG> CVA_REG_LOG { get; set; }
        public virtual DbSet<CVA_STU> CVA_STU { get; set; }
        public virtual DbSet<CVA_TIM> CVA_TIM { get; set; }
        public virtual DbSet<CVA_TIP_REG> CVA_TIP_REG { get; set; }
        public virtual DbSet<CVA_EML> CVA_EML { get; set; }
    }
}
