//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA_Rep_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVA_BAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CVA_BAS()
        {
            this.CVA_REG = new HashSet<CVA_REG>();
            this.CVA_REG_LOG = new HashSet<CVA_REG_LOG>();
            this.CVA_REG1 = new HashSet<CVA_REG>();
        }
    
        public int ID { get; set; }
        public System.DateTime INS { get; set; }
        public Nullable<System.DateTime> UPD { get; set; }
        public Nullable<int> STU { get; set; }
        public string SRVR { get; set; }
        public string PAS { get; set; }
        public string COMP { get; set; }
        public Nullable<int> USE_TRU { get; set; }
        public string UNAME { get; set; }
        public string DB_UNAME { get; set; }
        public string DB_PAS { get; set; }
        public Nullable<int> DB_TYP { get; set; }
        public string DB_SRVR { get; set; }
    
        public virtual CVA_STU CVA_STU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CVA_REG> CVA_REG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CVA_REG_LOG> CVA_REG_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CVA_REG> CVA_REG1 { get; set; }
    }
}
