IF EXISTS (SELECT * FROM sys.objects WHERE type = 'TF' AND name = 'FN_CVA_SEF_E100')
	DROP FUNCTION FN_CVA_SEF_E100
GO

--- SELECT * FROM FN_CVA_SEF_E100 (9,'2018-01-01', '2018-01-31')
CREATE FUNCTION FN_CVA_SEF_E100


(
	@Filial			INT,
	@DataInicial	DATETIME,
	@DataFinal		DATETIME
) 



RETURNs @Docs TABLE

	(
		DocEntry		  VARCHAR(50),
		ObjType			  INT,	
		IND_OPER		  INT,
		IND_EMIT		  INT,
		COD_PART		  VARCHAR(100),
		COD_MUN_SERV	  VARCHAR(50),
		COD_MOD			  VARCHAR(10),
		COD_SIT			  VARCHAR(10),
		QTD_CANC		  VARCHAR(10),
		SER				  VARCHAR(10),
		SUB				  VARCHAR(10),
		COD_CONS		  VARCHAR(10),
		NUM_DOC			  VARCHAR(30),
		QTD_DOC			  VARCHAR(1),
		DT_EMIS			  VARCHAR(8),
		DT_DOC			  DATETIME,
		--COD_NAT			  INT,	
		CODNAT		      VARCHAR(4),
		NUM_LCTO		  VARCHAR(50),
		VL_CONT			  NUMERIC(19,2),
		VL_OP_ISS		  NUMERIC(19,2),
		VL_BC_ICMS		  NUMERIC(19,2),
		VL_ICMS			  NUMERIC(19,2),
		VL_ICMS_ST		  NUMERIC(19,2),
		VL_ISNT_ICMS	  NUMERIC(19,2),
		VL_OUT_ICMS		  NUMERIC(19,2),
		COD_INF_OBS		  VARCHAR(10),
		UF				  VARCHAR(2),
		CFOP		      VARCHAR(4)
	)


AS 
BEGIN 

DECLARE @DOCS2 TABLE

(
		DocEntry		  VARCHAR(50),
		ObjType			  INT,	
		IND_OPER		  INT,
		IND_EMIT		  INT,
		COD_PART		  VARCHAR(100),
		COD_MUN_SERV	  VARCHAR(50),
		COD_MOD			  VARCHAR(10),
		COD_SIT			  VARCHAR(10),
		QTD_CANC		  VARCHAR(10),
		SER				  VARCHAR(10),
		SUB				  VARCHAR(10),
		COD_CONS		  VARCHAR(10),
		NUM_DOC			  VARCHAR(30),
		QTD_DOC			  VARCHAR(1),
		DT_EMIS			  VARCHAR(8),
		DT_DOC			  DATETIME,
		--COD_NAT			  INT,	
		CODNAT		      VARCHAR(4),
		NUM_LCTO		  VARCHAR(50),
		VL_CONT			  NUMERIC(19,2),
		VL_OP_ISS		  NUMERIC(19,2),
		VL_BC_ICMS		  NUMERIC(19,2),
		VL_ICMS			  NUMERIC(19,2),
		VL_ICMS_ST		  NUMERIC(19,2),
		VL_ISNT_ICMS	  NUMERIC(19,2),
		VL_OUT_ICMS		  NUMERIC(19,2),
		COD_INF_OBS		  VARCHAR(10),
		UF				  VARCHAR(2),
		CFOP			  VARCHAR(4)

	)


	INSERT INTO  @DOCS2 
	

		SELECT  DISTINCT
		OPCH.DocEntry,
		OPCH.ObjType,
		0					IND_OPER,
		1					IND_EMIT,
		REPLACE(REPLACE(OPCH.CardCode,'F','FOR'),'C','CLI')		COD_PART,
		--''					COD_PART,
		''					COD_MUN_SERV,
		REPLICATE('0',2 - Len(ONFM.NfmCode)) + RTRIM((ONFM.NfmCode))		COD_MOD,
		'00'				COD_SIT,
		''					QTD_CANC,
		1					SER,
		''					SUB,
		''					COD_CONS,
		OPCH.Serial			NUM_DOC,
		'1'					QTD_DOC,
		''					DT_EMIS,
		OPCH.DocDate		DT_DOC,
		--CODNAT.COD			COD_NAT,
		CODNAT.CODNAT  		COP,
		OPCH.DocNum			NUM_LCTO,
		--OPCH.DocTotal		VL_CONT,
		CASE WHEN OPCH.DocTotal	= 0 THEN OPCH.Max1099 ELSE OPCH.DocTotal END	VL_CONT,
		ISNULL(ISS.BaseSum,0)			VL_OP_ISS,
		ISNULL(ICMS.BaseSum,0)			VL_BC_ICMS,
		ISNULL(ICMS.TaxSum,0)			VL_ICMS,
		ISNULL(ICMS_ST.TaxSum,0)		VL_ICMS_ST,
		ISNULL(ICMS.Isentas,0)			VL_ISNT_ICMS,
		ISNULL(ICMS.Outras,0)			VL_OUT_ICMS,
		''								COD_INF_OBS,
		PCH12.StateS					UF,
		(SELECT TOP 1 CFOPCODE FROM PCH1 WHERE DOCENTRY = OPCH.DOCENTRY) CFOP

	FROM OPCH WITH(NOLOCK)
		INNER JOIN PCH1 WITH(NOLOCK)
			ON PCH1.DocEntry = OPCH.DocEntry
		INNER JOIN ONFM WITH(NOLOCK)
			ON ONFM.AbsEntry = OPCH.Model
		INNER JOIN OUSG WITH(NOLOCK)
			ON OUSG.Id = PCH1.Usage
		LEFT JOIN (SELECT FRETE.DocEntry, SUM(FRETE.LineTotal) ValorFrete FROM PCH3 FRETE WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON FRETE.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%FRETE%' GROUP BY FRETE.DocEntry) FRETE
			ON FRETE.DocEntry = OPCH.DocEntry
		LEFT JOIN (SELECT SEGURO.DocEntry, SUM(SEGURO.LineTotal) ValorSeguro FROM PCH3 SEGURO WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON SEGURO.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%SEGURO%' GROUP BY SEGURO.DocEntry) SEGURO
			ON SEGURO.DocEntry = OPCH.DocEntry
		LEFT JOIN (SELECT OUTROS.DocEntry, SUM(OUTROS.LineTotal) ValorOutrasDespesas FROM PCH3 OUTROS WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON OUTROS.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName NOT LIKE '%FRETE%' AND OEXD.ExpnsName NOT LIKE '%SEGURO%' GROUP BY OUTROS.DocEntry) OUTROS
			ON OUTROS.DocEntry = OPCH.DocEntry
		LEFT JOIN (
					SELECT PCH4.DocEntry,  SUM(PCH4.TaxSum) TaxSum, SUM(PCH4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
					FROM PCH4 WITH(NOLOCK) 
						INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PCH4.StaType
						INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code IN ('ISS', 'ISSQN')
					GROUP BY PCH4.DocEntry
				) ISS
			ON ISS.DocEntry = PCH1.DocEntry
		LEFT JOIN (
				SELECT PCH4.DocEntry, SUM(PCH4.TaxSum) TaxSum, SUM(PCH4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
				FROM PCH4 WITH(NOLOCK) 
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PCH4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS'
				GROUP BY PCH4.DocEntry
			) ICMS
			ON ICMS.DocEntry = PCH1.DocEntry
		LEFT JOIN (
			SELECT PCH4.DocEntry, SUM(PCH4.TaxSum) TaxSum, SUM(PCH4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM PCH4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PCH4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY PCH4.DocEntry
		) ICMS_ST
			ON ICMS_ST.DocEntry = PCH1.DocEntry
		LEFT JOIN (
			SELECT PCH4.DocEntry, SUM(PCH4.TaxSum) TaxSum, SUM(PCH4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM PCH4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PCH4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'IPI'
			GROUP BY PCH4.DocEntry
		) IPI
			ON IPI.DocEntry = PCH1.DocEntry
		LEFT JOIN CODNAT  ON (SELECT TOP 1 CFOPCODE FROM PCH1 WHERE DOCENTRY = OPCH.DOCENTRY) = CODNAT.CFOP
		LEFT JOIN PCH12 ON PCH12.Docentry = OPCH.DocEntry

	WHERE OPCH.DocDate BETWEEN @DataInicial AND @DataFinal
	AND OPCH.BPLId = @Filial
	AND OPCH.CANCELED = 'N' AND Model IN (6, 19, 22)




	INSERT INTO @Docs
		SELECT * FROM @DOCS2 
		-- WHERE (VL_ICMS <> 0 OR VL_OP_ISS <> 0)

RETURN
END

