IF EXISTS (SELECT * FROM sys.objects WHERE type = 'TF' AND name = 'FN_CVA_SEF_E330')
	DROP FUNCTION FN_CVA_SEF_E330
GO


--- SELECT * FROM FN_CVA_SEF_E330 (9,'2018-01-01', '2018-01-31')
CREATE FUNCTION FN_CVA_SEF_E330
(
	@Filial			INT,
	@DataInicial	DATETIME,
	@DataFinal		DATETIME
) RETURNS @DOCS TABLE

	(

	IND_TOT				INT,
	VL_CONT				DECIMAL(19,2),
	VL_OP_ISS			DECIMAL(19,2),
	VL_BC_ICMS			DECIMAL(19,2),
	VL_ICMS				DECIMAL(19,2),
	VL_ICMS_ST			DECIMAL(19,2),
	VL_ST_ENT			DECIMAL(19,2),
	VL_ST_FNT			DECIMAL(19,2),
	VL_ST_UF			DECIMAL(19,2),
	VL_ST_OE			DECIMAL(19,2),
	VL_AT				DECIMAL(19,2),
	VL_ISNT_ICMS		DECIMAL(19,2),
	VL_OUT_ICMS			DECIMAL(19,2)
	)


AS
BEGIN

DECLARE @DOCS2 TABLE

	(

	IND_TOT				INT,
	VL_CONT				DECIMAL(19,2),
	VL_OP_ISS			DECIMAL(19,2),
	VL_BC_ICMS			DECIMAL(19,2),
	VL_ICMS				DECIMAL(19,2),
	VL_ICMS_ST			DECIMAL(19,2),
	VL_ST_ENT			DECIMAL(19,2),
	VL_ST_FNT			DECIMAL(19,2),
	VL_ST_UF			DECIMAL(19,2),
	VL_ST_OE			DECIMAL(19,2),
	VL_AT				DECIMAL(19,2),
	VL_ISNT_ICMS		DECIMAL(19,2),
	VL_OUT_ICMS			DECIMAL(19,2)

	)

DECLARE @DOCS3 TABLE

	(

	DOCENTRY			VARCHAR(50),
	OBJTYPE				INT,
	IND_EMIT			VARCHAR(10),
	UF					VARCHAR(2),
	CFOP				VARCHAR(4),
	VL_CONT				DECIMAL(19,2),
	VL_OP_ISS			DECIMAL(19,2),
	VL_BC_ICMS			DECIMAL(19,2),
	VL_ICMS				DECIMAL(19,2),
	VL_ICMS_ST			DECIMAL(19,2),
	VL_ISNT_ICMS		DECIMAL(19,2),
	VL_OUT_ICMS			DECIMAL(19,2)

	)


INSERT INTO @DOCS3
	SELECT DOCENTRY, OBJTYPE, IND_EMIT, UF, CFOP, VL_CONT, VL_OP_ISS, VL_BC_ICMS, VL_ICMS, VL_ICMS_ST,  VL_ISNT_ICMS, VL_OUT_ICMS  FROM FN_CVA_SEF_E020 (@Filial,@DataInicial, @DataFinal)  
	UNION ALL 
	SELECT DOCENTRY, OBJTYPE, IND_EMIT, UF, CFOP, VL_CONT, VL_OP_ISS, VL_BC_ICMS, VL_ICMS, VL_ICMS_ST,  VL_ISNT_ICMS, VL_OUT_ICMS  FROM FN_CVA_SEF_E100 (@Filial,@DataInicial, @DataFinal) 
	UNION ALL 
	SELECT DOCENTRY, OBJTYPE, IND_EMIT, UF, CFOP, VL_CONT, 0.00,      VL_BC_ICMS, VL_ICMS, VL_ICMS_ST,  VL_ISNT_ICMS, VL_OUT_ICMS  FROM FN_CVA_SEF_E120  (@Filial,@DataInicial, @DataFinal) 			


INSERT INTO @DOCS2

	SELECT
		/*02*/ 1					
		/*03*/ ,SUM(VL_CONT)				
		/*04*/ ,SUM(VL_OP_ISS)			
		/*05*/ ,SUM(VL_BC_ICMS)			
		/*06*/ ,SUM(VL_ICMS)				
		/*07*/ ,SUM(VL_ICMS_ST)		
		/*08*/ ,(SELECT ISNULL(SUM(VL_ICMS_ST),0) FROM @DOCS3 WHERE IND_EMIT = '0' AND CFOP LIKE '1%'  )					
		/*09*/ ,(SELECT ISNULL(SUM(VL_ICMS_ST),0) FROM @DOCS3 WHERE IND_EMIT = '1' AND CFOP LIKE '1%'  )				
		/*10*/ ,0.00				
		/*11*/ ,0.00				
		/*12*/ ,0.00				
		/*13*/ ,SUM(VL_ISNT_ICMS)		
		/*14*/ ,SUM(VL_OUT_ICMS)			
	FROM @DOCS3 
		LEFT JOIN OBPL ON @Filial = OBPL.BPLId
		WHERE 0=0
			AND CFOP LIKE '1%'

INSERT INTO @DOCS2

	SELECT
		/*02*/ 2					
		/*03*/ ,SUM(VL_CONT)				
		/*04*/ ,SUM(VL_OP_ISS)			
		/*05*/ ,SUM(VL_BC_ICMS)			
		/*06*/ ,SUM(VL_ICMS)				
		/*07*/ ,SUM(VL_ICMS_ST)		
		/*08*/ ,(SELECT ISNULL(SUM(VL_ICMS_ST),0) FROM @DOCS3 WHERE IND_EMIT = '0' AND CFOP LIKE '2%'  )					
		/*09*/ ,(SELECT ISNULL(SUM(VL_ICMS_ST),0) FROM @DOCS3 WHERE IND_EMIT = '1' AND CFOP LIKE '2%'  )				
		/*10*/ ,0.00				
		/*11*/ ,0.00				
		/*12*/ ,0.00				
		/*13*/ ,SUM(VL_ISNT_ICMS)		
		/*14*/ ,SUM(VL_OUT_ICMS)			
	FROM @DOCS3 
		LEFT JOIN OBPL ON @Filial = OBPL.BPLId
		WHERE 0=0
			AND CFOP LIKE '2%'

INSERT INTO @DOCS2

	SELECT
		/*02*/ 4					
		/*03*/ ,SUM(VL_CONT)				
		/*04*/ ,SUM(VL_OP_ISS)			
		/*05*/ ,SUM(VL_BC_ICMS)			
		/*06*/ ,SUM(VL_ICMS)				
		/*07*/ ,SUM(VL_ICMS_ST)		
		/*08*/ ,(SELECT ISNULL(SUM(VL_ICMS_ST),0) FROM @DOCS3 WHERE IND_EMIT = '0' AND CFOP LIKE '1%' OR CFOP LIKE '2%')					
		/*09*/ ,(SELECT ISNULL(SUM(VL_ICMS_ST),0) FROM @DOCS3 WHERE IND_EMIT = '1' AND CFOP LIKE '1%' OR CFOP LIKE '2%')				
		/*10*/ ,0.00				
		/*11*/ ,0.00				
		/*12*/ ,0.00				
		/*13*/ ,SUM(VL_ISNT_ICMS)		
		/*14*/ ,SUM(VL_OUT_ICMS)			
	FROM @DOCS3 
		LEFT JOIN OBPL ON @Filial = OBPL.BPLId
		WHERE 0=0
			AND CFOP LIKE '1%' OR CFOP LIKE '2%'


INSERT INTO @DOCS2
	SELECT
		/*02*/ 5					
		/*03*/ ,SUM(VL_CONT)				
		/*04*/ ,SUM(VL_OP_ISS)			
		/*05*/ ,SUM(VL_BC_ICMS)			
		/*06*/ ,SUM(VL_ICMS)				
		/*07*/ ,SUM(VL_ICMS_ST)		
		/*08*/ ,0.00					
		/*09*/ ,0.00				
		/*10*/ ,(SELECT ISNULL(SUM(VL_ICMS_ST),0) FROM @DOCS3 WHERE CFOP LIKE '5%')				
		/*11*/ ,0.00				
		/*12*/ ,0.00				
		/*13*/ ,SUM(VL_ISNT_ICMS)		
		/*14*/ ,SUM(VL_OUT_ICMS)			
	FROM @DOCS3 
		LEFT JOIN OBPL ON @Filial = OBPL.BPLId
		WHERE 0=0
			AND CFOP LIKE '5%'

INSERT INTO @DOCS2
	SELECT
		/*02*/  6					
		/*03*/ ,SUM(VL_CONT)				
		/*04*/ ,SUM(VL_OP_ISS)			
		/*05*/ ,SUM(VL_BC_ICMS)			
		/*06*/ ,SUM(VL_ICMS)				
		/*07*/ ,SUM(VL_ICMS_ST)		
		/*08*/ ,0.00					
		/*09*/ ,0.00				
		/*10*/ ,0.00		
		/*11*/ ,(SELECT ISNULL(SUM(VL_ICMS_ST),0) FROM @DOCS3 WHERE CFOP LIKE '6%')						
		/*12*/ ,0.00				
		/*13*/ ,SUM(VL_ISNT_ICMS)		
		/*14*/ ,SUM(VL_OUT_ICMS)			
	FROM @DOCS3 
		LEFT JOIN OBPL ON @Filial = OBPL.BPLId
		WHERE 0=0
			AND CFOP LIKE '6%'

INSERT INTO @DOCS2
	SELECT
		/*02*/  8					
		/*03*/ ,SUM(VL_CONT)				
		/*04*/ ,SUM(VL_OP_ISS)			
		/*05*/ ,SUM(VL_BC_ICMS)			
		/*06*/ ,SUM(VL_ICMS)				
		/*07*/ ,SUM(VL_ICMS_ST)		
		/*08*/ ,0.00					
		/*09*/ ,0.00				
		/*10*/ ,(SELECT ISNULL(SUM(VL_ICMS_ST),0) FROM @DOCS3 WHERE CFOP LIKE '5%')			
		/*11*/ ,(SELECT ISNULL(SUM(VL_ICMS_ST),0) FROM @DOCS3 WHERE CFOP LIKE '6%')						
		/*12*/ ,0.00				
		/*13*/ ,SUM(VL_ISNT_ICMS)		
		/*14*/ ,SUM(VL_OUT_ICMS)			
	FROM @DOCS3 
		LEFT JOIN OBPL ON @Filial = OBPL.BPLId
		WHERE 0=0
			AND CFOP LIKE '5%' OR CFOP LIKE '6%'





INSERT INTO @DOCS
		SELECT * FROM @DOCS2

RETURN 

END


