IF EXISTS (SELECT * FROM sys.objects WHERE type = 'IF' AND name = 'FN_CVA_SEF_E500')
	DROP FUNCTION FN_CVA_SEF_E500
GO
CREATE FUNCTION FN_CVA_SEF_E500
(
	@Filial			INT,
	@DataInicial	DATETIME,
	@DataFinal		DATETIME
) RETURNS TABLE
AS
RETURN
(
	SELECT @DataInicial DT_INI, @DataFinal DT_FIN
)
