DROP TABLE CODNATOPER
CREATE TABLE CODNATOPER

(
	COD_NAT     INT,
	COP     VARCHAR (4),
	DESCR_NAT    VARCHAR (200),


)

INSERT INTO CODNATOPER  VALUES (1,'EA10','Compra')
INSERT INTO CODNATOPER  VALUES (2,'EA20','Devolução de venda')
INSERT INTO CODNATOPER  VALUES (3,'EA30','Retorno de remessa')
INSERT INTO CODNATOPER  VALUES (4,'EA40','Devolução de remessa')
INSERT INTO CODNATOPER  VALUES (5,'EA50','Entrada')
INSERT INTO CODNATOPER  VALUES (6,'EA60','Transferência')
INSERT INTO CODNATOPER  VALUES (7,'EA65','Ajuste de estoque')
INSERT INTO CODNATOPER  VALUES (8,'EA70','Aquisição de serviço')
INSERT INTO CODNATOPER  VALUES (9,'EA80','Anulação de valor')
INSERT INTO CODNATOPER  VALUES (10,'EA90','Operação financeira')
INSERT INTO CODNATOPER  VALUES (11,'EA91','Ressarcimento de valor')
INSERT INTO CODNATOPER  VALUES (12,'EA99','Outras entradas/aquisições')
INSERT INTO CODNATOPER  VALUES (13,'SP10','Venda')
INSERT INTO CODNATOPER  VALUES (14,'SP20','Devolução de compra')
INSERT INTO CODNATOPER  VALUES (15,'SP30','Remessa')
INSERT INTO CODNATOPER  VALUES (16,'SP50','Retorno')
INSERT INTO CODNATOPER  VALUES (17,'SP60','Transferência')
INSERT INTO CODNATOPER  VALUES (18,'SP65','Ajuste de estoque')
INSERT INTO CODNATOPER  VALUES (19,'SP70','Prestação de serviço')
INSERT INTO CODNATOPER  VALUES (20,'SP80','Anulação de valor')
INSERT INTO CODNATOPER  VALUES (21,'SP90','Operação financeira')
INSERT INTO CODNATOPER  VALUES (22,'SP91','Ressarcimento de valor')
INSERT INTO CODNATOPER  VALUES (23,'SP99','Outras saídas/prestações')

