IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CVA_WAYBILL_INVITEM')
	DROP PROCEDURE CVA_WAYBILL_INVITEM
GO

CREATE PROCEDURE CVA_WAYBILL_INVITEM
( 
	@DocKey NVARCHAR(30),
	@DocNum INT
) 
AS   
BEGIN
	SELECT
		INV1.ItemCode,
		INV1.Dscription,
		INV1.Quantity
	FROM OINV
		INNER JOIN INV1
			ON INV1.DocEntry = OINV.DocEntry
		INNER JOIN OITM
			ON OITM.ItemCode = INV1.ItemCode
	WHERE OINV.DocNum = @DocNum
END