IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CVA_WAYBILL_PACK')
	DROP PROCEDURE CVA_WAYBILL_PACK
GO

CREATE PROCEDURE CVA_WAYBILL_PACK
( 
	@DocKey NVARCHAR(30)  
) 
AS   
BEGIN
	SELECT
		OITM.SalPackMsr		Pack,
		SUM(INV1.PackQty)	PackQty
	FROM [@CVA_WAYBILL_INV] INV
		INNER JOIN OINV
			ON OINV.DocNum = INV.U_DocNum
		INNER JOIN INV1
			ON INV1.DocEntry = OINV.DocEntry
		INNER JOIN OITM
			ON OITM.ItemCode = INV1.ItemCode
	WHERE INV.Code = @DocKey
	GROUP BY OITM.SalPackMsr
END