SELECT PROD_LOG.*, LOG_ERRO.*
FROM SSPExportProd PROD 
	INNER JOIN SSPExportProd_LOG PROD_LOG ON PROD.ID = PROD_LOG.ID_MES
	INNER JOIN SSPExportProd_LOG LOG_ERRO
		 ON LOG_ERRO.ID_MES = PROD_LOG.ID_MES AND 
		 ((LOG_ERRO.TYPE = 0 AND LOG_ERRO.Status NOT IN (0, 1, 2))
		 OR (LOG_ERRO.TYPE = 1 AND LOG_ERRO.Status NOT IN (0, 1, 2)))
WHERE  PROD_LOG.Status = 0
AND PROD_LOG.TYPE IN (1, 3)

UPDATE PROD_LOG SET
	PROD_LOG.Status = LOG_ERRO.Status, 
	PROD_LOG.Description = LOG_ERRO.Description
FROM SSPExportProd PROD 
	INNER JOIN SSPExportProd_LOG PROD_LOG ON PROD.ID = PROD_LOG.ID_MES
	INNER JOIN SSPExportProd_LOG LOG_ERRO
		 ON LOG_ERRO.ID_MES = PROD_LOG.ID_MES AND 
		 ((LOG_ERRO.TYPE = 0 AND LOG_ERRO.Status NOT IN (0, 1, 2))
		 OR (LOG_ERRO.TYPE = 1 AND LOG_ERRO.Status NOT IN (0, 1, 2)))
WHERE  PROD_LOG.Status = 0
AND PROD_LOG.TYPE IN (1, 3)