//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.View.EmissorEtiqueta.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Etiquetas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Etiquetas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.View.EmissorEtiqueta.Resources.Etiquetas", typeof(Etiquetas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I8,A,001
        ///
        ///
        ///Q200,024
        ///q863
        ///rN
        ///S2
        ///D11
        ///ZT
        ///JF
        ///OD
        ///R172,0
        ///f100
        ///N
        ///GW280,114,3,27,ÿÿÿÿÿÿð ÷ÿÿ÷ÿû÷ÿÿ÷ÿÿ÷ÿÿ÷ÿÿ÷ÿÿûÿýýÿÿsÿÿwÿþûÿýþÿ÷ÿÿÿÿð ð ð ð {ð ð ð ÿÿÿÿÿÿ
        ///GW264,84,6,32,ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿð    ÿð    ÿóÿÿÿþÿóÿÿÿþÿóÿÿÿþÿóÿÿÿþÿóÏýøÿóÏà8ÿóÏà8ÿóÏÇ&gt;~ÿóÏÏž~ÿóÏÏž~ÿóÏÏž~ÿóÏÏ~ÿóÏÇ&gt;~ÿóÀà&gt;~ÿóÀð~~ÿóÿÿÿþÿóÿÿÿþÿóÿÿÿþÿóÿÿÿþÿóÿÿÿþÿð    ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
        ///GW113,76,6,38,ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿà    ïÿÿÿÿïÿÿÿÿïàïàïœçùÿïœçùÿïœçùÿ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Componente {
            get {
                return ResourceManager.GetString("Componente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I8,A,001
        ///
        ///
        ///Q256,024
        ///q831
        ///rN
        ///S2
        ///D15
        ///ZT
        ///JF
        ///O
        ///R0,0
        ///f100
        ///N
        ///GW499,141,3,25,ÿÿÿÿÿÿð ÷ÿÿ÷ÿû÷ÿÿ÷ÿÿ÷ÿÿ÷ÿÿ÷ÿýüÿÿsÿÿwÿþûÿûþÿ÷ÿÿð ð ð ð ð ð ð ÿÿÿÿÿÿ
        ///GW494,97,6,30,ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿð   ÿð   ÿóÿÿÿ÷ÿóÿÿÿ÷ÿóÿÿÿ÷ÿóÿÿÿ÷ÿóŸÁà7ÿóŸÀà7ÿóŸŒy÷ÿóŸžy÷ÿóŸžy÷ÿóŸžy÷ÿóŸžy÷ÿóŸŒy÷ÿóÀù÷ÿóÁù÷ÿóÿÿÿ÷ÿóÿÿÿ÷ÿóÿÿÿ÷ÿóÿÿÿ÷ÿð   ÿð   ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
        ///GW285,88,6,38,ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿà    ÿïÿÿÿþÿïÿÿÿþÿïà0&gt;ÿïà0&gt;ÿïïóþÿïïóþÿïïóþÿï àp&gt;ÿïàp&gt;ÿïïóþÿïà [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Implante {
            get {
                return ResourceManager.GetString("Implante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I8,A,001
        ///
        ///
        ///Q200,024
        ///q831
        ///rN
        ///S2
        ///D15
        ///ZT
        ///JF
        ///O
        ///R239,0
        ///f100
        ///N
        ///GW292,62,5,24,ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿø   ÿø   ÿûÿÿüÿûÿÿüÿûÿÿüÿûßÿûÞgÌÿûÞgÌÿûÞ÷ÌÿûÞ÷ÌÿûÞgÌÿúÌÿúÌÿûÿÿüÿûÿÿüÿûÿÿüÿø   ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
        ///GW192,63,5,27,ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿþ  ÿþÿÿÿÿþÿÿÿÿþÿÿÿÿþÿÿÿÿþÿÿÿÿþÿÿÿÿþ÷½ÿÿþóœïÿþóZßÿþõg_ÿþö÷¿ÿþ÷ÿÿÿþ÷ÿÿÿþ÷ÿÿÿþ÷ÿÿÿþ÷ÿÿÿþ÷ÿÿÿþ÷ÿÿÿþÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
        ///GW110,63,3,27,ÿÿÿÿÿÿø ø ø x ø ø ø ÿÿÿûÿßþÿÿ|ÿÿûÿÿ½ÿþ~ÿùÿ¿ÿÿßÿÿßÿÿßÿÿßÿÿßÿßÿÿßø ÿÿÿÿÿÿ
        ///GW149,99,4,27,ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿà  ÿÿÿûÿÿÿûÿÿÿûÿÿÿûÿÈ;ÿÈ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interna {
            get {
                return ResourceManager.GetString("Interna", resourceCulture);
            }
        }
    }
}
