//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.View.FolhaPagamento.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.View.FolhaPagamento.Resources.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT BPlId, BPlName FROM OBPL.
        /// </summary>
        internal static string Branch_Get {
            get {
                return ResourceManager.GetString("Branch_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///	Code,
        ///	U_Server	[Server],
        ///	U_Port		[Port],
        ///	U_SSL		[SSL],
        ///	U_User		[User],
        ///	U_Password	[Password],
        ///	U_Subject	[Subject],
        ///	U_Message	[Message]
        /// FROM [@CVA_EMAIL_ACTIVITY].
        /// </summary>
        internal static string EmailConfig_Get {
            get {
                return ResourceManager.GetString("EmailConfig_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT
        ///	CASE OCLG.[Action]
        ///		WHEN &apos;C&apos; THEN &apos;Telefonema&apos;
        ///		WHEN &apos;M&apos; THEN &apos;Reunião&apos;
        ///		WHEN &apos;E&apos; THEN &apos;Nota&apos;
        ///		WHEN &apos;P&apos; THEN &apos;Campanha&apos;
        ///		WHEN &apos;N&apos; THEN &apos;Outros&apos;
        ///	END [Action],
        ///	OCLT.Name CntctType,
        ///	OCLS.Name CntctSbjct,
        ///	CASE WHEN AttendUser IS NOT NULL
        ///		THEN OUSR.U_NAME
        ///		ELSE OHEM.firstName
        ///	END [User],
        ///	OCLG.ClgCode,
        ///	OCRD.CardCode,
        ///	OCRD.CardName,
        ///	OCLG.Details,
        ///	OCLG.Recontact,
        ///	OCLG.endDate EndDate,
        ///	OCLG.DocType,
        ///	OCLG.DocNum,
        ///	CASE WHEN AttendUser IS NOT NULL
        ///		THEN OUSR.E_Mail        /// [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string EmailTags_Get {
            get {
                return ResourceManager.GetString("EmailTags_Get", resourceCulture);
            }
        }
    }
}
