using System.Collections.Generic;

namespace Escoteiro.Magento.Models.SAP
{
    public class ItemPrice
    {
        public int PriceList { get; set; }
        public double Price { get; set; }
        public object Currency { get; set; }
        public double AdditionalPrice1 { get; set; }
        public object AdditionalCurrency1 { get; set; }
        public double AdditionalPrice2 { get; set; }
        public object AdditionalCurrency2 { get; set; }
        public int BasePriceList { get; set; }
        public double Factor { get; set; }
        public object U_CVA_Validade { get; set; }
        public List<object> UoMPrices { get; set; }
    }

    public class ItemWarehouseInfoCollection
    {
        public double MinimalStock { get; set; }
        public double MaximalStock { get; set; }
        public double MinimalOrder { get; set; }
        public double StandardAveragePrice { get; set; }
        public string Locked { get; set; }
        public object InventoryAccount { get; set; }
        public object CostAccount { get; set; }
        public object TransferAccount { get; set; }
        public object RevenuesAccount { get; set; }
        public object VarienceAccount { get; set; }
        public object DecreasingAccount { get; set; }
        public object IncreasingAccount { get; set; }
        public object ReturningAccount { get; set; }
        public object ExpensesAccount { get; set; }
        public object EURevenuesAccount { get; set; }
        public object EUExpensesAccount { get; set; }
        public object ForeignRevenueAcc { get; set; }
        public object ForeignExpensAcc { get; set; }
        public object ExemptIncomeAcc { get; set; }
        public object PriceDifferenceAcc { get; set; }
        public string WarehouseCode { get; set; }
        public double InStock { get; set; }
        public double Committed { get; set; }
        public double Ordered { get; set; }
        public double CountedQuantity { get; set; }
        public string WasCounted { get; set; }
        public int UserSignature { get; set; }
        public double Counted { get; set; }
        public object ExpenseClearingAct { get; set; }
        public object PurchaseCreditAcc { get; set; }
        public object EUPurchaseCreditAcc { get; set; }
        public object ForeignPurchaseCreditAcc { get; set; }
        public object SalesCreditAcc { get; set; }
        public object SalesCreditEUAcc { get; set; }
        public object ExemptedCredits { get; set; }
        public object SalesCreditForeignAcc { get; set; }
        public object ExpenseOffsettingAccount { get; set; }
        public object WipAccount { get; set; }
        public object ExchangeRateDifferencesAcct { get; set; }
        public object GoodsClearingAcct { get; set; }
        public object NegativeInventoryAdjustmentAccount { get; set; }
        public object CostInflationOffsetAccount { get; set; }
        public object GLDecreaseAcct { get; set; }
        public object GLIncreaseAcct { get; set; }
        public object PAReturnAcct { get; set; }
        public object PurchaseAcct { get; set; }
        public object PurchaseOffsetAcct { get; set; }
        public object ShippedGoodsAccount { get; set; }
        public object StockInflationOffsetAccount { get; set; }
        public object StockInflationAdjustAccount { get; set; }
        public object VATInRevenueAccount { get; set; }
        public object WipVarianceAccount { get; set; }
        public object CostInflationAccount { get; set; }
        public object WHIncomingCenvatAccount { get; set; }
        public object WHOutgoingCenvatAccount { get; set; }
        public object StockInTransitAccount { get; set; }
        public object WipOffsetProfitAndLossAccount { get; set; }
        public object InventoryOffsetProfitAndLossAccount { get; set; }
        public object DefaultBin { get; set; }
        public string DefaultBinEnforced { get; set; }
        public object PurchaseBalanceAccount { get; set; }
        public string ItemCode { get; set; }
        public List<object> ItemCycleCounts { get; set; }
    }

    public class ItemUnitOfMeasurementCollection
    {
        public string UoMType { get; set; }
        public int UoMEntry { get; set; }
        public int? DefaultBarcode { get; set; }
        public object DefaultPackage { get; set; }
        public double? Length1 { get; set; }
        public object Length1Unit { get; set; }
        public double? Length2 { get; set; }
        public object Length2Unit { get; set; }
        public double? Width1 { get; set; }
        public object Width1Unit { get; set; }
        public double? Width2 { get; set; }
        public object Width2Unit { get; set; }
        public double? Height1 { get; set; }
        public object Height1Unit { get; set; }
        public double? Height2 { get; set; }
        public object Height2Unit { get; set; }
        public double? Volume { get; set; }
        public int? VolumeUnit { get; set; }
        public double? Weight1 { get; set; }
        public object Weight1Unit { get; set; }
        public double? Weight2 { get; set; }
        public object Weight2Unit { get; set; }
        public List<object> ItemUoMPackageCollection { get; set; }
    }

    public class ItemBarCodeCollection
    {
        public int AbsEntry { get; set; }
        public int UoMEntry { get; set; }
        public string Barcode { get; set; }
        public object FreeText { get; set; }
        public object U_CVA_Qtde_CodBarras { get; set; }
    }

    public class ItemIntrastatExtension
    {
    }

    public class ItemsMasterDataModel
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        //public object ForeignName { get; set; }
        //public int ItemsGroupCode { get; set; }
        //public int CustomsGroupCode { get; set; }
        //public object SalesVATGroup { get; set; }
        public string BarCode { get; set; }
        //public string VatLiable { get; set; }
        //public string PurchaseItem { get; set; }
        //public string SalesItem { get; set; }
        //public string InventoryItem { get; set; }
        //public object IncomeAccount { get; set; }
        //public object ExemptIncomeAccount { get; set; }
        //public object ExpanseAccount { get; set; }
        //public object Mainsupplier { get; set; }
        //public object SupplierCatalogNo { get; set; }
        //public double DesiredInventory { get; set; }
        //public double MinInventory { get; set; }
        //public object Picture { get; set; }
        public object User_Text { get; set; }
        //public object SerialNum { get; set; }
        //public double CommissionPercent { get; set; }
        //public double CommissionSum { get; set; }
        //public int CommissionGroup { get; set; }
        //public string TreeType { get; set; }
        //public string AssetItem { get; set; }
        //public object DataExportCode { get; set; }
        //public int Manufacturer { get; set; }
        //public double QuantityOnStock { get; set; }
        //public double QuantityOrderedFromVendors { get; set; }
        //public double QuantityOrderedByCustomers { get; set; }
        //public string ManageSerialNumbers { get; set; }
        //public string ManageBatchNumbers { get; set; }
        //public string Valid { get; set; }
        //public object ValidFrom { get; set; }
        //public object ValidTo { get; set; }
        //public object ValidRemarks { get; set; }
        //public string Frozen { get; set; }
        //public object FrozenFrom { get; set; }
        //public object FrozenTo { get; set; }
        //public object FrozenRemarks { get; set; }
        //public string SalesUnit { get; set; }
        //public double SalesItemsPerUnit { get; set; }
        //public object SalesPackagingUnit { get; set; }
        //public double SalesQtyPerPackUnit { get; set; }
        public object SalesUnitLength { get; set; }
        //public object SalesLengthUnit { get; set; }
        public object SalesUnitWidth { get; set; }
        //public object SalesWidthUnit { get; set; }
        public object SalesUnitHeight { get; set; }
        //public object SalesHeightUnit { get; set; }
        //public double SalesUnitVolume { get; set; }
        //public int SalesVolumeUnit { get; set; }
        public object SalesUnitWeight { get; set; }
        //public object SalesWeightUnit { get; set; }
        //public string PurchaseUnit { get; set; }
        //public double PurchaseItemsPerUnit { get; set; }
        //public object PurchasePackagingUnit { get; set; }
        //public double PurchaseQtyPerPackUnit { get; set; }
        //public double PurchaseUnitLength { get; set; }
        //public object PurchaseLengthUnit { get; set; }
        //public double PurchaseUnitWidth { get; set; }
        //public object PurchaseWidthUnit { get; set; }
        //public double PurchaseUnitHeight { get; set; }
        //public object PurchaseHeightUnit { get; set; }
        //public double PurchaseUnitVolume { get; set; }
        //public int PurchaseVolumeUnit { get; set; }
        //public double PurchaseUnitWeight { get; set; }
        //public object PurchaseWeightUnit { get; set; }
        //public object PurchaseVATGroup { get; set; }
        //public double SalesFactor1 { get; set; }
        //public double SalesFactor2 { get; set; }
        //public double SalesFactor3 { get; set; }
        //public double SalesFactor4 { get; set; }
        //public double PurchaseFactor1 { get; set; }
        //public double PurchaseFactor2 { get; set; }
        //public double PurchaseFactor3 { get; set; }
        //public double PurchaseFactor4 { get; set; }
        //public double MovingAveragePrice { get; set; }
        //public object ForeignRevenuesAccount { get; set; }
        //public object ECRevenuesAccount { get; set; }
        //public object ForeignExpensesAccount { get; set; }
        //public object ECExpensesAccount { get; set; }
        //public double AvgStdPrice { get; set; }
        //public object DefaultWarehouse { get; set; }
        //public int ShipType { get; set; }
        //public string GLMethod { get; set; }
        //public string TaxType { get; set; }
        //public double MaxInventory { get; set; }
        //public string ManageStockByWarehouse { get; set; }
        //public object PurchaseHeightUnit1 { get; set; }
        //public double PurchaseUnitHeight1 { get; set; }
        //public object PurchaseLengthUnit1 { get; set; }
        //public double PurchaseUnitLength1 { get; set; }
        //public object PurchaseWeightUnit1 { get; set; }
        //public double PurchaseUnitWeight1 { get; set; }
        //public object PurchaseWidthUnit1 { get; set; }
        //public double PurchaseUnitWidth1 { get; set; }
        //public object SalesHeightUnit1 { get; set; }
        //public double SalesUnitHeight1 { get; set; }
        //public object SalesLengthUnit1 { get; set; }
        //public double SalesUnitLength1 { get; set; }
        //public object SalesWeightUnit1 { get; set; }
        //public double SalesUnitWeight1 { get; set; }
        //public object SalesWidthUnit1 { get; set; }
        //public double SalesUnitWidth1 { get; set; }
        //public string ForceSelectionOfSerialNumber { get; set; }
        //public string ManageSerialNumbersOnReleaseOnly { get; set; }
        //public string WTLiable { get; set; }
        //public string CostAccountingMethod { get; set; }
        //public object SWW { get; set; }
        //public object WarrantyTemplate { get; set; }
        //public string IndirectTax { get; set; }
        //public object ArTaxCode { get; set; }
        //public object ApTaxCode { get; set; }
        //public object BaseUnitName { get; set; }
        //public object ItemCountryOrg { get; set; }
        //public string IssueMethod { get; set; }
        //public string SRIAndBatchManageMethod { get; set; }
        //public string IsPhantom { get; set; }
        //public string InventoryUOM { get; set; }
        //public string PlanningSystem { get; set; }
        //public string ProcurementMethod { get; set; }
        //public string ComponentWarehouse { get; set; }
        //public object OrderIntervals { get; set; }
        //public double OrderMultiple { get; set; }
        //public object LeadTime { get; set; }
        //public double MinOrderQuantity { get; set; }
        //public string ItemType { get; set; }
        //public string ItemClass { get; set; }
        //public int OutgoingServiceCode { get; set; }
        //public int IncomingServiceCode { get; set; }
        //public int ServiceGroup { get; set; }
        //public int NCMCode { get; set; }
        //public string MaterialType { get; set; }
        //public int MaterialGroup { get; set; }
        //public string ProductSource { get; set; }
        //public string Properties1 { get; set; }
        //public string Properties2 { get; set; }
        //public string Properties3 { get; set; }
        //public string Properties4 { get; set; }
        //public string Properties5 { get; set; }
        //public string Properties6 { get; set; }
        //public string Properties7 { get; set; }
        //public string Properties8 { get; set; }
        //public string Properties9 { get; set; }
        //public string Properties10 { get; set; }
        //public string Properties11 { get; set; }
        //public string Properties12 { get; set; }
        //public string Properties13 { get; set; }
        //public string Properties14 { get; set; }
        //public string Properties15 { get; set; }
        //public string Properties16 { get; set; }
        //public string Properties17 { get; set; }
        //public string Properties18 { get; set; }
        //public string Properties19 { get; set; }
        //public string Properties20 { get; set; }
        //public string Properties21 { get; set; }
        //public string Properties22 { get; set; }
        //public string Properties23 { get; set; }
        //public string Properties24 { get; set; }
        //public string Properties25 { get; set; }
        //public string Properties26 { get; set; }
        //public string Properties27 { get; set; }
        //public string Properties28 { get; set; }
        //public string Properties29 { get; set; }
        //public string Properties30 { get; set; }
        //public string Properties31 { get; set; }
        //public string Properties32 { get; set; }
        //public string Properties33 { get; set; }
        //public string Properties34 { get; set; }
        //public string Properties35 { get; set; }
        //public string Properties36 { get; set; }
        //public string Properties37 { get; set; }
        //public string Properties38 { get; set; }
        //public string Properties39 { get; set; }
        //public string Properties40 { get; set; }
        //public string Properties41 { get; set; }
        //public string Properties42 { get; set; }
        //public string Properties43 { get; set; }
        //public string Properties44 { get; set; }
        //public string Properties45 { get; set; }
        //public string Properties46 { get; set; }
        //public string Properties47 { get; set; }
        //public string Properties48 { get; set; }
        //public string Properties49 { get; set; }
        //public string Properties50 { get; set; }
        //public string Properties51 { get; set; }
        //public string Properties52 { get; set; }
        //public string Properties53 { get; set; }
        //public string Properties54 { get; set; }
        //public string Properties55 { get; set; }
        //public string Properties56 { get; set; }
        //public string Properties57 { get; set; }
        //public string Properties58 { get; set; }
        //public string Properties59 { get; set; }
        //public string Properties60 { get; set; }
        //public string Properties61 { get; set; }
        //public string Properties62 { get; set; }
        //public string Properties63 { get; set; }
        //public string Properties64 { get; set; }
        //public string AutoCreateSerialNumbersOnRelease { get; set; }
        //public int DNFEntry { get; set; }
        //public object GTSItemSpec { get; set; }
        //public object GTSItemTaxCategory { get; set; }
        //public int FuelID { get; set; }
        //public object BeverageTableCode { get; set; }
        //public object BeverageGroupCode { get; set; }
        //public int BeverageCommercialBrandCode { get; set; }
        //public int Series { get; set; }
        //public object ToleranceDays { get; set; }
        //public string TypeOfAdvancedRules { get; set; }
        //public string IssuePrimarilyBy { get; set; }
        //public string NoDiscounts { get; set; }
        //public string AssetClass { get; set; }
        //public string AssetGroup { get; set; }
        //public string InventoryNumber { get; set; }
        //public object Technician { get; set; }
        //public object Employee { get; set; }
        //public object Location { get; set; }
        //public string AssetStatus { get; set; }
        //public object CapitalizationDate { get; set; }
        //public string StatisticalAsset { get; set; }
        //public string Cession { get; set; }
        //public string DeactivateAfterUsefulLife { get; set; }
        //public string ManageByQuantity { get; set; }
        //public int UoMGroupEntry { get; set; }
        //public int InventoryUoMEntry { get; set; }
        //public int DefaultSalesUoMEntry { get; set; }
        //public int DefaultPurchasingUoMEntry { get; set; }
        //public object DepreciationGroup { get; set; }
        //public string AssetSerialNumber { get; set; }
        //public double InventoryWeight { get; set; }
        //public object InventoryWeightUnit { get; set; }
        //public double InventoryWeight1 { get; set; }
        //public object InventoryWeightUnit1 { get; set; }
        //public object DefaultCountingUnit { get; set; }
        //public double CountingItemsPerUnit { get; set; }
        //public object DefaultCountingUoMEntry { get; set; }
        //public string Excisable { get; set; }
        //public int ChapterID { get; set; }
        //public object ScsCode { get; set; }
        //public object SpProdType { get; set; }
        //public double ProdStdCost { get; set; }
        //public string InCostRollup { get; set; }
        //public string VirtualAssetItem { get; set; }
        //public string EnforceAssetSerialNumbers { get; set; }
        //public object AttachmentEntry { get; set; }
        //public object LinkedResource { get; set; }
        //public string UpdateDate { get; set; }
        //public string UpdateTime { get; set; }
        //public string GSTRelevnt { get; set; }
        //public int SACEntry { get; set; }
        //public object GSTTaxCategory { get; set; }
        //public int ServiceCategoryEntry { get; set; }
        //public object CapitalGoodsOnHoldPercent { get; set; }
        //public object CapitalGoodsOnHoldLimit { get; set; }
        //public double AssessableValue { get; set; }
        //public double AssVal4WTR { get; set; }
        //public string SOIExcisable { get; set; }
        //public object TNVED { get; set; }
        //public string ImportedItem { get; set; }
        //public int PricingUnit { get; set; }
        //public string CreateDate { get; set; }
        //public string CreateTime { get; set; }
        public object U_B1SYS_IPIStamp { get; set; }
        public object U_B1SYS_ItmClssC { get; set; }
        public object U_B1SYS_FedServC { get; set; }
        public object U_B1SYS_TaxUoMBS { get; set; }
        public double U_B1SYS_QtyPerTaxUoM { get; set; }
        public object U_B1SYS_TaxUoM { get; set; }
        public double U_B1SYS_IVAST { get; set; }
        public object U_B1SYS_IPIClssC { get; set; }
        public object U_B1SYS_SPEDItSerCod { get; set; }
        public double U_B1SYS_SPEDICMSRate { get; set; }
        public object U_B1SYS_SPEDTipi { get; set; }
        public object U_nfe_clEnq { get; set; }
        public object U_AGL_SF_COD_ENQ { get; set; }
        public object U_nfe_cSelo { get; set; }
        public string U_AGL_SF_TP_PROD { get; set; }
        public object U_AGL_CodSerF { get; set; }
        public double U_AGL_ALIQ_ICMS { get; set; }
        public object U_AGL_NBS { get; set; }
        public object U_NFE_CEST { get; set; }
        public object U_AGL_RF_TPSERV { get; set; }
        public object U_nfe_indEscala { get; set; }
        public object U_nfe_CNPJFab { get; set; }
        public object U_nfe_cProdANVISA { get; set; }
        public object U_AGL_IND_U_BEM_IMO { get; set; }
        public string U_AGL_DESCJUD_NFSCTE { get; set; }
        public string U_CVA_IdCategoria { get; set; }
        public object U_CVA_IdGrupo { get; set; }
        public object U_CVA_IdSubgrupo { get; set; }
        public object U_CVA_IdCor { get; set; }
        public object U_CVA_IdTamanho { get; set; }
        public int U_CVA_IdReferencia { get; set; }
        public object U_CVA_IdGrade { get; set; }
        public string U_CVA_Grade { get; set; }
        public object U_AGL_RF_COD_CPRB { get; set; }
        public object U_nfe_MotIsencao { get; set; }
        public object U_CVA_Product_id { get; set; }
        public object U_CVA_ImprCodBar { get; set; }
        public string U_CVA_Integrated { get; set; }
        public object U_CVA_ShortDescription { get; set; }
        public object U_CVA_Url { get; set; }
        public int U_CVA_Visibility { get; set; }
        public string U_CVA_Active { get; set; }
        public List<ItemPrice> ItemPrices { get; set; }
        //public List<ItemWarehouseInfoCollection> ItemWarehouseInfoCollection { get; set; }
        //public List<object> ItemPreferredVendors { get; set; }
        //public List<object> ItemLocalizationInfos { get; set; }
        //public List<object> ItemProjects { get; set; }
        //public List<object> ItemDistributionRules { get; set; }
        //public List<object> ItemAttributeGroups { get; set; }
        //public List<object> ItemDepreciationParameters { get; set; }
        //public List<object> ItemPeriodControls { get; set; }
        //public List<ItemUnitOfMeasurementCollection> ItemUnitOfMeasurementCollection { get; set; }
        //public List<ItemBarCodeCollection> ItemBarCodeCollection { get; set; }
        //public ItemIntrastatExtension ItemIntrastatExtension { get; set; }
    }
}
