//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.View.Hybel.DAO.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.View.Hybel.DAO.Resources.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT
        ///	CASE WHEN ISNULL(U_CVA_Email, &apos;N&apos;) &lt;&gt; &apos;E&apos; 
        ///		THEN &apos;Y&apos;
        ///		ELSE &apos;N&apos;					
        ///	END					[Enviar],
        ///	OBOE.BoeNum			[Boleto],
        ///	OBOE.PmntDate		[Lançamento],
        ///	OBOE.DueDate		[Vencimento],
        ///	OBOE.CardCode		[Cód. Cliente],
        ///	OBOE.CardName		[Nome],
        ///	OCRD.E_Mail			[E-mail],
        ///	OBOE.BoeSum			[Valor],
        ///	OINV.Serial			[Nr. NF],
        ///	CAST(INV6.InstlmntID AS NVARCHAR(10)) + &apos;/&apos; + CAST(PARC_COUNT.QtdeParcela AS NVARCHAR(10)) AS [Parcela],
        ///	CASE ISNULL(U_CVA_Email, &apos;N&apos;)
        ///		WHEN &apos;N&apos; THEN &apos;Não Enviado&apos;
        ///		WHEN &apos;P&apos; THEN &apos;P [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Boleto_Get {
            get {
                return ResourceManager.GetString("Boleto_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT
        ///	OBOE.BoeNum			[Boleto],
        ///	OBOE.DueDate		[Vencimento],
        ///	OBOE.CardCode		[Cód. Cliente],
        ///	OBOE.CardName		[Nome],
        ///	OBOE.BoeSum			[Valor],
        ///	OINV.Serial			[Nr. NF],
        ///	CAST(INV6.InstlmntID AS NVARCHAR(10)) + &apos;/&apos; + CAST(PARC_COUNT.QtdeParcela AS NVARCHAR(10)) AS [Parcela],
        ///	CASE ISNULL(U_CVA_Email, &apos;N&apos;)
        ///		WHEN &apos;N&apos; THEN &apos;Não Enviado&apos;
        ///		WHEN &apos;P&apos; THEN &apos;Pendente de Envio&apos;
        ///		WHEN &apos;E&apos; THEN &apos;Enviado&apos;
        ///		WHEN &apos;R&apos; THEN &apos;Erro no Envio&apos;
        ///	END [Status],
        ///	U_CVA_Data_Email	[Último Envio],
        ///	U_CVA_Erro_Email	[Er [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Boleto_GetLog {
            get {
                return ResourceManager.GetString("Boleto_GetLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE OBOE SET U_CVA_Email = &apos;R&apos;, U_CVA_Erro_Email = &apos;{1}&apos;
        ///WHERE OBOE.BoeNum IN ({0}).
        /// </summary>
        internal static string Boleto_UpdateErro {
            get {
                return ResourceManager.GetString("Boleto_UpdateErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE OBOE SET U_CVA_Email = &apos;E&apos;, U_CVA_Data_Email = CAST(GETDATE() AS DATE), U_CVA_Erro_Email = &apos;&apos;
        ///WHERE OBOE.BoeNum IN ({0}).
        /// </summary>
        internal static string Boleto_UpdateOK {
            get {
                return ResourceManager.GetString("Boleto_UpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE OBOE SET U_CVA_Email = &apos;P&apos;, U_CVA_Erro_Email = &apos;&apos;
        ///WHERE OBOE.BoeNum IN ({0}).
        /// </summary>
        internal static string Boleto_UpdatePendente {
            get {
                return ResourceManager.GetString("Boleto_UpdatePendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT T0.AlcName, T0.AlcCode, T0.LaCAllcAcc, T0.U_CVA_CodItem, T0.U_CVA_TipoDespesa FROM OALC T0.
        /// </summary>
        internal static string BuscarDespesasImportacao {
            get {
                return ResourceManager.GetString("BuscarDespesasImportacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT CRD7.CardCode FROM OBPL
        ///	INNER JOIN CRD7
        ///		ON CRD7.TaxId0 = OBPL.TaxIdNum
        ///WHERE OBPL.BPLId = {0}.
        /// </summary>
        internal static string Cliente_GetByFilial {
            get {
                return ResourceManager.GetString("Cliente_GetByFilial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///	U_Concorrente	[Cód. Concorrente],
        ///	Code			[Concorrente]
        ///FROM [@CVA_CONC_ITEM] T0.
        /// </summary>
        internal static string CodConcorrente_Get {
            get {
                return ResourceManager.GetString("CodConcorrente_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT COUNT(*) FROM [@CVA_CONC_ITEM]
        ///WHERE U_Concorrente = &apos;{0}&apos;.
        /// </summary>
        internal static string Concorrente_GetCount {
            get {
                return ResourceManager.GetString("Concorrente_GetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT U_ItemCode FROM [@CVA_CONC_ITEM]
        ///WHERE U_Concorrente = &apos;{0}&apos;.
        /// </summary>
        internal static string Concorrente_GetItemCode {
            get {
                return ResourceManager.GetString("Concorrente_GetItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Name, Memo FROM OCMT.
        /// </summary>
        internal static string Concorrente_GetList {
            get {
                return ResourceManager.GetString("Concorrente_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///	U_Servidor Servidor,
        ///	U_Porta		Porta,
        ///	U_Email		Email,
        ///	U_Senha		Senha,
        ///	U_SSL		[SSL],
        ///	U_Assunto	[Assunto]
        ///FROM [@CVA_CONFIG_EMAIL].
        /// </summary>
        internal static string ConfiguracaoEmail_Get {
            get {
                return ResourceManager.GetString("ConfiguracaoEmail_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXEC SP_CVA_DCIP_ENERGIA {0}, &apos;{1}&apos;, &apos;{2}&apos;.
        /// </summary>
        internal static string Dcip_GetEnergiaEletrica {
            get {
                return ResourceManager.GetString("Dcip_GetEnergiaEletrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXEC SP_CVA_DCIP_SIMPLES {0}, &apos;{1}&apos;, &apos;{2}&apos;.
        /// </summary>
        internal static string Dcip_GetSimplesNacional {
            get {
                return ResourceManager.GetString("Dcip_GetSimplesNacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DECLARE @Engenharia AS NVARCHAR(MAX)
        ///SET @Engenharia = $[$38.U_CVA_Engenharia]
        ///SET @Engenharia = RTRIM(@Engenharia)
        ///SET @Engenharia = LTRIM(@Engenharia)
        ///SELECT U_H_Codigo_Engenharia, ItemCode, ItemName FROM OITM WHERE U_H_Codigo_Engenharia LIKE @Engenharia.
        /// </summary>
        internal static string Engenharia_Get {
            get {
                return ResourceManager.GetString("Engenharia_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DECLARE @Engenharia AS NVARCHAR(MAX)
        ///SET @Engenharia = &apos;{0}&apos;
        ///SET @Engenharia = RTRIM(@Engenharia)
        ///SET @Engenharia = LTRIM(@Engenharia)
        ///SELECT 
        ///	U_H_Codigo_Engenharia	[Cód. Engenharia], 
        ///	ItemCode				[Cód. Item],
        ///	ItemName				[Descrição]
        ///FROM OITM 
        ///WHERE U_H_Codigo_Engenharia LIKE &apos;%&apos;+ @Engenharia + &apos;%&apos;.
        /// </summary>
        internal static string Engenharia_GetOld {
            get {
                return ResourceManager.GetString("Engenharia_GetOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT BPLId, BPLName FROM OBPL.
        /// </summary>
        internal static string Filial_Get {
            get {
                return ResourceManager.GetString("Filial_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT
        ///	STC1.STCCode	CodigoImposto,
        ///	OSTT.Name		TipoImposto, 
        ///	STA1.Rate		Taxa,
        ///	STA1.U_Base	* ISNULL(NULLIF(STA1.U_taxAliq, 0), 1)	BaseCalculo
        ///FROM STC1 WITH(NOLOCK)
        ///	INNER JOIN OSTT WITH(NOLOCK)
        ///		ON OSTT.AbsId = STC1.STAType
        ///	INNER JOIN OSTA WITH(NOLOCK)
        ///		ON OSTA.Code = STC1.STACode
        ///		AND OSTA.Type = STC1.STAType
        ///	INNER JOIN STA1 WITH(NOLOCK)
        ///		ON STA1.StaCode = OSTA.Code
        ///		AND STA1.SttType = OSTA.[Type]
        ///WHERE STC1.STCCode IN ({0}).
        /// </summary>
        internal static string Imposto_GetTaxas {
            get {
                return ResourceManager.GetString("Imposto_GetTaxas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DISTINCT
        ///	OITM.ItemCode				[Cód. Item],
        ///	OITM.ItemName				[Descrição],
        ///	OITM.U_H_Codigo_Engenharia	[Cód. Engenharia],
        ///                   CAST(CONC.U_Obs AS NVARCHAR(MAX)) [Observação],
        ///	OITW.OnHand - OITW.IsCommited + OITW.OnOrder	[Qtde],
        ///	OITW.WhsCode				[Depósito]
        ///
        ///FROM OITM WITH(NOLOCK)
        ///	LEFT JOIN [@CVA_MONT_ITEM] MONT WITH(NOLOCK)
        ///		ON MONT.U_ItemCode = OITM.ItemCode
        ///	LEFT JOIN [@CVA_CONC_ITEM] CONC WITH(NOLOCK)
        ///		ON CONC.U_ItemCode = OITM.ItemCode
        ///	LEFT JOIN OBPL WITH(NOLOCK)
        ///		ON  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Item_Get {
            get {
                return ResourceManager.GetString("Item_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///	U_ItemCode		[Cód. Item],
        ///	U_ItemName		[Descrição],
        ///	U_Concorrente	[Concorrente],
        ///	U_Obs			[Observações]
        ///FROM [@CVA_CONC_ITEM] ITEM
        ///	INNER JOIN [@CVA_CONCORRENTE] CONC
        ///		ON CONC.Code = ITEM.Code
        ///WHERE U_Concorrente = &apos;{0}&apos;.
        /// </summary>
        internal static string Item_GetByConcorrente {
            get {
                return ResourceManager.GetString("Item_GetByConcorrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT ItemCode FROM OITM WHERE U_H_Codigo_Engenharia = &apos;{0}&apos;.
        /// </summary>
        internal static string Item_GetByEngenharia {
            get {
                return ResourceManager.GetString("Item_GetByEngenharia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Code, Name FROM [@CVA_MOTIVO_CANC].
        /// </summary>
        internal static string MotivoCancelamento_Get {
            get {
                return ResourceManager.GetString("MotivoCancelamento_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT OPCH.Serial, OPCH.DocTotal - ISNULL(SUM(PCH4.TaxSum), 0) Total, OPCH.DocTotal, ISNULL(SUM(PCH4.TaxSum), 0) Total_Imposto FROM OPCH WITH(NOLOCK)
        ///	LEFT JOIN PCH4 WITH(NOLOCK)
        ///		ON PCH4.DocEntry = OPCH.DocEntry
        ///		AND PCH4.TaxInPrice = &apos;Y&apos;
        ///WHERE DocNum = {0}
        ///GROUP BY OPCH.Serial, OPCH.DocTotal.
        /// </summary>
        internal static string NotaEntrada_DespesasImportacao {
            get {
                return ResourceManager.GetString("NotaEntrada_DespesasImportacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DocEntry FROM OPCH WITH(NOLOCK) WHERE DocNum = {0}.
        /// </summary>
        internal static string NotaEntrada_GetByDocNum {
            get {
                return ResourceManager.GetString("NotaEntrada_GetByDocNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT OPCH.Serial, OPCH.DocTotal - ISNULL(SUM(PCH4.TaxSum), 0) Total,
        ///OPCH.DocTotal,
        ///ISNULL(SUM(PCH4.TaxSum), 0) Total_Imposto,
        ///PCH4.TaxSum,
        ///PCH4.staType,
        ///PCH4.StcCode,
        ///OSTT.Name
        ///FROM OPCH WITH(NOLOCK)
        ///	LEFT JOIN PCH4 WITH(NOLOCK)
        ///		ON PCH4.DocEntry = OPCH.DocEntry
        ///		AND PCH4.TaxInPrice = &apos;Y&apos;
        ///	
        ///	INNER JOIN OSTT WITH(NOLOCK)
        ///		ON OSTT.AbsId = PCH4.staType
        ///
        ///WHERE DocNum = {0}
        ///GROUP BY PCH4.TaxSum, OPCH.Serial, OPCH.DocTotal,PCH4.staType,PCH4.StcCode,OSTT.Name.
        /// </summary>
        internal static string NotaFiscaEntradalBuscarImpostos {
            get {
                return ResourceManager.GetString("NotaFiscaEntradalBuscarImpostos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT CARDCODE FROM OCRD WHERE CARDNAME = &apos;{0}&apos;.
        /// </summary>
        internal static string Parceiro_GetCardCode {
            get {
                return ResourceManager.GetString("Parceiro_GetCardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DECLARE @cardcode NVARCHAR(30), @dias INT, @retorno VARCHAR(10)
        ///
        ///SELECT @cardcode = &apos;{0}&apos;
        ///SET @retorno = &apos;FALSE&apos;
        ///
        ///IF EXISTS(SELECT TOP 1 1 FROM OCRD WITH(NOLOCK) WHERE CardCode = @cardcode AND ISNULL(CAST(Free_Text AS NVARCHAR(MAX)), &apos;&apos;) &lt;&gt; &apos;&apos;)
        ///BEGIN	
        ///	SET @retorno = &apos;TRUE&apos;
        ///END
        ///ELSE IF NOT EXISTS(SELECT TOP 1 1 FROM OINV WITH(NOLOCK) WHERE CANCELED = &apos;N&apos; AND CardCode = @cardcode AND DocDate &gt; DATEADD(DAY, -31, GETDATE()))
        ///BEGIN
        ///	SET @retorno = &apos;TRUE&apos;
        ///END
        ///ELSE
        ///BEGIN
        ///	DECLARE invcursor CURSOR F [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Parceiro_GetStatus {
            get {
                return ResourceManager.GetString("Parceiro_GetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT RDR1.ItemCode, RDR1.Dscription ItemName, RDR1.OpenQty Quantidade FROM ORDR WITH(NOLOCK)
        ///	INNER JOIN RDR1 WITH(NOLOCK)
        ///		ON RDR1.DocEntry = ORDR.DocEntry
        ///WHERE ORDR.DocNum = {0}.
        /// </summary>
        internal static string PedidoVenda_GetItems {
            get {
                return ResourceManager.GetString("PedidoVenda_GetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DECLARE @WhsCode NVARCHAR(100)
        ///
        ///SELECT @WhsCode = DflWhs FROM OBPL WHERE BPLId = {0}
        ///
        ///EXEC SP_CVA_TRANSF_FILIAIS @WhsCode.
        /// </summary>
        internal static string PedidoVenda_GetTransferenciaFilial {
            get {
                return ResourceManager.GetString("PedidoVenda_GetTransferenciaFilial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT U_Produto FROM [@CVA_MONT_PROD]
        ///WHERE Code = $[$et_Mont.0]  OR $[$et_Mont.0] = &apos;&apos;.
        /// </summary>
        internal static string ProdutoMontadora_Get {
            get {
                return ResourceManager.GetString("ProdutoMontadora_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DECLARE @DataDe DATETIME
        ///DECLARE @DataAte DATETIME
        ///
        ///SET @DataDe = CAST(&apos;{0}&apos; AS DATETIME)
        ///SET @DataAte = CAST(&apos;{1}&apos; AS DATETIME)
        ///
        ///exec SP_CVA_TAXA_CONVERSAO_VENDA &apos;{2}&apos;, @DataDe, @DataAte, {3}.
        /// </summary>
        internal static string RelatorioTaxaConversaoVenda {
            get {
                return ResourceManager.GetString("RelatorioTaxaConversaoVenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DECLARE @DataDe DATETIME
        ///DECLARE @DataAte DATETIME
        ///
        ///SET @DataDe = CAST(&apos;{0}&apos; AS DATETIME)
        ///SET @DataAte = CAST(&apos;{1}&apos; AS DATETIME)
        ///
        ///exec SP_CVA_VENDA_CANCELADA_SUM &apos;{2}&apos;, @DataDe, @DataAte, {3}.
        /// </summary>
        internal static string RelatorioVendasCancelas {
            get {
                return ResourceManager.GetString("RelatorioVendasCancelas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT COUNT(*) FROM [@CVA_SIM_VENDA]
        ///WHERE Code = &apos;{0}&apos;.
        /// </summary>
        internal static string SimuladorVenda_GetCount {
            get {
                return ResourceManager.GetString("SimuladorVenda_GetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXEC SP_CVA_SIMULADOR_ENTRADA &apos;{0}&apos;.
        /// </summary>
        internal static string SimuladorVenda_GetEntradas {
            get {
                return ResourceManager.GetString("SimuladorVenda_GetEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXEC SP_CVA_SIMULADOR_OP &apos;{0}&apos;.
        /// </summary>
        internal static string SimuladorVenda_GetOPs {
            get {
                return ResourceManager.GetString("SimuladorVenda_GetOPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXEC SP_CVA_SIMULADOR_PEDIDO.
        /// </summary>
        internal static string SimuladorVenda_GetPedidos {
            get {
                return ResourceManager.GetString("SimuladorVenda_GetPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXEC SP_CVA_SIMULADOR_ROTEIRO {0}, &apos;{1}&apos;.
        /// </summary>
        internal static string SimuladorVenda_GetRoteiro {
            get {
                return ResourceManager.GetString("SimuladorVenda_GetRoteiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXEC SP_CVA_SIMULADOR_SAIDA &apos;{0}&apos;.
        /// </summary>
        internal static string SimuladorVenda_GetSaidas {
            get {
                return ResourceManager.GetString("SimuladorVenda_GetSaidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EXEC SP_CVA_SIMULADOR_VENDA &apos;{0}&apos;.
        /// </summary>
        internal static string SimuladorVenda_GetSimulacao {
            get {
                return ResourceManager.GetString("SimuladorVenda_GetSimulacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM [@CVA_SIM_VENDA_OP]
        ///WHERE Code = &apos;{0}&apos;
        ///
        ///INSERT INTO [@CVA_SIM_VENDA_OP]
        ///(Code, Name, U_ItemCode, U_OP, U_Fis, U_Res, U_Enc, U_Dis)
        ///VALUES(&apos;{0}&apos;, &apos;{0}&apos;, &apos;{1}&apos;, {2}, {3}, {4}, {5}, {6}).
        /// </summary>
        internal static string SimuladorVenda_SetLayout {
            get {
                return ResourceManager.GetString("SimuladorVenda_SetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT AlcCode FROM OALC WHERE AlcName = &apos;{0}&apos;.
        /// </summary>
        internal static string TipoDespesaImportacao_GetByName {
            get {
                return ResourceManager.GetString("TipoDespesaImportacao_GetByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT U_Tipo FROM [@CVA_MAQUINA]
        ///WHERE Code = $[$et_Aplic.0] OR $[$et_Aplic.0] = &apos;&apos;.
        /// </summary>
        internal static string TipoMaquina_Get {
            get {
                return ResourceManager.GetString("TipoMaquina_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT USERID FROM OUSR WHERE USER_CODE = &apos;{0}&apos;.
        /// </summary>
        internal static string User_GetId {
            get {
                return ResourceManager.GetString("User_GetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT MainUsage FROM OCRD WHERE CardCode = &apos;{0}&apos;.
        /// </summary>
        internal static string Utilizacao_GetByPN {
            get {
                return ResourceManager.GetString("Utilizacao_GetByPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Model From OPCH Where DocNum = {0}.
        /// </summary>
        internal static string VericarTipoNF {
            get {
                return ResourceManager.GetString("VericarTipoNF", resourceCulture);
            }
        }
    }
}
