IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SKA_BEAS_CONSUMIDO')
	DROP PROCEDURE SP_CVA_SKA_BEAS_CONSUMIDO
GO
CREATE PROCEDURE SP_CVA_SKA_BEAS_CONSUMIDO
AS
BEGIN
	SELECT DISTINCT
		PROD.Id	IdMes,
		PROD.OP,
		PROD.BELPOS_ID	BelPosId,
		PROD.POS_ID	PosId,
		CASE WHEN ISNULL(IGE1.DOCENTRY,0) > 0 THEN '' ELSE CAST(ERRO.Information AS NVARCHAR(MAX)) END  Erro
	FROM MES.[dbo].SSPExportProd PROD WITH(NOLOCK)
		INNER JOIN MES.[dbo].SSPExportProd_Log TLOG WITH(NOLOCK)
			ON TLOG.ID_MES = PROD.Id
			AND TLOG.[TYPE] = 1		-- Consumo
			AND TLOG.[Status] = 1	-- Arquivo gerado
		INNER JOIN BEAS_FTSTL STL WITH(NOLOCK)
			ON STL.BELNR_ID = PROD.OP
			AND STL.BELPOS_ID = PROD.BELPOS_ID
			AND STL.APLANPOS_ID = PROD.POS_ID
		LEFT JOIN IGE1 WITH(NOLOCK)
			ON IGE1.u_belnrid = STL.BELNR_ID
			AND IGE1.u_belposid = STL.BELPOS_ID
			AND IGE1.u_posid = STL.POS_ID
		OUTER APPLY
		(
			SELECT TOP 1 * FROM BEAS_PROTOKOLL ERRO WITH (NOLOCK)
			WHERE ERRO.BASE_DOCENTRY = PROD.OP
			AND ERRO.BASE_LINENUM = PROD.BELPOS_ID
			AND ERRO.BASE_DOCTYPE = 'WO'
			AND PROD.[STATUS] = 1
			AND ERRO.DATUM >= REPDATETIME
			ORDER BY NR DESC
		) ERRO
	WHERE ISNULL(IGE1.DocEntry, 0) <> 0
	OR ISNULL(CAST(ERRO.Information AS NVARCHAR(MAX)), '') <> ''

	UNION ALL

	SELECT 
		PROD.Id	IdMes,
		PROD.OP,
		PROD.BELPOS_ID	BelPosId,
		PROD.POS_ID	PosId,
		''
	FROM MES.[dbo].SSPExportProd PROD 
		INNER JOIN MES.[dbo].SSPExportProd_LOG PROD_LOG 
			ON PROD.ID = PROD_LOG.ID_MES
	WHERE  PROD_LOG.[TYPE] = 1
	AND PROD_LOG.[Status] = 5

END