IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SKA_BEAS_TEMPO')
	DROP PROCEDURE SP_CVA_SKA_BEAS_TEMPO
GO
CREATE PROCEDURE SP_CVA_SKA_BEAS_TEMPO
AS
BEGIN
	SELECT DISTINCT
		PROD.Id,
		PROD.OP,
		PROD.BELPOS_ID,
		CAST(ERRO.Information AS NVARCHAR(MAX)) Erro
	FROM MES.[dbo].SSPExportProd PROD WITH(NOLOCK)
		INNER JOIN MES.[dbo].SSPExportProd_Log TLOG WITH(NOLOCK)
			ON TLOG.ID_MES = PROD.Id
			AND TLOG.[TYPE] = 0
			AND TLOG.[Status] = 1
		INNER JOIN BEAS_ARBZEIT ZEIT WITH(NOLOCK)
			ON ZEIT.UDF1 = PROD.Id
		OUTER APPLY
		(
			SELECT TOP 1 * FROM BEAS_PROTOKOLL ERRO WITH (NOLOCK)
			WHERE ERRO.BASE_DOCENTRY = PROD.OP
			AND ERRO.BASE_LINENUM = PROD.POS_ID
			AND ERRO.BASE_DOCTYPE = 'WO'
			AND PROD.[STATUS] = 1
			AND ERRO.DATUM >= REPDATETIME
			ORDER BY NR DESC
		) ERRO
END