IF EXISTS (SELECT * FROM sys.objects WHERE type = 'TR' AND name = 'TGR_PROD_LOG')
	DROP TRIGGER TGR_PROD_LOG
GO
CREATE TRIGGER TGR_PROD_LOG
ON [SSPExportProd]
FOR INSERT
AS
BEGIN
    DECLARE @ID_MES  INT

    SELECT @ID_MES = ID FROM INSERTED WHERE ENCERR = 1

	IF @ID_MES IS NOT NULL
	BEGIN
		INSERT INTO [SSPExportProd_Log] (ID_MES, [TYPE], [Status])
		SELECT @ID_MES, 0, 0

		INSERT INTO [SSPExportProd_Log] (ID_MES, [TYPE], [Status])
		SELECT @ID_MES, 1, 0

		INSERT INTO [SSPExportProd_Log] (ID_MES, [TYPE], [Status])
		SELECT @ID_MES, 3, 0
	END
END
GO