//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA_Rep_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVA_TIM
    {
        public int ID { get; set; }
        public System.DateTime INS { get; set; }
        public Nullable<System.DateTime> UPD { get; set; }
        public Nullable<int> STU { get; set; }
        public Nullable<int> TIM { get; set; }
        public Nullable<int> NUM_OBJ { get; set; }
    
        public virtual CVA_STU CVA_STU { get; set; }
    }
}
