//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Tust.Import.ConciliatorDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVA_REG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CVA_REG()
        {
            this.CVA_REG_LOG = new HashSet<CVA_REG_LOG>();
        }
    
        public int ID { get; set; }
        public System.DateTime INS { get; set; }
        public Nullable<System.DateTime> UPD { get; set; }
        public Nullable<int> STU { get; set; }
        public Nullable<int> BAS { get; set; }
        public string CODE { get; set; }
        public string FUNC { get; set; }
        public Nullable<int> BAS_ERR { get; set; }
    
        public virtual CVA_BASES CVA_BASES { get; set; }
        public virtual CVA_BASES CVA_BASES1 { get; set; }
        public virtual CVA_STATUS CVA_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CVA_REG_LOG> CVA_REG_LOG { get; set; }
    }
}
