//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Escoteiro.Magento.DAO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HanaCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HanaCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.Escoteiro.Magento.DAO.Resources.HanaCommands", typeof(HanaCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;LineNum&quot; from &quot;{0}&quot;.CRD1 where &quot;CardCode&quot; = &apos;{1}&apos; and &quot;Address&quot; = &apos;{2}&apos; .
        /// </summary>
        public static string Address_Get {
            get {
                return ResourceManager.GetString("Address_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with BPTaxId as
        ///(
        ///	select distinct 1 as &quot;RecOrder&quot;, OCRD.&quot;CardCode&quot;, case when length(CRD7.&quot;TaxId0&quot;) = 0 or CRD7.&quot;TaxId0&quot; is null then CRD7.&quot;TaxId4&quot; else CRD7.&quot;TaxId0&quot; end as &quot;TaxId&quot;
        ///	  from &quot;{0}&quot;.OCRD
        ///	 inner join &quot;{0}&quot;.CRD7 on CRD7.&quot;CardCode&quot; = OCRD.&quot;CardCode&quot;
        ///	 where OCRD.&quot;CardType&quot; = &apos;C&apos;
        ///	   and CRD7.&quot;AddrType&quot; = &apos;S&apos;
        ///                      
        ///	   and (replace(replace(replace(CRD7.&quot;TaxId0&quot;, &apos;.&apos;, &apos;&apos;), &apos;-&apos;, &apos;&apos;), &apos;/&apos;, &apos;&apos;) = replace(replace(replace(&apos;{1}&apos;, &apos;.&apos;, &apos;&apos;), &apos;-&apos;, &apos;&apos;), &apos;/&apos;, &apos;&apos;) 
        ///		or replace(repl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BP_Get {
            get {
                return ResourceManager.GetString("BP_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ORDR.&quot;DocEntry&quot;, ORDR.&quot;U_CVA_EntityId&quot;
        ///  from &quot;{0}&quot;.&quot;ORDR&quot;
        /// where ORDR.&quot;U_CVA_EntityId&quot; is not null
        ///   and ORDR.&quot;CANCELED&quot; = &apos;Y&apos;
        ///   and ORDR.&quot;U_CVA_IntegratedCancellation&quot; = &apos;N&apos;.
        /// </summary>
        public static string CancelledOrders_Get {
            get {
                return ResourceManager.GetString("CancelledOrders_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select OCRD.&quot;CardCode&quot; 
        ///      from &quot;{0}&quot;.OCRD 
        ///     inner join &quot;{0}&quot;.OCRG on OCRG.&quot;GroupCode&quot; = OCRD.&quot;GroupCode&quot;
        ///     where OCRD.&quot;CardFName&quot; like &apos;%{1}%&apos; 
        ///       and OCRD.&quot;CardType&quot; = &apos;S&apos;
        ///       and OCRG.&quot;GroupName&quot; = &apos;TRANS - PJ NACIONAL&apos;.
        /// </summary>
        public static string Carrier_Get {
            get {
                return ResourceManager.GetString("Carrier_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select OCNT.&quot;AbsId&quot; 
        ///  from &quot;{0}&quot;.OCNT 
        /// where replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(upper(OCNT.&quot;Name&quot;), &apos;Á&apos;, &apos;A&apos;), &apos;Â&apos;, &apos;A&apos;), &apos;Ã&apos;, &apos;A&apos;), &apos;É&apos;, &apos;E&apos;), &apos;Ê&apos;, &apos;E&apos;), &apos;Í&apos;, &apos;I&apos;), &apos;Ó&apos;, &apos;O&apos;), &apos;Ô&apos;, &apos;O&apos;), &apos;Ú&apos;, &apos;U&apos;), &apos;Ç&apos;, &apos;C&apos;), &apos;&apos;&apos;&apos;, &apos;&apos;) = 
        /// 	   replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(upper(&apos;{1}&apos;), &apos;Á&apos;, &apos;A&apos;), &apos;Â&apos;, &apos;A&apos;), &apos;Ã&apos;, &apos;A&apos;), &apos;É&apos;, &apos;E&apos;), &apos;Ê&apos;, &apos;E&apos;), &apos;Í&apos;, &apos;I&apos;), &apos;Ó&apos;, &apos;O&apos;), &apos;Ô&apos;, &apos;O&apos;), &apos;Ú&apos;, &apos;U&apos;), &apos;Ç&apos;, &apos;C&apos;) 	
        ///   and OCNT.&quot;State&quot;  [rest of string was truncate....
        /// </summary>
        public static string CountyAbsId_Get {
            get {
                return ResourceManager.GetString("CountyAbsId_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;CreditCard&quot; FROM &quot;{0}&quot;.OCRC WHERE UPPER(&quot;CardName&quot;) like &apos;{1}%&apos;.
        /// </summary>
        public static string CreditCard_Get {
            get {
                return ResourceManager.GetString("CreditCard_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;CrTypeCode&quot; from &quot;{0}&quot;.OCRP where &quot;CrTypeName&quot; = &apos;{1}&apos;.
        /// </summary>
        public static string CreditCardTypeCode_Get {
            get {
                return ResourceManager.GetString("CreditCardTypeCode_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select coalesce(&quot;Price&quot;, 0.0) as &quot;Price&quot; from &quot;{0}&quot;.ITM1 where &quot;ItemCode&quot; = &apos;{1}&apos; and &quot;PriceList&quot; = 3.
        /// </summary>
        public static string DistribuidorPriceList_Get {
            get {
                return ResourceManager.GetString("DistribuidorPriceList_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;DocEntry&quot; from &quot;{0}&quot;.ODPI where &quot;U_CVA_EntityId&quot; = {1} and not exists (select * from &quot;{0}&quot;.DPI1 where DPI1.&quot;DocEntry&quot; = ODPI.&quot;DocEntry&quot; and DPI1.&quot;TargetType&quot; = 14).
        /// </summary>
        public static string DownPayment_Get {
            get {
                return ResourceManager.GetString("DownPayment_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;DocEntry&quot; from &quot;{0}&quot;.&quot;ORCT&quot; WHERE &quot;U_CVA_EntityId&quot; = {1} AND &quot;Canceled&quot; = &apos;N&apos;.
        /// </summary>
        public static string IncomingPayments_Get {
            get {
                return ResourceManager.GetString("IncomingPayments_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT JDT1.&quot;TransId&quot;, JDT1.&quot;Line_ID&quot;, OCRH.&quot;VoucherNum&quot; &quot;AdditionalReference&quot;
        ///FROM &quot;{0}&quot;.ORCT
        ///	INNER JOIN &quot;{0}&quot;.OCRH ON OCRH.&quot;RctAbs&quot; = ORCT.&quot;DocEntry&quot;
        ///	INNER JOIN &quot;{0}&quot;.JDT1 ON JDT1.&quot;TransId&quot; = ORCT.&quot;TransId&quot; 
        ///	AND SUBSTR_AFTER(REPLACE(JDT1.&quot;Ref3Line&quot;, &apos;\&apos;, &apos;/&apos;), &apos;/&apos;) = SUBSTR_AFTER(REPLACE(OCRH.&quot;VoucherNum&quot;, &apos;\&apos;, &apos;/&apos;) , &apos;/&apos;)
        ///WHERE ORCT.&quot;DocEntry&quot; = {1}
        ///AND SUBSTR_BEFORE(REPLACE(JDT1.&quot;Ref3Line&quot;, &apos;\&apos;, &apos;/&apos;), &apos;/&apos;) &lt;&gt; SUBSTR_BEFORE(REPLACE(OCRH.&quot;VoucherNum&quot;, &apos;\&apos;, &apos;/&apos;) , &apos;/&apos;)
        ///ORDER BY JDT1.&quot;Line_ID&quot;.
        /// </summary>
        public static string IncomingPayments_GetJournalToFix {
            get {
                return ResourceManager.GetString("IncomingPayments_GetJournalToFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;ItemCode&quot; FROM &quot;{0}&quot;.&quot;OITM&quot; WHERE &quot;CodeBars&quot; = &apos;{1}&apos;.
        /// </summary>
        public static string Item_Get {
            get {
                return ResourceManager.GetString("Item_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;ManBtchNum&quot; FROM &quot;{0}&quot;.&quot;OITM&quot; WHERE &quot;ItemCode&quot; = &apos;{1}&apos;.
        /// </summary>
        public static string ItemManageBatchNum_Get {
            get {
                return ResourceManager.GetString("ItemManageBatchNum_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Obtém os itens que ainda não estão na tabela @CVA_STOCK_MAGENTO
        ///select distinct OBCD.&quot;BcdCode&quot;, OITW.&quot;ItemCode&quot;, OITM.&quot;ItemName&quot;, 
        ///	   OITW.&quot;OnHand&quot;  - coalesce((select sum(RDR1.&quot;Quantity&quot;)
        ///			   					  from &quot;{0}&quot;.ORDR
        ///			   					 inner join &quot;{0}&quot;.RDR1 on RDR1.&quot;DocEntry&quot; = ORDR.&quot;DocEntry&quot;
        ///			   					   and RDR1.&quot;ItemCode&quot; = OITM.&quot;ItemCode&quot; 
        ///			   					   and RDR1.&quot;LineStatus&quot; = &apos;O&apos;
        ///			   					 where ORDR.&quot;U_OrigemPedido&quot; in (&apos;2&apos;, &apos;3&apos;)
        ///			   					   and ORDR.&quot;CANCELED&quot; = &apos;N&apos;), 0) as &quot;WhsQty&quot;
        ///  fr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ItemStockQuantity_Get {
            get {
                return ResourceManager.GetString("ItemStockQuantity_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;Code&quot;
        ///  from &quot;{0}&quot;.&quot;@CVA_STOCK_MAGENTO&quot; as &quot;STOCK&quot;
        /// where &quot;STOCK&quot;.&quot;U_BarCode&quot; = &apos;{1}&apos;
        ///   and &quot;STOCK&quot;.&quot;U_ItemCode&quot; = &apos;{2}&apos;.
        /// </summary>
        public static string ItemStockQuantity_GetCode {
            get {
                return ResourceManager.GetString("ItemStockQuantity_GetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select coalesce(max(cast(&quot;Code&quot; as int)), 0) + 1 from &quot;{0}&quot;.&quot;@CVA_STOCK_MAGENTO&quot;.
        /// </summary>
        public static string ItemStockQuantity_GetNextCode {
            get {
                return ResourceManager.GetString("ItemStockQuantity_GetNextCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select OITM.&quot;ItemCode&quot;
        ///  from &quot;{0}&quot;.OITM
        /// where OITM.&quot;InvntItem&quot; = &apos;Y&apos;
        ///   and OITM.&quot;SellItem&quot; = &apos;Y&apos;
        ///   and (OITM.&quot;U_CVA_Integrated&quot; = &apos;N&apos; or OITM.&quot;U_CVA_Integrated&quot; is null)
        ///   and OITM.&quot;CodeBars&quot; is not null.
        /// </summary>
        public static string ItemsToIntegrate_Get {
            get {
                return ResourceManager.GetString("ItemsToIntegrate_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;Code&quot; from &quot;{0}&quot;.&quot;@CVA_MAGENTO_DT&quot; Where &quot;U_EndPoint&quot; = &apos;{1}&apos;.
        /// </summary>
        public static string LastDate_GetCode {
            get {
                return ResourceManager.GetString("LastDate_GetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;DocEntry&quot; from &quot;{0}&quot;.&quot;ORDR&quot; WHERE &quot;U_CVA_EntityId&quot; = {1} AND &quot;CANCELED&quot; = &apos;N&apos;.
        /// </summary>
        public static string Orders_Get {
            get {
                return ResourceManager.GetString("Orders_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &quot;{0}&quot;.&quot;@CVA_ORDERS_MAGENTO_S&quot;.NEXTVAL from dummy.
        /// </summary>
        public static string OrdersNextVal_Set {
            get {
                return ResourceManager.GetString("OrdersNextVal_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ORDERS.&quot;Code&quot;, ORDERS.&quot;U_EntityId&quot;, ORDERS.&quot;U_Mensagem&quot;, ORDERS.&quot;U_Status&quot;
        ///  from &quot;{0}&quot;.&quot;@CVA_ORDERS_MAGENTO&quot; as ORDERS
        /// where ORDERS.&quot;U_IntegrateStatus&quot; = &apos;Y&apos;
        ///   and ORDERS.&quot;U_EntityId&quot; is not null;.
        /// </summary>
        public static string OrderStatusMessages_Get {
            get {
                return ResourceManager.GetString("OrderStatusMessages_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;{0}&quot;.&quot;@CVA_ORDERS_MAGENTO&quot; (&quot;Code&quot;, &quot;Name&quot;, &quot;U_EntityId&quot;, &quot;U_State&quot;, &quot;U_Status&quot;, &quot;U_Data&quot;, 
        ///  								   &quot;U_Hora&quot;, &quot;U_JSON&quot;, &quot;U_StatusProc&quot;, &quot;U_Mensagem&quot;, &quot;U_DataProc&quot;, 
        ///  								   &quot;U_HoraProc&quot;, &quot;U_DocEntry&quot;, &quot;U_ObjType&quot;, &quot;U_IntegrateStatus&quot;)
        ///select (select max(coalesce(&quot;Code&quot;, 0)) + 1 from &quot;@CVA_ORDERS_MAGENTO&quot;), &apos;Orders&apos;, 
        ///	   OINV.&quot;U_CVA_EntityId&quot;, &apos;complete&apos;, &apos;transportadora&apos;, current_date, cast(replace(current_time, &apos;:&apos;, &apos;&apos;) as varchar(4)), null, &apos;OK&apos;, 
        ///	   &apos;Os produtos do pedido fo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderStatusMessages_SetShipped {
            get {
                return ResourceManager.GetString("OrderStatusMessages_SetShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 10 distinct ORDERS.&quot;U_EntityId&quot;
        ///  from &quot;{0}&quot;.&quot;@CVA_ORDERS_MAGENTO&quot; as ORDERS
        /// where ORDERS.&quot;U_StatusProc&quot; like &apos;NOK&apos;
        ///   and not exists (select *
        ///					 from &quot;{0}&quot;.&quot;@CVA_ORDERS_MAGENTO&quot; as A0
        ///					where A0.&quot;U_StatusProc&quot; like &apos;OK&apos;
        ///					  and A0.&quot;U_EntityId&quot; = ORDERS.&quot;U_EntityId&quot;).
        /// </summary>
        public static string PedingOrders_Get {
            get {
                return ResourceManager.GetString("PedingOrders_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;TrnspCode&quot; FROM &quot;{0}&quot;.&quot;OSHP&quot; WHERE &quot;TrnspName&quot; = &apos;{1}&apos;.
        /// </summary>
        public static string TipoTransporte_Get {
            get {
                return ResourceManager.GetString("TipoTransporte_Get", resourceCulture);
            }
        }
    }
}
