//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Tust.Import.DAO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.Tust.Import.DAO.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(CAST(Code AS INTEGER)), 0) FROM [@SIEBS_OTRF].
        /// </summary>
        internal static string BankSyncTransfer_GetMaxCode {
            get {
                return ResourceManager.GetString("BankSyncTransfer_GetMaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(BoeNum), 0) + 1 FROM OBOE.
        /// </summary>
        internal static string Boe_GetNext {
            get {
                return ResourceManager.GetString("Boe_GetNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT OCRD.CardCode, OCRD.CardName 
        ///FROM CRD7 WITH(NOLOCK) 
        ///	INNER JOIN OCRD WITH(NOLOCK)
        ///		ON OCRD.CardCode = CRD7.CardCode
        ///WHERE CRD7.TaxId0 = &apos;{0}&apos;.
        /// </summary>
        internal static string BusinessPartner_GetByCnpj {
            get {
                return ResourceManager.GetString("BusinessPartner_GetByCnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 1  FROM OPYM
        ///	INNER JOIN OCRD
        ///		ON OPYM.BnkDflt = OCRD.BankCode
        ///WHERE OPYM.PayMethCod = &apos;{0}&apos;
        ///AND OCRD.CardCode = &apos;{1}&apos;.
        /// </summary>
        internal static string PayMethod_Validation {
            get {
                return ResourceManager.GetString("PayMethod_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ISNULL(MAX(CAST(Code AS INTEGER)), 0) FROM [@SKILL_INF_ITEM_DOC].
        /// </summary>
        internal static string SkillItemAdditionalInformation_GetMaxCode {
            get {
                return ResourceManager.GetString("SkillItemAdditionalInformation_GetMaxCode", resourceCulture);
            }
        }
    }
}
