IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SEF_0400')
	DROP PROCEDURE SP_CVA_SEF_0400
GO
CREATE PROCEDURE SP_CVA_SEF_0400
(
	@Filial			INT,
	@DataDe			DATETIME,
	@DataAte		DATETIME
)
AS
BEGIN
	SELECT '0400' Linha, OUSG.Id UsageId, OUSG.Usage UsageDesc, OUSG.U_CVA_ICMS ICMS FROM OPDN WITH(NOLOCK) INNER JOIN PDN1 WITH(NOLOCK) ON PDN1.DocEntry = OPDN.DocEntry INNER JOIN OUSG WITH(NOLOCK) ON OUSG.Id = PDN1.Usage WHERE OPDN.CANCELED = 'N' AND OPDN.BPLId = @Filial AND OPDN.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY OUSG.Id, OUSG.Usage, OUSG.U_CVA_ICMS

	UNION

	SELECT '0400' Linha, OUSG.Id UsageId, OUSG.Usage UsageDesc, OUSG.U_CVA_ICMS ICMS FROM OPCH WITH(NOLOCK) INNER JOIN PCH1 WITH(NOLOCK) ON PCH1.DocEntry = OPCH.DocEntry INNER JOIN OUSG WITH(NOLOCK) ON OUSG.Id = PCH1.Usage WHERE OPCH.CANCELED = 'N' AND OPCH.BPLId = @Filial AND OPCH.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY OUSG.Id, OUSG.Usage, OUSG.U_CVA_ICMS

	UNION

	SELECT '0400' Linha, OUSG.Id UsageId, OUSG.Usage UsageDesc, OUSG.U_CVA_ICMS ICMS FROM ORDN WITH(NOLOCK) INNER JOIN RDN1 WITH(NOLOCK) ON RDN1.DocEntry = ORDN.DocEntry INNER JOIN OUSG WITH(NOLOCK) ON OUSG.Id = RDN1.Usage WHERE ORDN.CANCELED = 'N' AND ORDN.BPLId = @Filial AND ORDN.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY OUSG.Id, OUSG.Usage, OUSG.U_CVA_ICMS

	UNION

	SELECT '0400' Linha, OUSG.Id UsageId, OUSG.Usage UsageDesc, OUSG.U_CVA_ICMS ICMS FROM ORIN WITH(NOLOCK) INNER JOIN RIN1 WITH(NOLOCK) ON RIN1.DocEntry = ORIN.DocEntry INNER JOIN OUSG WITH(NOLOCK) ON OUSG.Id = RIN1.Usage WHERE ORIN.CANCELED = 'N' AND ORIN.BPLId = @Filial AND ORIN.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY OUSG.Id, OUSG.Usage, OUSG.U_CVA_ICMS

	UNION

	SELECT '0400' Linha, OUSG.Id UsageId, OUSG.Usage UsageDesc, OUSG.U_CVA_ICMS ICMS FROM ODLN WITH(NOLOCK) INNER JOIN DLN1 WITH(NOLOCK) ON DLN1.DocEntry = ODLN.DocEntry INNER JOIN OUSG WITH(NOLOCK) ON OUSG.Id = DLN1.Usage WHERE ODLN.CANCELED = 'N' AND ODLN.BPLId = @Filial AND ODLN.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY OUSG.Id, OUSG.Usage, OUSG.U_CVA_ICMS

	UNION

	SELECT '0400' Linha, OUSG.Id UsageId, OUSG.Usage UsageDesc, OUSG.U_CVA_ICMS ICMS FROM OINV WITH(NOLOCK) INNER JOIN INV1 WITH(NOLOCK) ON INV1.DocEntry = OINV.DocEntry INNER JOIN OUSG WITH(NOLOCK) ON OUSG.Id = INV1.Usage WHERE OINV.CANCELED = 'N' AND OINV.BPLId = @Filial AND OINV.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY OUSG.Id, OUSG.Usage, OUSG.U_CVA_ICMS

	UNION

	SELECT '0400' Linha, OUSG.Id UsageId, OUSG.Usage UsageDesc, OUSG.U_CVA_ICMS ICMS FROM ORPD WITH(NOLOCK) INNER JOIN RPD1 WITH(NOLOCK) ON RPD1.DocEntry = ORPD.DocEntry INNER JOIN OUSG WITH(NOLOCK) ON OUSG.Id = RPD1.Usage WHERE ORPD.CANCELED = 'N' AND ORPD.BPLId = @Filial AND ORPD.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY OUSG.Id, OUSG.Usage, OUSG.U_CVA_ICMS

	UNION

	SELECT '0400' Linha, OUSG.Id UsageId, OUSG.Usage UsageDesc, OUSG.U_CVA_ICMS ICMS FROM ORPC WITH(NOLOCK) INNER JOIN RPC1 WITH(NOLOCK) ON RPC1.DocEntry = ORPC.DocEntry INNER JOIN OUSG WITH(NOLOCK) ON OUSG.Id = RPC1.Usage WHERE ORPC.CANCELED = 'N' AND ORPC.BPLId = @Filial AND ORPC.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY OUSG.Id, OUSG.Usage, OUSG.U_CVA_ICMS
END