USE [SBOHybel]
GO
/****** Object:  StoredProcedure [dbo].[SP_CVA_SIMULADOR_SAIDA]    Script Date: 10/6/2021 12:08:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/********************************************************************************************************                                
-- Data Criacao  :               Autor:
-- Data Alteracao: 06/10/2021    Autor: Luis Nogueira
-- Procedure : SP_CVA_SIMULADOR_SAIDA

-- Versao 1.0.3    : SIMULADOR DE VENDAS
-- Alteração       : Ajustes para correto funcionamento do script, após restauração ambiente.
-- OBS             :                                     
*********************************************************************************************************/


/********************************************************************************************************
				PROCEDURE DO SIMULADOR DE VENDAS PARA MOSTRAR ONDE ESTA RESERVADO O ITEM
									CVA CONSULTORIA - LEANDRO MAZZUCCO
---------------------------------------------------------------------------------------------------------
ALTERAÇÕES
----------


002 - 27/08/2019 - LEANDRO MAZZUCCO --> INCLUIDO COMANDO PARA VERIFICAR A QUANTIADDE NECESSARIA UTILIZANDO A 
										ESTRUTURA DA BOMBA * A QUANTIDADE NO PEDIDO, EXIBINDO ASSIM A QUANTIDADE
										CORRETA RESERVADA.	


001 - 16/08/2019 - LEANDRO MAZZUCCO --> INCLUIDO COMANDO PARA VERIFICAR EM QUAIS OPS O ITEM TAMBÉM ESTA RESERVADO
										PARA PODER TER UMA MELHOR VISÃO.							

*********************************************************************************************************/

ALTER PROCEDURE [dbo].[SP_CVA_SIMULADOR_SAIDA]
(
	@ItemCode		NVARCHAR(60)
)
AS
BEGIN
	SELECT 
		TT.ItemCode,
		CONS.[Nr. OP],
		CONS.DocEntryPV,
		CONS.LineNumPV,
		CONS.CardCodePV,
		CONS.QtdeConsOP,
		CONS.[Dt. Lanc],
		CONS.[Dt. Reserva]
	INTO #OP
	FROM (SELECT @ItemCode ItemCode) TT
		LEFT JOIN	(
						SELECT
							POS.ItemCode,
							AUPT.BELNR_ID		[Nr. OP],
							AUPT.LFGDAT			[Dt. Lanc],
							AUPT.BELDAT			[Dt. Reserva],
							AUPT.KND_ID			CardCodePV,
							AUPT.DocEntry		DocEntryPV,
							AUPT.AUFTRAGPOS		LineNumPV,
							POS.MENGE_VERBRAUCH QtdeConsOP
						FROM BEAS_FTHAUPT AUPT WITH(NOLOCK)
							INNER JOIN BEAS_FTPOS POS WITH(NOLOCK)
								ON POS.BELNR_ID = AUPT.BELNR_ID
								AND POS.STUFE <> 0
						WHERE AUPT.ABGKZ = 'N'
					) CONS ON CONS.ItemCode = @ItemCode
	
	;WITH Produtos(ParentId, ChildId, QtdeConsPV, Lvl) AS
	(
		SELECT 
			STL.ItemCode ParentId,
			STL.ART1_ID ChildId,
			STL.MENGE_LAGER AS QtdeConsPV,
			STL.POS_ID AS Lvl 
		FROM dbo.BEAS_STL STL WITH(NOLOCK)
		WHERE STL.ItemCode = @ItemCode
		  and STL.ItemCode <> STL.ART1_ID

		UNION ALL

		SELECT 
			RH.ItemCode ParentId,
			RH.ART1_ID ChildId,
			CAST(RC.QtdeConsPV * RH.MENGE_LAGER AS NUMERIC(19,6)) QtdeConsPV,
			RH.POS_ID AS Lvl
		FROM dbo.BEAS_STL AS RH WITH(NOLOCK) INNER JOIN Produtos AS RC ON RH.ItemCode = RC.ChildId
	) 
		
	,CTE_RN AS 
	(
		SELECT *, ROW_NUMBER() OVER (PARTITION BY r.ChildID ORDER BY r.Lvl DESC) RN
		FROM Produtos r WITH (NOLOCK)
	)
	-- Agrupa os produtos para evitar duplicidade
	,CTE_RN_GROUPED AS 
	(
		SELECT 
			ParentId,
			QtdeConsPV
		FROM CTE_RN WITH (NOLOCK)
		WHERE Lvl = 10
		GROUP BY ParentId, QtdeConsPV
	)
	-- Busca os pedidos de venda
	SELECT 
		RDR1.WhsCode	[Depósito],
		ORDR.DocNum		[Nr. Doc],
		ORDR.DocDate	[Dt Reserva],
		ORDR.DocDueDate	[Dt Lanc],
		RDR1.OpenQty * (SELECT ISNULL(SUM(MENGE_LAGER),1) FROM BEAS_STL WHERE ITEMCODE = CTE.ParentId AND ART1_ID = @ItemCode) [Qtde], --002
		ORDR.CardName	[Cliente]
	INTO #Pedido
	FROM CTE_RN_GROUPED CTE WITH (NOLOCK) INNER JOIN RDR1 WITH(NOLOCK) ON RDR1.ItemCode = CTE.ParentId AND RDR1.OpenQty > 0
		 INNER JOIN ORDR WITH(NOLOCK) ON ORDR.DocEntry = RDR1.DocEntry AND ORDR.DocStatus = 'O'
	WHERE 
	
	--VERIFICA SE NÃO POSSUI OP
	(
		SELECT DISTINCT COUNT(*)		
		FROM BEAS_FTHAUPT	  A WITH(NOLOCK)
			 INNER JOIN BEAS_FTPOS B WITH(NOLOCK) ON B.BELNR_ID = A.BELNR_ID and b.ABGKZ <> 'J' 
			 INNER JOIN BEAS_FTSTL C WITH(NOLOCK) ON C.BELNR_ID = A.BELNR_ID AND C.BELPOS_ID = B.BELPOS_ID AND C.ABGKZ <> 'J'
		WHERE A.ABGKZ <> 'J' --ABERTAS
		  AND A.AUFTRAGINT  = RDR1.DOCENTRY
		  AND (SELECT COUNT(A1.BELNR_ID) FROM BEAS_ARBZEIT A1 WITH(NOLOCK) WHERE A1.BELNR_ID  = A.BELNR_ID AND A1.POS_ID = (SELECT TOP 1 POS_ID FROM BEAS_FTAPL WITH(NOLOCK) WHERE BELNR_ID  = A1.BELNR_ID AND BELPOS_ID = 10 ORDER BY SortId DESC)) = 0 --ULTIMO PROCESSO ABERTO		
		  AND C.ART1_ID = @ItemCode --ITEMCODE
		  AND 
		
		--NÃO TENHA ENTRADO NO ESTOQUE AINDA MESMO SEM APONTAMENTO
		(SELECT COUNT(*)
		FROM IGN1 WITH(NOLOCK)
		INNER	   JOIN OIGN	WITH(NOLOCK) ON OIGN.DOCENTRY=IGN1.DOCENTRY 
		LEFT OUTER JOIN OITM	WITH(NOLOCK) ON OITM.ITEMCODE=IGN1.ITEMCODE 
		LEFT OUTER JOIN BEAS_ME WITH(NOLOCK) ON BEAS_ME.ME_ID=OITM.INVNTRYUOM 
		LEFT OUTER JOIN OWHS	WITH(NOLOCK) ON OWHS.WHSCODE=IGN1.WHSCODE 
		WHERE IGN1.U_BELNRID=B.BELNR_ID AND IGN1.U_BELPOSID=C.BELPOS_ID AND IGN1.U_POSID=C.POS_ID) = 0
		
		AND 
		
		(SELECT COUNT(*)
		 FROM IGE1 IGN1			WITH(NOLOCK)
		INNER JOIN OIGE OIGN	WITH(NOLOCK) ON OIGN.DOCENTRY=IGN1.DOCENTRY 
		LEFT OUTER JOIN OITM	WITH(NOLOCK) ON OITM.ITEMCODE=IGN1.ITEMCODE 
		LEFT OUTER JOIN BEAS_ME WITH(NOLOCK) ON BEAS_ME.ME_ID=OITM.INVNTRYUOM 
		LEFT OUTER JOIN OWHS	WITH(NOLOCK) ON OWHS.WHSCODE=IGN1.WHSCODE 
		WHERE IGN1.U_BELNRID=B.BELNR_ID AND IGN1.U_BELPOSID=C.BELPOS_ID AND IGN1.U_POSID=C.POS_ID ) = 0
		
		AND
		
		(SELECT COUNT(*)
		 FROM WTR1				WITH(NOLOCK) 
		INNER JOIN OWTR			WITH(NOLOCK) ON OWTR.DOCENTRY=WTR1.DOCENTRY 
		LEFT OUTER JOIN OITM	WITH(NOLOCK) ON OITM.ITEMCODE=WTR1.ITEMCODE 
		LEFT OUTER JOIN BEAS_ME WITH(NOLOCK) ON BEAS_ME.ME_ID=OITM.INVNTRYUOM 
		LEFT OUTER JOIN OWHS	WITH(NOLOCK) ON OWHS.WHSCODE=WTR1.WHSCODE 
		WHERE WTR1.U_BELNRID=B.BELNR_ID AND WTR1.U_BELPOSID=C.BELPOS_ID AND WTR1.U_POSID=C.POS_ID) = 0
	) = 0


	AND	
	
	
	NOT EXISTS
	(
		SELECT TOP 1 1 FROM RDR1 WITH(NOLOCK) 
			INNER JOIN #OP OP WITH (NOLOCK)
				ON OP.DocEntryPV = RDR1.DocEntry
				AND OP.LineNumPV = RDR1.LineNum
	)
	ORDER BY ORDR.DocNum
	

	SELECT * INTO #DADOS FROM
	(
		SELECT DISTINCT
			OP.[Nr. OP]	[Nr. Doc],
			OP.[Dt. Reserva],
			OP.[Dt. Lanc],
			CASE WHEN ISNULL(DocEntryPV, 0) = 0
				THEN 'OP'
				ELSE CASE WHEN ISNULL(OBPL.BPlId, 0) = 0
					THEN 'PC'
					ELSE 'PE'
				END
			END Tipo,
			OP.QtdeConsOP	[Qtde],
			CAST(OBPL.AliasName	AS NVARCHAR(MAX)) [Cliente]
		FROM #OP OP WITH (NOLOCK)
			LEFT JOIN CRD7 WITH(NOLOCK)
				ON CRD7.CardCode = OP.CardCodePV
			LEFT JOIN OBPL WITH(NOLOCK)
				ON OBPL.TaxIdNum = CRD7.TaxId0
		WHERE OP.[Nr. OP] IS NOT NULL

		--001
		
		UNION ALL


		SELECT DISTINCT

		A.BELNR_ID [Nr. Doc],
		A.BELDAT [Dt Reserva],
		A.BELDAT [Dt. Lanc],
		'OP',
		C.TOTALQUANTITY_WHUNIT [Qtde],
		A.KNDNAME [Cliente]
		
		FROM BEAS_FTHAUPT	  A WITH(NOLOCK)
		INNER JOIN BEAS_FTPOS B WITH(NOLOCK) ON B.BELNR_ID = A.BELNR_ID and b.ABGKZ <> 'J'
		INNER JOIN BEAS_FTSTL C WITH(NOLOCK) ON C.BELNR_ID = A.BELNR_ID AND C.BELPOS_ID = B.BELPOS_ID AND C.ABGKZ <> 'J'

		
		
		WHERE
		--ABERTAS
		A.ABGKZ <> 'J'

		--AND A.AUFTRAGINT IS NULL
		
		--ULTIMO PROCESSO ABERTO
		AND (SELECT COUNT(A1.BELNR_ID) FROM BEAS_ARBZEIT A1 WITH(NOLOCK) WHERE A1.BELNR_ID  = A.BELNR_ID AND A1.POS_ID = (SELECT TOP 1 POS_ID FROM BEAS_FTAPL WITH(NOLOCK) WHERE BELNR_ID  = A1.BELNR_ID AND BELPOS_ID = 10 ORDER BY SortId DESC)) = 0
		
		
		--ITEMCODE
		AND C.ART1_ID = @ItemCode
		
		AND 
		
		--NÃO TENHA ENTRADO NO ESTOQUE AINDA MESMO SEM APONTAMENTO
		(SELECT COUNT(*)
		FROM IGN1 WITH(NOLOCK)
		INNER	   JOIN OIGN	WITH(NOLOCK) ON OIGN.DOCENTRY=IGN1.DOCENTRY 
		LEFT OUTER JOIN OITM	WITH(NOLOCK) ON OITM.ITEMCODE=IGN1.ITEMCODE 
		LEFT OUTER JOIN BEAS_ME WITH(NOLOCK) ON BEAS_ME.ME_ID=OITM.INVNTRYUOM 
		LEFT OUTER JOIN OWHS	WITH(NOLOCK) ON OWHS.WHSCODE=IGN1.WHSCODE 
		WHERE IGN1.U_BELNRID=B.BELNR_ID AND IGN1.U_BELPOSID=C.BELPOS_ID AND IGN1.U_POSID=C.POS_ID) = 0
		
		AND 
		
		(SELECT COUNT(*)
		 FROM IGE1 IGN1			WITH(NOLOCK)
		INNER JOIN OIGE OIGN	WITH(NOLOCK) ON OIGN.DOCENTRY=IGN1.DOCENTRY 
		LEFT OUTER JOIN OITM	WITH(NOLOCK) ON OITM.ITEMCODE=IGN1.ITEMCODE 
		LEFT OUTER JOIN BEAS_ME WITH(NOLOCK) ON BEAS_ME.ME_ID=OITM.INVNTRYUOM 
		LEFT OUTER JOIN OWHS	WITH(NOLOCK) ON OWHS.WHSCODE=IGN1.WHSCODE 
		WHERE IGN1.U_BELNRID=B.BELNR_ID AND IGN1.U_BELPOSID=C.BELPOS_ID AND IGN1.U_POSID=C.POS_ID ) = 0
		
		AND
		
		(SELECT COUNT(*)
		 FROM WTR1				WITH(NOLOCK) 
		INNER JOIN OWTR			WITH(NOLOCK) ON OWTR.DOCENTRY=WTR1.DOCENTRY 
		LEFT OUTER JOIN OITM	WITH(NOLOCK) ON OITM.ITEMCODE=WTR1.ITEMCODE 
		LEFT OUTER JOIN BEAS_ME WITH(NOLOCK) ON BEAS_ME.ME_ID=OITM.INVNTRYUOM 
		LEFT OUTER JOIN OWHS	WITH(NOLOCK) ON OWHS.WHSCODE=WTR1.WHSCODE 
		WHERE WTR1.U_BELNRID=B.BELNR_ID AND WTR1.U_BELPOSID=C.BELPOS_ID AND WTR1.U_POSID=C.POS_ID) = 0
		--//
		

		UNION ALL

		SELECT 
			Pedido.[Nr. Doc],
			Pedido.[Dt Reserva],
			Pedido.[Dt Lanc],
			'PV',
			SUM(Pedido.[Qtde]),
			Pedido.[Cliente]
		FROM #Pedido Pedido WITH (NOLOCK)
		GROUP BY
			Pedido.[Nr. Doc],
			Pedido.[Dt Reserva],
			Pedido.[Dt Lanc],
			Pedido.[Cliente]
	) Reserva
	ORDER BY [Nr. Doc]


	SELECT * INTO #FINAL FROM #DADOS

	SELECT *,
	TOTAL_RESERVADO = (SELECT SUM(QTDE) FROM #FINAL)
	FROM #DADOS
	option (maxrecursion 00)

	DROP TABLE #OP
	DROP TABLE #Pedido
	DROP TABLE #DADOS
	DROP TABLE #FINAL
END
