IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SERIE_SAIDA')
	DROP PROCEDURE SP_CVA_SERIE_SAIDA
GO
CREATE PROCEDURE SP_CVA_SERIE_SAIDA
(
	@DataDe		DATETIME,
	@DataAte	DATETIME
)
AS
BEGIN
	SELECT
		OITL.ItemCode,
		OITL.ItemName,
		CASE WHEN OINV.DocEntry IS NOT NULL
			THEN 'NF'
			ELSE 'Entrega'
		END	DocType,
		CASE WHEN OINV.DocEntry IS NOT NULL
			THEN OINV.DocNum
			ELSE ODLN.DocNum
		END	DocNum,
		CASE WHEN OINV.DocEntry IS NOT NULL
			THEN OINV.Serial
			ELSE ODLN.Serial
		END	Serial,
		CASE WHEN OINV.DocEntry IS NOT NULL
			THEN OINV.DocDate
			ELSE ODLN.DocDate
		END	DocDate,
		CASE WHEN OINV.DocEntry IS NOT NULL
			THEN OINV.CardCode
			ELSE ODLN.CardCode
		END	CardCode,
		CASE WHEN OINV.DocEntry IS NOT NULL
			THEN OINV.CardName
			ELSE ODLN.CardName
		END	CardName,
		OSRN.DistNumber,
		OADP.LogoImage,
		OBPL.BPLName,
		OBPL.BPLFrName
	FROM		ITL1 WITH(NOLOCK)
		INNER JOIN	OITL WITH(NOLOCK) ON OITL.LogEntry = ITL1.LogEntry
		INNER JOIN	OSRN WITH(NOLOCK) ON ITL1.ItemCode = OSRN.ItemCode and ITL1.SysNumber = OSRN.SysNumber
		LEFT JOIN	INV1 WITH(NOLOCK) ON INV1.DocEntry = OITL.ApplyEntry AND INV1.LineNum = OITL.ApplyLine AND OITL.ApplyType = 13
		LEFT JOIN	OINV WITH(NOLOCK) ON OINV.DocEntry = INV1.DocEntry
		LEFT JOIN	DLN1 WITH(NOLOCK) ON DLN1.DocEntry = OITL.ApplyEntry AND DLN1.LineNum = OITL.ApplyLine AND OITL.ApplyType = 15
		LEFT JOIN	ODLN WITH(NOLOCK) ON ODLN.DocEntry = DLN1.DocEntry
		LEFT JOIN	OADP WITH(NOLOCK) ON 1 = 1
		LEFT JOIN	OBPL WITH(NOLOCK) ON OBPL.BPLId = 1
	WHERE ISNULL(OINV.DocEntry, 0) <> 0 OR ISNULL(ODLN.DocEntry, 0) <> 0
	AND ISNULL(OINV.DocDate, DATEADD(YEAR, -100, GETDATE())) BETWEEN @DataDe AND @DataAte
	AND ISNULL(ODLN.DocDate, DATEADD(YEAR, -100, GETDATE())) BETWEEN @DataDe AND @DataAte
	--AND ITL1.ItemCode = @ItemCode
	ORDER BY
		CASE WHEN OINV.DocEntry IS NOT NULL
			THEN OINV.DocDate
			ELSE ODLN.DocDate
		END
END