IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_PICKING')
	DROP PROCEDURE SP_CVA_PICKING
GO
CREATE PROCEDURE SP_CVA_PICKING
(
	@DocKey INT
)
AS
BEGIN
	SELECT
		OPKL.AbsEntry,
		OPKL.PickDate,
		OPKL.Name,
		ORDR.DocNum,
		ORDR.CardCode,
		ORDR.CardName,
		CRD1.State,
		RDR1.ItemCode,
		RDR1.Dscription,
		PKL1.RelQtty,
		PKL1.PickQtty,
		OBPL.BPLName,
		OBPL.BPLFrName,
		OADP.LogoImage
	FROM OPKL WITH(NOLOCK)
		INNER JOIN	PKL1 WITH(NOLOCK) ON PKL1.AbsEntry = OPKL.AbsEntry
		INNER JOIN	RDR1 WITH(NOLOCK) ON RDR1.DocEntry = PKL1.OrderEntry AND RDR1.LineNum = PKL1.OrderLine AND PKL1.BaseObject = 17
		INNER JOIN	ORDR WITH(NOLOCK) ON ORDR.DocEntry = RDR1.DocEntry
		INNER JOIN	CRD1 WITH(NOLOCK) ON CRD1.CardCode = ORDR.CardCode AND CRD1.AdresType = 'S'
		INNER JOIN	OBPL WITH(NOLOCK) ON OBPL.BPLId = ORDR.BPLId
		INNER JOIN	OUSR WITH(NOLOCK) ON OUSR.USERID = OPKL.OwnerCode
		--LEFT JOIN	OITL WITH(NOLOCK) ON OITL.ApplyEntry = RDR1.DocEntry AND OITL.ApplyLine = RDR1.LineNum AND OITL.ApplyType = 17
		--LEFT JOIN	ITL1 WITH(NOLOCK) ON ITL1.LogEntry = OITL.LogEntry
		--LEFT JOIN	OSRN WITH(NOLOCK) ON ITL1.ItemCode = OSRN.ItemCode and ITL1.SysNumber = OSRN.SysNumber
		LEFT JOIN	OADP WITH(NOLOCK) ON 1 = 1
	WHERE OPKL.AbsEntry = @DocKey
END

