IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SERIE_DISPONIVEL')
	DROP PROCEDURE SP_CVA_SERIE_DISPONIVEL
GO
CREATE PROCEDURE SP_CVA_SERIE_DISPONIVEL
(
	@ItemCode	NVARCHAR(100)
)
AS
BEGIN
	SELECT OSRN.DistNumber, OSRN.InDate, OSRN.MnfDate, OSRN.ExpDate
	FROM		ITL1 WITH(NOLOCK)
			INNER JOIN	OITL WITH(NOLOCK) ON OITL.LogEntry = ITL1.LogEntry
			INNER JOIN	OSRN WITH(NOLOCK) ON ITL1.ItemCode = OSRN.ItemCode and ITL1.SysNumber = OSRN.SysNumber
	WHERE ITL1.ItemCode = @ItemCode
	GROUP BY OSRN.DistNumber, OSRN.InDate, OSRN.MnfDate, OSRN.ExpDate
	HAVING SUM(ITL1.Quantity) > 0
	ORDER BY OSRN.ExpDate DESC, OSRN.MnfDate DESC, OSRN.InDate DESC
END