//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.NF.Import.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVA_BAS
    {
        public int ID { get; set; }
        public System.DateTime INS { get; set; }
        public Nullable<System.DateTime> UPD { get; set; }
        public Nullable<int> STU { get; set; }
        public string SRVR { get; set; }
        public string PAS { get; set; }
        public string COMP { get; set; }
        public Nullable<int> USE_TRU { get; set; }
        public string UNAME { get; set; }
        public string DB_UNAME { get; set; }
        public string DB_PAS { get; set; }
        public Nullable<int> DB_TYP { get; set; }
        public string DB_SRVR { get; set; }
    }
}
