//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.NF.Import.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportParamModel
    {
        public int ID { get; set; }
        public System.DateTime INS { get; set; }
        public Nullable<System.DateTime> UPD { get; set; }
        public int BASE_ID { get; set; }
        public string BASE_NAME { get; set; }
        public string CNPJ { get; set; }
        public string ITEMCODE { get; set; }
        public int USAGE { get; set; }
        public string COSTCENTER { get; set; }
        public string PROJECT { get; set; }
        public int NFSEQ { get; set; }
        public string REMARKS { get; set; }
        public int BPLID { get; set; }
        public Nullable<decimal> ALIQIPI { get; set; }
        public string APLIC { get; set; }
    }
}
