//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Core.TransportLCM.SERVICE.BasePortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.Core.TransportLCM.SERVICE.BasePortal.Resources.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT GRP.DSCR + &apos;.&apos; + CAST(ITEM.TYPE AS VARCHAR(10))
        ///FROM CVA_APPR_GROUP GRP
        ///	INNER JOIN CVA_APPR_GROUP_ITEM ITEM
        ///		ON ITEM.ID_GROUP = GRP.ID
        ///	INNER JOIN CVA_APPR_GROUP_ACC ACC
        ///		ON ACC.GROUP_ID = GRP.ID
        ///WHERE ITEM.VAL_FROM &lt;= {0}
        ///AND ITEM.VAL_TO &gt;= {0}
        ///AND ACC_CODE = &apos;{1}&apos;.
        /// </summary>
        internal static string ApprovalGroupAccount_GetByRange {
            get {
                return ResourceManager.GetString("ApprovalGroupAccount_GetByRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT GROUP_ID FROM CVA_APPR_GROUP_ACC
        ///WHERE ACC_CODE IN ({0}).
        /// </summary>
        internal static string ApprovalGroupAccount_GetDistinctGroups {
            get {
                return ResourceManager.GetString("ApprovalGroupAccount_GetDistinctGroups", resourceCulture);
            }
        }
    }
}
