IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_EDOC_0200')
	DROP PROCEDURE SP_CVA_EDOC_0200
GO
CREATE PROCEDURE SP_CVA_EDOC_0200
(
	@Filial			INT,
	@DataDe			DATETIME,
	@DataAte		DATETIME
)
AS
BEGIN
	SELECT ItemCode INTO #Item FROM
	(
		SELECT ItemCode FROM OPDN WITH(NOLOCK) INNER JOIN PDN1 WITH(NOLOCK) ON PDN1.DocEntry = OPDN.DocEntry WHERE CANCELED = 'N' AND OPDN.BPLId = @Filial AND OPDN.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY ItemCode

		UNION

		SELECT ItemCode FROM OPCH WITH(NOLOCK) INNER JOIN PCH1 WITH(NOLOCK) ON PCH1.DocEntry = OPCH.DocEntry WHERE CANCELED = 'N' AND OPCH.BPLId = @Filial AND OPCH.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY ItemCode

		UNION

		SELECT ItemCode FROM ORDN WITH(NOLOCK) INNER JOIN RDN1 WITH(NOLOCK) ON RDN1.DocEntry = ORDN.DocEntry WHERE CANCELED = 'N' AND ORDN.BPLId = @Filial AND ORDN.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY ItemCode

		UNION

		SELECT ItemCode FROM ORIN WITH(NOLOCK) INNER JOIN RIN1 WITH(NOLOCK) ON RIN1.DocEntry = ORIN.DocEntry WHERE CANCELED = 'N' AND ORIN.BPLId = @Filial AND ORIN.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY ItemCode

		UNION

		SELECT ItemCode FROM ODLN WITH(NOLOCK) INNER JOIN DLN1 WITH(NOLOCK) ON DLN1.DocEntry = ODLN.DocEntry WHERE CANCELED = 'N' AND ODLN.BPLId = @Filial AND ODLN.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY ItemCode

		UNION

		SELECT ItemCode FROM OINV WITH(NOLOCK) INNER JOIN INV1 WITH(NOLOCK) ON INV1.DocEntry = OINV.DocEntry WHERE CANCELED = 'N' AND OINV.BPLId = @Filial AND OINV.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY ItemCode

		UNION

		SELECT ItemCode FROM ORPD WITH(NOLOCK) INNER JOIN RPD1 WITH(NOLOCK) ON RPD1.DocEntry = ORPD.DocEntry WHERE CANCELED = 'N' AND ORPD.BPLId = @Filial AND ORPD.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY ItemCode

		UNION

		SELECT ItemCode FROM ORPC WITH(NOLOCK) INNER JOIN RPC1 WITH(NOLOCK) ON RPC1.DocEntry = ORPC.DocEntry WHERE CANCELED = 'N' AND ORPC.BPLId = @Filial AND ORPC.DocDate BETWEEN @DataDe AND @DataAte AND Model IN (1, 3, 5, 39) GROUP BY ItemCode
	) DOCS

	SELECT 
		'0200' Linha,
		OITM.ItemCode,
		OITM.ItemName,
		SUBSTRING(ONCM.NcmCode, 1, 2) CodGenero
	FROM #Item Item
		INNER JOIN OITM WITH(NOLOCK)
			ON OITM.ItemCode = Item.ItemCode
		INNER JOIN ONCM WITH(NOLOCK)
			ON ONCM.AbsEntry = OITM.NCMCode
END