IF EXISTS (SELECT * FROM sys.objects WHERE type = 'IF' AND name = 'FN_CVA_SEF_E020')
	DROP FUNCTION FN_CVA_SEF_E020
GO

--- SELECT * FROM FN_CVA_SEF_E020 (9,'2018-01-01', '2018-31-01')
CREATE FUNCTION FN_CVA_SEF_E020
(
	@Filial			INT,
	@DataInicial	DATETIME,
	@DataFinal		DATETIME
) RETURNS TABLE
AS
RETURN
(
	SELECT DISTINCT
		OPDN.DocEntry,
		OPDN.ObjType,
		CASE WHEN PDN1.CFOPCode LIKE '1%' OR PDN1.CFOPCode LIKE '2%' OR PDN1.CFOPCode LIKE '3%' 
			THEN 0
			ELSE 1
		END									IND_OPER,
		0									IND_EMIT,
		OPDN.CardCode						COD_PART,
		ONFM.NfmCode						COD_MOD,
		'00'								COD_SIT,
		OPDN.SeriesStr						SER,
		OPDN.Serial							NUM_DOC,
		OPDN.U_chaveacesso					CHV_NFE,
		OPDN.TaxDate						DT_EMIS,
		OPDN.DocDate						DT_DOC,
		PDN1.Usage							COD_NAT,
		OUSG.U_CVA_ICMS						COP,
		OPDN.DocNum							NUM_LCTO,
		CASE WHEN OPDN.Installmnt = 1
			THEN 0
			ELSE 1
		END									IND_PGTO,
		OPDN.DocTotal						VL_CONT,
		ISNULL(ISS.BaseSum,0.00)			VL_OP_ISS,
		ISNULL(ICMS.BaseSum,0.00)			VL_BC_ICMS,
		ISNULL(ICMS.TaxSum,0.00)			VL_ICMS,
		ISNULL(ICMS_ST.TaxSum,0.00)			VL_ICMS_ST,
		CASE WHEN PDN1.CFOPCode LIKE '1%' OR PDN1.CFOPCode LIKE '2%' OR PDN1.CFOPCode LIKE '3%' 
			THEN ISNULL(ICMS_ST.TaxSum,0)
			ELSE 0.00
		END	VL_ST_E,
		CASE WHEN PDN1.CFOPCode LIKE '1%' OR PDN1.CFOPCode LIKE '2%' OR PDN1.CFOPCode LIKE '3%' 
			THEN 0.00
			ELSE ICMS_ST.TaxSum
		END VL_ST_S,
		ICMS_ST.TaxSum		VL_AT,
		ICMS.Isentas		VL_ISNT_ICMS,
		ICMS.Outras			VL_OUT_ICMS,
		IPI.BaseSum			VL_BC_IPI,
		IPI.TaxSum			VL_IPI,
		IPI.Isentas			VL_ISNT_IPI,
		IPI.Outras			VL_OUT_IPI,
		''					COD_INF_OBS
	FROM OPDN WITH(NOLOCK)
		INNER JOIN PDN1 WITH(NOLOCK)
			ON PDN1.DocEntry = OPDN.DocEntry
		INNER JOIN ONFM WITH(NOLOCK)
			ON ONFM.AbsEntry = OPDN.Model
		INNER JOIN OUSG WITH(NOLOCK)
			ON OUSG.Id = PDN1.Usage
		LEFT JOIN (SELECT FRETE.DocEntry, SUM(FRETE.LineTotal) ValorFrete FROM PDN3 FRETE WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON FRETE.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%FRETE%' GROUP BY FRETE.DocEntry) FRETE
			ON FRETE.DocEntry = OPDN.DocEntry
		LEFT JOIN (SELECT SEGURO.DocEntry, SUM(SEGURO.LineTotal) ValorSeguro FROM PDN3 SEGURO WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON SEGURO.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%SEGURO%' GROUP BY SEGURO.DocEntry) SEGURO
			ON SEGURO.DocEntry = OPDN.DocEntry
		LEFT JOIN (SELECT OUTROS.DocEntry, SUM(OUTROS.LineTotal) ValorOutrasDespesas FROM PDN3 OUTROS WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON OUTROS.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName NOT LIKE '%FRETE%' AND OEXD.ExpnsName NOT LIKE '%SEGURO%' GROUP BY OUTROS.DocEntry) OUTROS
			ON OUTROS.DocEntry = OPDN.DocEntry
		LEFT JOIN (
					SELECT PDN4.DocEntry, SUM(PDN4.TaxSum) TaxSum, SUM(PDN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
					FROM PDN4 WITH(NOLOCK) 
						INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PDN4.StaType
						INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code IN ('ISS', 'ISSQN')
					GROUP BY PDN4.DocEntry
				) ISS
			ON ISS.DocEntry = PDN1.DocEntry
		LEFT JOIN (
				SELECT PDN4.DocEntry, SUM(PDN4.TaxSum) TaxSum, SUM(PDN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
				FROM PDN4 WITH(NOLOCK) 
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PDN4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS'
				GROUP BY PDN4.DocEntry
			) ICMS
			ON ICMS.DocEntry = PDN1.DocEntry
		LEFT JOIN (
			SELECT PDN4.DocEntry, SUM(PDN4.TaxSum) TaxSum, SUM(PDN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM PDN4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PDN4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY PDN4.DocEntry
		) ICMS_ST
			ON ICMS_ST.DocEntry = PDN1.DocEntry
		LEFT JOIN (
			SELECT PDN4.DocEntry, SUM(PDN4.TaxSum) TaxSum, SUM(PDN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM PDN4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PDN4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'IPI'
			GROUP BY PDN4.DocEntry
		) IPI
			ON IPI.DocEntry = PDN1.DocEntry
	WHERE OPDN.DocDate BETWEEN @DataInicial AND @DataFinal
	AND OPDN.BPLId = @Filial
	AND ISNULL(PDN1.TargetType, 0) <> 18
	AND OPDN.CANCELED = 'N' AND Model IN (1, 3, 5, 39)

	UNION ALL

		SELECT DISTINCT
		OPCH.DocEntry,
		OPCH.ObjType,
		CASE WHEN PCH1.CFOPCode LIKE '1%' OR PCH1.CFOPCode LIKE '2%' OR PCH1.CFOPCode LIKE '3%' 
			THEN 0
			ELSE 1
		END					IND_OPER,
		0					IND_EMIT,
		OPCH.CardCode		COD_PART,
		ONFM.NfmCode		COD_MOD,
		'00'				COD_SIT,
		OPCH.SeriesStr		SER,
		OPCH.Serial			NUM_DOC,
		OPCH.U_chaveacesso	CHV_NFE,
		OPCH.TaxDate		DT_EMIS,
		OPCH.DocDate		DT_DOC,
		PCH1.Usage			COD_NAT,
		OUSG.U_CVA_ICMS		COP,
		OPCH.DocNum			NUM_LCTO,
		CASE WHEN OPCH.Installmnt = 1
			THEN 0
			ELSE 1
		END					IND_PGTO,
		OPCH.DocTotal		VL_CONT,
		ISS.BaseSum			VL_OP_ISS,
		ICMS.BaseSum		VL_BC_ICMS,
		ICMS.TaxSum			VL_ICMS,
		ICMS_ST.TaxSum		VL_ICMS_ST,
		CASE WHEN PCH1.CFOPCode LIKE '1%' OR PCH1.CFOPCode LIKE '2%' OR PCH1.CFOPCode LIKE '3%' 
			THEN ICMS_ST.TaxSum
			ELSE 0.00
		END VL_ST_E,
		CASE WHEN PCH1.CFOPCode LIKE '1%' OR PCH1.CFOPCode LIKE '2%' OR PCH1.CFOPCode LIKE '3%' 
			THEN 0.00
			ELSE ICMS_ST.TaxSum
		END VL_ST_S,
		ICMS_ST.TaxSum		VL_AT,
		ICMS.Isentas		VL_ISNT_ICMS,
		ICMS.Outras			VL_OUT_ICMS,
		IPI.BaseSum			VL_BC_IPI,
		IPI.TaxSum			VL_IPI,
		IPI.Isentas			VL_ISNT_IPI,
		IPI.Outras			VL_OUT_IPI,
		''					COD_INF_OBS
	FROM OPCH WITH(NOLOCK)
		INNER JOIN PCH1 WITH(NOLOCK)
			ON PCH1.DocEntry = OPCH.DocEntry
		INNER JOIN ONFM WITH(NOLOCK)
			ON ONFM.AbsEntry = OPCH.Model
		INNER JOIN OUSG WITH(NOLOCK)
			ON OUSG.Id = PCH1.Usage
		LEFT JOIN (SELECT FRETE.DocEntry, SUM(FRETE.LineTotal) ValorFrete FROM PCH3 FRETE WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON FRETE.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%FRETE%' GROUP BY FRETE.DocEntry) FRETE
			ON FRETE.DocEntry = OPCH.DocEntry
		LEFT JOIN (SELECT SEGURO.DocEntry, SUM(SEGURO.LineTotal) ValorSeguro FROM PCH3 SEGURO WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON SEGURO.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%SEGURO%' GROUP BY SEGURO.DocEntry) SEGURO
			ON SEGURO.DocEntry = OPCH.DocEntry
		LEFT JOIN (SELECT OUTROS.DocEntry, SUM(OUTROS.LineTotal) ValorOutrasDespesas FROM PCH3 OUTROS WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON OUTROS.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName NOT LIKE '%FRETE%' AND OEXD.ExpnsName NOT LIKE '%SEGURO%' GROUP BY OUTROS.DocEntry) OUTROS
			ON OUTROS.DocEntry = OPCH.DocEntry
		LEFT JOIN (
					SELECT PCH4.DocEntry,  SUM(PCH4.TaxSum) TaxSum, SUM(PCH4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
					FROM PCH4 WITH(NOLOCK) 
						INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PCH4.StaType
						INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code IN ('ISS', 'ISSQN')
					GROUP BY PCH4.DocEntry
				) ISS
			ON ISS.DocEntry = PCH1.DocEntry
		LEFT JOIN (
				SELECT PCH4.DocEntry, SUM(PCH4.TaxSum) TaxSum, SUM(PCH4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
				FROM PCH4 WITH(NOLOCK) 
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PCH4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS'
				GROUP BY PCH4.DocEntry
			) ICMS
			ON ICMS.DocEntry = PCH1.DocEntry
		LEFT JOIN (
			SELECT PCH4.DocEntry, SUM(PCH4.TaxSum) TaxSum, SUM(PCH4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM PCH4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PCH4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY PCH4.DocEntry
		) ICMS_ST
			ON ICMS_ST.DocEntry = PCH1.DocEntry
		LEFT JOIN (
			SELECT PCH4.DocEntry, SUM(PCH4.TaxSum) TaxSum, SUM(PCH4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM PCH4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = PCH4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'IPI'
			GROUP BY PCH4.DocEntry
		) IPI
			ON IPI.DocEntry = PCH1.DocEntry
	WHERE OPCH.DocDate BETWEEN @DataInicial AND @DataFinal
	AND OPCH.BPLId = @Filial
	AND OPCH.CANCELED = 'N' AND Model IN (1, 3, 5, 39)

	UNION ALL 

		SELECT DISTINCT
		ORDN.DocEntry,
		ORDN.ObjType,
		CASE WHEN RDN1.CFOPCode LIKE '1%' OR RDN1.CFOPCode LIKE '2%' OR RDN1.CFOPCode LIKE '3%' 
			THEN 0
			ELSE 1
		END					IND_OPER,
		0					IND_EMIT,
		ORDN.CardCode		COD_PART,
		ONFM.NfmCode		COD_MOD,
		'00'				COD_SIT,
		ORDN.SeriesStr		SER,
		ORDN.Serial			NUM_DOC,
		ORDN.U_chaveacesso	CHV_NFE,
		ORDN.TaxDate		DT_EMIS,
		ORDN.DocDate		DT_DOC,
		RDN1.Usage			COD_NAT,
		OUSG.U_CVA_ICMS		COP,
		ORDN.DocNum			NUM_LCTO,
		CASE WHEN ORDN.Installmnt = 1
			THEN 0
			ELSE 1
		END					IND_PGTO,
		ORDN.DocTotal		VL_CONT,
		ISS.BaseSum			VL_OP_ISS,
		ICMS.BaseSum		VL_BC_ICMS,
		ICMS.TaxSum			VL_ICMS,
		ICMS_ST.TaxSum		VL_ICMS_ST,
		CASE WHEN RDN1.CFOPCode LIKE '1%' OR RDN1.CFOPCode LIKE '2%' OR RDN1.CFOPCode LIKE '3%' 
			THEN ICMS_ST.TaxSum
			ELSE 0.00
		END VL_ST_E,
		CASE WHEN RDN1.CFOPCode LIKE '1%' OR RDN1.CFOPCode LIKE '2%' OR RDN1.CFOPCode LIKE '3%' 
			THEN 0.00
			ELSE ICMS_ST.TaxSum
		END VL_ST_S,
		ICMS_ST.TaxSum		VL_AT,
		ICMS.Isentas		VL_ISNT_ICMS,
		ICMS.Outras			VL_OUT_ICMS,
		IPI.BaseSum			VL_BC_IPI,
		IPI.TaxSum			VL_IPI,
		IPI.Isentas			VL_ISNT_IPI,
		IPI.Outras			VL_OUT_IPI,
		''					COD_INF_OBS
	FROM ORDN WITH(NOLOCK)
		INNER JOIN RDN1 WITH(NOLOCK)
			ON RDN1.DocEntry = ORDN.DocEntry
		INNER JOIN ONFM WITH(NOLOCK)
			ON ONFM.AbsEntry = ORDN.Model
		INNER JOIN OUSG WITH(NOLOCK)
			ON OUSG.Id = RDN1.Usage
		LEFT JOIN (SELECT FRETE.DocEntry, SUM(FRETE.LineTotal) ValorFrete FROM RDN3 FRETE WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON FRETE.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%FRETE%' GROUP BY FRETE.DocEntry) FRETE
			ON FRETE.DocEntry = ORDN.DocEntry
		LEFT JOIN (SELECT SEGURO.DocEntry, SUM(SEGURO.LineTotal) ValorSeguro FROM RDN3 SEGURO WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON SEGURO.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%SEGURO%' GROUP BY SEGURO.DocEntry) SEGURO
			ON SEGURO.DocEntry = ORDN.DocEntry
		LEFT JOIN (SELECT OUTROS.DocEntry, SUM(OUTROS.LineTotal) ValorOutrasDespesas FROM RDN3 OUTROS WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON OUTROS.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName NOT LIKE '%FRETE%' AND OEXD.ExpnsName NOT LIKE '%SEGURO%' GROUP BY OUTROS.DocEntry) OUTROS
			ON OUTROS.DocEntry = ORDN.DocEntry
		LEFT JOIN (
					SELECT RDN4.DocEntry,SUM(RDN4.TaxSum) TaxSum, SUM(RDN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
					FROM RDN4 WITH(NOLOCK) 
						INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RDN4.StaType
						INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code IN ('ISS', 'ISSQN')
					GROUP BY RDN4.DocEntry
				) ISS
			ON ISS.DocEntry = RDN1.DocEntry
		LEFT JOIN (
				SELECT RDN4.DocEntry, SUM(RDN4.TaxSum) TaxSum, SUM(RDN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
				FROM RDN4 WITH(NOLOCK) 
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RDN4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS'
				GROUP BY RDN4.DocEntry
			) ICMS
			ON ICMS.DocEntry = RDN1.DocEntry
		LEFT JOIN (
			SELECT RDN4.DocEntry, SUM(RDN4.TaxSum) TaxSum, SUM(RDN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM RDN4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RDN4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY RDN4.DocEntry
		) ICMS_ST
			ON ICMS_ST.DocEntry = RDN1.DocEntry
		LEFT JOIN (
			SELECT RDN4.DocEntry, SUM(RDN4.TaxSum) TaxSum, SUM(RDN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM RDN4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RDN4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'IPI'
			GROUP BY RDN4.DocEntry
		) IPI
			ON IPI.DocEntry = RDN1.DocEntry
	WHERE ORDN.DocDate BETWEEN @DataInicial AND @DataFinal
	AND ORDN.BPLId = @Filial
	AND ORDN.CANCELED = 'N' AND Model IN (1, 3, 5, 39)


	UNION ALL 

		SELECT DISTINCT
		ORIN.DocEntry,
		ORIN.ObjType,
		CASE WHEN RIN1.CFOPCode LIKE '1%' OR RIN1.CFOPCode LIKE '2%' OR RIN1.CFOPCode LIKE '3%' 
			THEN 0
			ELSE 1
		END					IND_OPER,
		0					IND_EMIT,
		ORIN.CardCode		COD_PART,
		ONFM.NfmCode		COD_MOD,
		'00'				COD_SIT,
		ORIN.SeriesStr		SER,
		ORIN.Serial			NUM_DOC,
		ORIN.U_chaveacesso	CHV_NFE,
		ORIN.TaxDate		DT_EMIS,
		ORIN.DocDate		DT_DOC,
		RIN1.Usage			COD_NAT,
		OUSG.U_CVA_ICMS		COP,
		ORIN.DocNum			NUM_LCTO,
		CASE WHEN ORIN.Installmnt = 1
			THEN 0
			ELSE 1
		END					IND_PGTO,
		ORIN.DocTotal		VL_CONT,
		ISS.BaseSum			VL_OP_ISS,
		ICMS.BaseSum		VL_BC_ICMS,
		ICMS.TaxSum			VL_ICMS,
		ICMS_ST.TaxSum		VL_ICMS_ST,
		CASE WHEN RIN1.CFOPCode LIKE '1%' OR RIN1.CFOPCode LIKE '2%' OR RIN1.CFOPCode LIKE '3%' 
			THEN ICMS_ST.TaxSum
			ELSE 0.00
		END VL_ST_E,
		CASE WHEN RIN1.CFOPCode LIKE '1%' OR RIN1.CFOPCode LIKE '2%' OR RIN1.CFOPCode LIKE '3%' 
			THEN 0.00
			ELSE ICMS_ST.TaxSum
		END VL_ST_S,
		ICMS_ST.TaxSum		VL_AT,
		ICMS.Isentas		VL_ISNT_ICMS,
		ICMS.Outras			VL_OUT_ICMS,
		IPI.BaseSum			VL_BC_IPI,
		IPI.TaxSum			VL_IPI,
		IPI.Isentas			VL_ISNT_IPI,
		IPI.Outras			VL_OUT_IPI,
		''					COD_INF_OBS
	FROM ORIN WITH(NOLOCK)
		INNER JOIN RIN1 WITH(NOLOCK)
			ON RIN1.DocEntry = ORIN.DocEntry
		INNER JOIN ONFM WITH(NOLOCK)
			ON ONFM.AbsEntry = ORIN.Model
		INNER JOIN OUSG WITH(NOLOCK)
			ON OUSG.Id = RIN1.Usage
		LEFT JOIN (SELECT FRETE.DocEntry, SUM(FRETE.LineTotal) ValorFrete FROM RIN3 FRETE WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON FRETE.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%FRETE%' GROUP BY FRETE.DocEntry) FRETE
			ON FRETE.DocEntry = ORIN.DocEntry
		LEFT JOIN (SELECT SEGURO.DocEntry, SUM(SEGURO.LineTotal) ValorSeguro FROM RIN3 SEGURO WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON SEGURO.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%SEGURO%' GROUP BY SEGURO.DocEntry) SEGURO
			ON SEGURO.DocEntry = ORIN.DocEntry
		LEFT JOIN (SELECT OUTROS.DocEntry, SUM(OUTROS.LineTotal) ValorOutrasDespesas FROM RIN3 OUTROS WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON OUTROS.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName NOT LIKE '%FRETE%' AND OEXD.ExpnsName NOT LIKE '%SEGURO%' GROUP BY OUTROS.DocEntry) OUTROS
			ON OUTROS.DocEntry = ORIN.DocEntry
		LEFT JOIN (
					SELECT RIN4.DocEntry, SUM(RIN4.TaxSum) TaxSum, SUM(RIN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
					FROM RIN4 WITH(NOLOCK) 
						INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RIN4.StaType
						INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code IN ('ISS', 'ISSQN')
					GROUP BY RIN4.DocEntry
				) ISS
			ON ISS.DocEntry = RIN1.DocEntry
		LEFT JOIN (
				SELECT RIN4.DocEntry, SUM(RIN4.TaxSum) TaxSum, SUM(RIN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
				FROM RIN4 WITH(NOLOCK) 
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RIN4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS'
				GROUP BY RIN4.DocEntry
			) ICMS
			ON ICMS.DocEntry = RIN1.DocEntry
		LEFT JOIN (
			SELECT RIN4.DocEntry, SUM(RIN4.TaxSum) TaxSum, SUM(RIN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM RIN4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RIN4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY RIN4.DocEntry
		) ICMS_ST
			ON ICMS_ST.DocEntry = RIN1.DocEntry
		LEFT JOIN (
			SELECT RIN4.DocEntry, SUM(RIN4.TaxSum) TaxSum, SUM(RIN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM RIN4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RIN4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'IPI'
			GROUP BY RIN4.DocEntry
		) IPI
			ON IPI.DocEntry = RIN1.DocEntry
	WHERE ORIN.DocDate BETWEEN @DataInicial AND @DataFinal
	AND ORIN.BPLId = @Filial
	AND ORIN.CANCELED = 'N' AND Model IN (1, 3, 5, 39)

	UNION ALL 

		SELECT DISTINCT
		ODLN.DocEntry,
		ODLN.ObjType,
		CASE WHEN DLN1.CFOPCode LIKE '1%' OR DLN1.CFOPCode LIKE '2%' OR DLN1.CFOPCode LIKE '3%' 
			THEN 0
			ELSE 1
		END					IND_OPER,
		0					IND_EMIT,
		ODLN.CardCode		COD_PART,
		ONFM.NfmCode		COD_MOD,
		'00'				COD_SIT,
		ODLN.SeriesStr		SER,
		ODLN.Serial			NUM_DOC,
		ODLN.U_chaveacesso	CHV_NFE,
		ODLN.TaxDate		DT_EMIS,
		ODLN.DocDate		DT_DOC,
		DLN1.Usage			COD_NAT,
		OUSG.U_CVA_ICMS		COP,
		ODLN.DocNum			NUM_LCTO,
		CASE WHEN ODLN.Installmnt = 1
			THEN 0
			ELSE 1
		END					IND_PGTO,
		ODLN.DocTotal		VL_CONT,
		ISS.BaseSum			VL_OP_ISS,
		ICMS.BaseSum		VL_BC_ICMS,
		ICMS.TaxSum			VL_ICMS,
		ICMS_ST.TaxSum		VL_ICMS_ST,
		CASE WHEN DLN1.CFOPCode LIKE '1%' OR DLN1.CFOPCode LIKE '2%' OR DLN1.CFOPCode LIKE '3%' 
			THEN ICMS_ST.TaxSum
			ELSE 0.00
		END VL_ST_E,
		CASE WHEN DLN1.CFOPCode LIKE '1%' OR DLN1.CFOPCode LIKE '2%' OR DLN1.CFOPCode LIKE '3%' 
			THEN 0.00
			ELSE ICMS_ST.TaxSum
		END VL_ST_S,
		ICMS_ST.TaxSum		VL_AT,
		ICMS.Isentas		VL_ISNT_ICMS,
		ICMS.Outras			VL_OUT_ICMS,
		IPI.BaseSum			VL_BC_IPI,
		IPI.TaxSum			VL_IPI,
		IPI.Isentas			VL_ISNT_IPI,
		IPI.Outras			VL_OUT_IPI,
		''					COD_INF_OBS
	FROM ODLN WITH(NOLOCK)
		INNER JOIN DLN1 WITH(NOLOCK)
			ON DLN1.DocEntry = ODLN.DocEntry
		INNER JOIN ONFM WITH(NOLOCK)
			ON ONFM.AbsEntry = ODLN.Model
		INNER JOIN OUSG WITH(NOLOCK)
			ON OUSG.Id = DLN1.Usage
		LEFT JOIN (SELECT FRETE.DocEntry, SUM(FRETE.LineTotal) ValorFrete FROM DLN3 FRETE WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON FRETE.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%FRETE%' GROUP BY FRETE.DocEntry) FRETE
			ON FRETE.DocEntry = ODLN.DocEntry
		LEFT JOIN (SELECT SEGURO.DocEntry, SUM(SEGURO.LineTotal) ValorSeguro FROM DLN3 SEGURO WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON SEGURO.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%SEGURO%' GROUP BY SEGURO.DocEntry) SEGURO
			ON SEGURO.DocEntry = ODLN.DocEntry
		LEFT JOIN (SELECT OUTROS.DocEntry, SUM(OUTROS.LineTotal) ValorOutrasDespesas FROM DLN3 OUTROS WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON OUTROS.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName NOT LIKE '%FRETE%' AND OEXD.ExpnsName NOT LIKE '%SEGURO%' GROUP BY OUTROS.DocEntry) OUTROS
			ON OUTROS.DocEntry = ODLN.DocEntry
		LEFT JOIN (
					SELECT DLN4.DocEntry, SUM(DLN4.TaxSum) TaxSum, SUM(DLN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
					FROM DLN4 WITH(NOLOCK) 
						INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = DLN4.StaType
						INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code IN ('ISS', 'ISSQN')
					GROUP BY DLN4.DocEntry
				) ISS
			ON ISS.DocEntry = DLN1.DocEntry
		LEFT JOIN (
				SELECT DLN4.DocEntry,SUM(DLN4.TaxSum) TaxSum, SUM(DLN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
				FROM DLN4 WITH(NOLOCK) 
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = DLN4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS'
				GROUP BY DLN4.DocEntry
			) ICMS
			ON ICMS.DocEntry = DLN1.DocEntry
		LEFT JOIN (
			SELECT DLN4.DocEntry, SUM(DLN4.TaxSum) TaxSum, SUM(DLN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM DLN4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = DLN4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY DLN4.DocEntry
		) ICMS_ST
			ON ICMS_ST.DocEntry = DLN1.DocEntry
		LEFT JOIN (
			SELECT DLN4.DocEntry, SUM(DLN4.TaxSum) TaxSum, SUM(DLN4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM DLN4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = DLN4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'IPI'
			GROUP BY DLN4.DocEntry
		) IPI
			ON IPI.DocEntry = DLN1.DocEntry
	WHERE ODLN.DocDate BETWEEN @DataInicial AND @DataFinal
	AND ODLN.BPLId = @Filial
	AND ISNULL(DLN1.TargetType, 0) <> 13
	AND ODLN.CANCELED = 'N' AND Model IN (1, 3, 5, 39)

	UNION ALL 


		SELECT DISTINCT
		OINV.DocEntry,
		OINV.ObjType,
		CASE WHEN INV1.CFOPCode LIKE '1%' OR INV1.CFOPCode LIKE '2%' OR INV1.CFOPCode LIKE '3%' 
			THEN 0
			ELSE 1
		END					IND_OPER,
		0					IND_EMIT,
		OINV.CardCode		COD_PART,
		ONFM.NfmCode		COD_MOD,
		'00'				COD_SIT,
		OINV.SeriesStr		SER,
		OINV.Serial			NUM_DOC,
		OINV.U_chaveacesso	CHV_NFE,
		OINV.TaxDate		DT_EMIS,
		OINV.DocDate		DT_DOC,
		INV1.Usage			COD_NAT,
		OUSG.U_CVA_ICMS		COP,
		OINV.DocNum			NUM_LCTO,
		CASE WHEN OINV.Installmnt = 1
			THEN 0
			ELSE 1
		END					IND_PGTO,
		OINV.DocTotal		VL_CONT,
		ISS.BaseSum			VL_OP_ISS,
		ICMS.BaseSum		VL_BC_ICMS,
		ICMS.TaxSum			VL_ICMS,
		ICMS_ST.TaxSum		VL_ICMS_ST,
		CASE WHEN INV1.CFOPCode LIKE '1%' OR INV1.CFOPCode LIKE '2%' OR INV1.CFOPCode LIKE '3%' 
			THEN ICMS_ST.TaxSum
			ELSE 0.00
		END VL_ST_E,
		CASE WHEN INV1.CFOPCode LIKE '1%' OR INV1.CFOPCode LIKE '2%' OR INV1.CFOPCode LIKE '3%' 
			THEN 0.00
			ELSE ICMS_ST.TaxSum
		END VL_ST_S,
		ICMS_ST.TaxSum		VL_AT,
		ICMS.Isentas		VL_ISNT_ICMS,
		ICMS.Outras			VL_OUT_ICMS,
		IPI.BaseSum			VL_BC_IPI,
		IPI.TaxSum			VL_IPI,
		IPI.Isentas			VL_ISNT_IPI,
		IPI.Outras			VL_OUT_IPI,
		''					COD_INF_OBS
	FROM OINV WITH(NOLOCK)
		INNER JOIN INV1 WITH(NOLOCK)
			ON INV1.DocEntry = OINV.DocEntry
		INNER JOIN ONFM WITH(NOLOCK)
			ON ONFM.AbsEntry = OINV.Model
		INNER JOIN OUSG WITH(NOLOCK)
			ON OUSG.Id = INV1.Usage
		LEFT JOIN (SELECT FRETE.DocEntry, SUM(FRETE.LineTotal) ValorFrete FROM INV3 FRETE WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON FRETE.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%FRETE%' GROUP BY FRETE.DocEntry) FRETE
			ON FRETE.DocEntry = OINV.DocEntry
		LEFT JOIN (SELECT SEGURO.DocEntry, SUM(SEGURO.LineTotal) ValorSeguro FROM INV3 SEGURO WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON SEGURO.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%SEGURO%' GROUP BY SEGURO.DocEntry) SEGURO
			ON SEGURO.DocEntry = OINV.DocEntry
		LEFT JOIN (SELECT OUTROS.DocEntry, SUM(OUTROS.LineTotal) ValorOutrasDespesas FROM INV3 OUTROS WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON OUTROS.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName NOT LIKE '%FRETE%' AND OEXD.ExpnsName NOT LIKE '%SEGURO%' GROUP BY OUTROS.DocEntry) OUTROS
			ON OUTROS.DocEntry = OINV.DocEntry
		LEFT JOIN (
					SELECT INV4.DocEntry, SUM(INV4.TaxSum) TaxSum, SUM(INV4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
					FROM INV4 WITH(NOLOCK) 
						INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = INV4.StaType
						INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code IN ('ISS', 'ISSQN')
					GROUP BY INV4.DocEntry
				) ISS
			ON ISS.DocEntry = INV1.DocEntry
		LEFT JOIN (
				SELECT INV4.DocEntry,SUM(INV4.TaxSum) TaxSum, SUM(INV4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
				FROM INV4 WITH(NOLOCK) 
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = INV4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS'
				GROUP BY INV4.DocEntry
			) ICMS
			ON ICMS.DocEntry = INV1.DocEntry
		LEFT JOIN (
			SELECT INV4.DocEntry,SUM(INV4.TaxSum) TaxSum, SUM(INV4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM INV4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = INV4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY INV4.DocEntry
		) ICMS_ST
			ON ICMS_ST.DocEntry = INV1.DocEntry
		LEFT JOIN (
			SELECT INV4.DocEntry,SUM(INV4.TaxSum) TaxSum, SUM(INV4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM INV4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = INV4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'IPI'
			GROUP BY INV4.DocEntry
		) IPI
			ON IPI.DocEntry = INV1.DocEntry
	WHERE OINV.DocDate BETWEEN @DataInicial AND @DataFinal
	AND OINV.BPLId = @Filial
	AND OINV.CANCELED = 'N' AND Model IN (1, 3, 5, 39)

	UNION ALL 

		SELECT 
		ORPD.DocEntry,
		ORPD.ObjType,
		CASE WHEN RPD1.CFOPCode LIKE '1%' OR RPD1.CFOPCode LIKE '2%' OR RPD1.CFOPCode LIKE '3%' 
			THEN 0
			ELSE 1
		END					IND_OPER,
		0					IND_EMIT,
		ORPD.CardCode		COD_PART,
		ONFM.NfmCode		COD_MOD,
		'00'				COD_SIT,
		ORPD.SeriesStr		SER,
		ORPD.Serial			NUM_DOC,
		ORPD.U_chaveacesso	CHV_NFE,
		ORPD.TaxDate		DT_EMIS,
		ORPD.DocDate		DT_DOC,
		RPD1.Usage			COD_NAT,
		OUSG.U_CVA_ICMS		COP,
		ORPD.DocNum			NUM_LCTO,
		CASE WHEN ORPD.Installmnt = 1
			THEN 0
			ELSE 1
		END					IND_PGTO,
		ORPD.DocTotal		VL_CONT,
		ISS.BaseSum			VL_OP_ISS,
		ICMS.BaseSum		VL_BC_ICMS,
		ICMS.TaxSum			VL_ICMS,
		ICMS_ST.TaxSum		VL_ICMS_ST,
		CASE WHEN RPD1.CFOPCode LIKE '1%' OR RPD1.CFOPCode LIKE '2%' OR RPD1.CFOPCode LIKE '3%' 
			THEN ICMS_ST.TaxSum
			ELSE 0.00
		END VL_ST_E,
		CASE WHEN RPD1.CFOPCode LIKE '1%' OR RPD1.CFOPCode LIKE '2%' OR RPD1.CFOPCode LIKE '3%' 
			THEN 0.00
			ELSE ICMS_ST.TaxSum
		END VL_ST_S,
		ICMS_ST.TaxSum		VL_AT,
		ICMS.Isentas		VL_ISNT_ICMS,
		ICMS.Outras			VL_OUT_ICMS,
		IPI.BaseSum			VL_BC_IPI,
		IPI.TaxSum			VL_IPI,
		IPI.Isentas			VL_ISNT_IPI,
		IPI.Outras			VL_OUT_IPI,
		''					COD_INF_OBS
	FROM ORPD WITH(NOLOCK)
		INNER JOIN RPD1 WITH(NOLOCK)
			ON RPD1.DocEntry = ORPD.DocEntry
		INNER JOIN ONFM WITH(NOLOCK)
			ON ONFM.AbsEntry = ORPD.Model
		INNER JOIN OUSG WITH(NOLOCK)
			ON OUSG.Id = RPD1.Usage
		LEFT JOIN (SELECT FRETE.DocEntry, SUM(FRETE.LineTotal) ValorFrete FROM RPD3 FRETE WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON FRETE.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%FRETE%' GROUP BY FRETE.DocEntry) FRETE
			ON FRETE.DocEntry = ORPD.DocEntry
		LEFT JOIN (SELECT SEGURO.DocEntry, SUM(SEGURO.LineTotal) ValorSeguro FROM RPD3 SEGURO WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON SEGURO.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%SEGURO%' GROUP BY SEGURO.DocEntry) SEGURO
			ON SEGURO.DocEntry = ORPD.DocEntry
		LEFT JOIN (SELECT OUTROS.DocEntry, SUM(OUTROS.LineTotal) ValorOutrasDespesas FROM RPD3 OUTROS WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON OUTROS.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName NOT LIKE '%FRETE%' AND OEXD.ExpnsName NOT LIKE '%SEGURO%' GROUP BY OUTROS.DocEntry) OUTROS
			ON OUTROS.DocEntry = ORPD.DocEntry
		LEFT JOIN (
					SELECT RPD4.DocEntry, SUM(RPD4.TaxSum) TaxSum, SUM(RPD4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
					FROM RPD4 WITH(NOLOCK) 
						INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RPD4.StaType
						INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code IN ('ISS', 'ISSQN')
					GROUP BY RPD4.DocEntry
				) ISS
			ON ISS.DocEntry = RPD1.DocEntry
		LEFT JOIN (
				SELECT RPD4.DocEntry, SUM(RPD4.TaxSum) TaxSum, SUM(RPD4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
				FROM RPD4 WITH(NOLOCK) 
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RPD4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS'
				GROUP BY RPD4.DocEntry
			) ICMS
			ON ICMS.DocEntry = RPD1.DocEntry
		LEFT JOIN (
			SELECT RPD4.DocEntry, SUM(RPD4.TaxSum) TaxSum, SUM(RPD4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM RPD4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RPD4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY RPD4.DocEntry
		) ICMS_ST
			ON ICMS_ST.DocEntry = RPD1.DocEntry

		LEFT JOIN (
			SELECT RPD4.DocEntry, SUM(RPD4.TaxSum) TaxSum, SUM(RPD4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM RPD4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RPD4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'IPI'
			GROUP BY RPD4.DocEntry
		) IPI
			ON IPI.DocEntry = RPD1.DocEntry
	WHERE ORPD.DocDate BETWEEN @DataInicial AND @DataFinal
	AND ORPD.BPLId = @Filial
	AND ORPD.CANCELED = 'N' AND Model IN (1, 3, 5, 39)

	UNION ALL 

		SELECT DISTINCT
		ORPC.DocEntry,
		ORPC.ObjType,
		CASE WHEN RPC1.CFOPCode LIKE '1%' OR RPC1.CFOPCode LIKE '2%' OR RPC1.CFOPCode LIKE '3%' 
			THEN 0
			ELSE 1
		END					IND_OPER,
		0					IND_EMIT,
		ORPC.CardCode		COD_PART,
		ONFM.NfmCode		COD_MOD,
		'00'				COD_SIT,
		ORPC.SeriesStr		SER,
		ORPC.Serial			NUM_DOC,
		ORPC.U_chaveacesso	CHV_NFE,
		ORPC.TaxDate		DT_EMIS,
		ORPC.DocDate		DT_DOC,
		RPC1.Usage			COD_NAT,
		OUSG.U_CVA_ICMS		COP,
		ORPC.DocNum			NUM_LCTO,
		CASE WHEN ORPC.Installmnt = 1
			THEN 0
			ELSE 1
		END					IND_PGTO,
		ORPC.DocTotal		VL_CONT,
		ISS.BaseSum			VL_OP_ISS,
		ICMS.BaseSum		VL_BC_ICMS,
		ICMS.TaxSum			VL_ICMS,
		ICMS_ST.TaxSum		VL_ICMS_ST,
		CASE WHEN RPC1.CFOPCode LIKE '1%' OR RPC1.CFOPCode LIKE '2%' OR RPC1.CFOPCode LIKE '3%' 
			THEN ICMS_ST.TaxSum
			ELSE 0.00
		END VL_ST_E,
		CASE WHEN RPC1.CFOPCode LIKE '1%' OR RPC1.CFOPCode LIKE '2%' OR RPC1.CFOPCode LIKE '3%' 
			THEN 0.00
			ELSE ICMS_ST.TaxSum
		END VL_ST_S,
		ICMS_ST.TaxSum		VL_AT,
		ICMS.Isentas		VL_ISNT_ICMS,
		ICMS.Outras			VL_OUT_ICMS,
		IPI.BaseSum			VL_BC_IPI,
		IPI.TaxSum			VL_IPI,
		IPI.Isentas			VL_ISNT_IPI,
		IPI.Outras			VL_OUT_IPI,
		''					COD_INF_OBS
	FROM ORPC WITH(NOLOCK)
		INNER JOIN RPC1 WITH(NOLOCK)
			ON RPC1.DocEntry = ORPC.DocEntry
		INNER JOIN ONFM WITH(NOLOCK)
			ON ONFM.AbsEntry = ORPC.Model
		INNER JOIN OUSG WITH(NOLOCK)
			ON OUSG.Id = RPC1.Usage
		LEFT JOIN (SELECT FRETE.DocEntry, SUM(FRETE.LineTotal) ValorFrete FROM RPC3 FRETE WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON FRETE.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%FRETE%' GROUP BY FRETE.DocEntry) FRETE
			ON FRETE.DocEntry = ORPC.DocEntry
		LEFT JOIN (SELECT SEGURO.DocEntry, SUM(SEGURO.LineTotal) ValorSeguro FROM RPC3 SEGURO WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON SEGURO.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName LIKE '%SEGURO%' GROUP BY SEGURO.DocEntry) SEGURO
			ON SEGURO.DocEntry = ORPC.DocEntry
		LEFT JOIN (SELECT OUTROS.DocEntry, SUM(OUTROS.LineTotal) ValorOutrasDespesas FROM RPC3 OUTROS WITH(NOLOCK) INNER JOIN OEXD WITH(NOLOCK) ON OUTROS.ExpnsCode = OEXD.ExpnsCode AND OEXD.ExpnsName NOT LIKE '%FRETE%' AND OEXD.ExpnsName NOT LIKE '%SEGURO%' GROUP BY OUTROS.DocEntry) OUTROS
			ON OUTROS.DocEntry = ORPC.DocEntry
		LEFT JOIN (
					SELECT RPC4.DocEntry,SUM(RPC4.TaxSum) TaxSum, SUM(RPC4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
					FROM RPC4 WITH(NOLOCK) 
						INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RPC4.StaType
						INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code IN ('ISS', 'ISSQN')
					GROUP BY RPC4.DocEntry
				) ISS
			ON ISS.DocEntry = RPC1.DocEntry

		LEFT JOIN (
				SELECT RPC4.DocEntry,SUM(RPC4.TaxSum) TaxSum, SUM(RPC4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
				FROM RPC4 WITH(NOLOCK) 
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RPC4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS'
				GROUP BY RPC4.DocEntry
			) ICMS
			ON ICMS.DocEntry = RPC1.DocEntry
		LEFT JOIN (
			SELECT RPC4.DocEntry,  SUM(RPC4.TaxSum) TaxSum, SUM(RPC4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM RPC4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RPC4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
			GROUP BY RPC4.DocEntry
		) ICMS_ST
			ON ICMS_ST.DocEntry = RPC1.DocEntry
		LEFT JOIN (
			SELECT RPC4.DocEntry, SUM(RPC4.TaxSum) TaxSum, SUM(RPC4.BaseSum) BaseSum, SUM(U_ExcAmtS) Isentas, SUM(U_OthAmtS) Outras
			FROM RPC4 WITH(NOLOCK) 
				INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RPC4.StaType
				INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'IPI'
			GROUP BY RPC4.DocEntry
		) IPI
			ON IPI.DocEntry = RPC1.DocEntry
	WHERE ORPC.DocDate BETWEEN @DataInicial AND @DataFinal
	AND ORPC.BPLId = @Filial
	AND ORPC.CANCELED = 'N' AND Model IN (1, 3, 5, 39)
)
