IF EXISTS (SELECT * FROM sys.objects WHERE type = 'IF' AND name = 'FN_CVA_SEF_E001')
	DROP FUNCTION FN_CVA_SEF_E001
GO
CREATE FUNCTION FN_CVA_SEF_E001
(
	@Filial			INT,
	@DataInicial	DATETIME,
	@DataFinal		DATETIME
) RETURNS TABLE
AS
RETURN
(
	SELECT '0' IND_DAD
)
