IF EXISTS (SELECT * FROM sys.objects WHERE type = 'IF' AND name = 'FN_CVA_SEF_E350')
	DROP FUNCTION FN_CVA_SEF_E350
GO
CREATE FUNCTION FN_CVA_SEF_E350
(
	@Filial			INT,
	@DataInicial	DATETIME,
	@DataFinal		DATETIME
) RETURNS TABLE
AS
RETURN
(
	SELECT
		0.00	UF_AJ,
		0.00	COD_AJ,
		0.00	VL_AJ,
		0.00	NUM_DA,
		0.00	NUM_PROC,
		0.00	IND_PROC,
		0.00	DESCR_PROC,
		0.00	COD_INF_OBS,
		0.00	IND_AP
)
