IF EXISTS (SELECT * FROM sys.objects WHERE type = 'IF' AND name = 'FN_CVA_SEF_E300')
	DROP FUNCTION FN_CVA_SEF_E300
GO
CREATE FUNCTION FN_CVA_SEF_E300
(
	@Filial			INT,
	@DataInicial	DATETIME,
	@DataFinal		DATETIME
) RETURNS TABLE
AS
RETURN
(
	SELECT @DataFinal DT_INI, @DataFinal DT_FIN
)
