IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SEF_9900')
	DROP PROCEDURE SP_CVA_SEF_9900
GO

-- exec SP_CVA_SEF_9900 1, '2018-01-01', '2018-31-01'
CREATE PROCEDURE SP_CVA_SEF_9900
(
	@Filial			INT,
	@DataDe			DATETIME,
	@DataAte		DATETIME
)
AS
BEGIN
	CREATE TABLE #ROWCOUNT
	(
		LIN_BLC		VARCHAR(10),
		QTD_LIN_BLC	INT
	)

	INSERT INTO #ROWCOUNT
	SELECT '0000', COUNT(*) FROM FN_CVA_SEF_0000 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT '0001', COUNT(*) FROM FN_CVA_SEF_0001 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT '0030', COUNT(*) FROM FN_CVA_SEF_0030 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT '0100', COUNT(*) FROM FN_CVA_SEF_0100 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT '0150', COUNT(*) FROM FN_CVA_SEF_0150 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT '0400', COUNT(*) FROM FN_CVA_SEF_0400 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT '0450', COUNT(*) FROM FN_CVA_SEF_0450 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT '0990', 1

	INSERT INTO #ROWCOUNT
	SELECT 'E001', COUNT(*) FROM FN_CVA_SEF_E001 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E020', COUNT(*) FROM FN_CVA_SEF_E020 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E300', COUNT(*) FROM FN_CVA_SEF_E300 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E310', COUNT(*) FROM FN_CVA_SEF_E310 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E330', COUNT(*) FROM FN_CVA_SEF_E330 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E340', COUNT(*) FROM FN_CVA_SEF_E340 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E350', COUNT(*) FROM FN_CVA_SEF_E350 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E360', COUNT(*) FROM FN_CVA_SEF_E360 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E500', COUNT(*) FROM FN_CVA_SEF_E500 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E520', COUNT(*) FROM FN_CVA_SEF_E520 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E525', COUNT(*) FROM FN_CVA_SEF_E525 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E540', COUNT(*) FROM FN_CVA_SEF_E540 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E560', COUNT(*) FROM FN_CVA_SEF_E560 (@Filial, @DataDe, @DataAte)

	INSERT INTO #ROWCOUNT
	SELECT 'E990', 1

	INSERT INTO #ROWCOUNT
	SELECT '9001', 1

	INSERT INTO #ROWCOUNT
	SELECT '9990', 1

	INSERT INTO #ROWCOUNT
	SELECT '9999', 1

	INSERT INTO #ROWCOUNT
	SELECT '9900', COUNT(*) FROM #ROWCOUNT

	SELECT * FROM #ROWCOUNT

	DROP TABLE #ROWCOUNT
END