IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_SEF_9999')
	DROP PROCEDURE SP_CVA_SEF_9999
GO

-- exec SP_CVA_SEF_9999 1, '2018-01-01', '2018-31-01'
CREATE PROCEDURE SP_CVA_SEF_9999
(
	@Filial			INT,
	@DataDe			DATETIME,
	@DataAte		DATETIME
)
AS
BEGIN
	CREATE TABLE #ROWCOUNT
	(
		LIN_BLC		VARCHAR(10),
		QTD_LIN_BLC	INT
	)

	INSERT INTO #ROWCOUNT
	EXEC SP_CVA_SEF_9900 @Filial, @DataDe, @DataAte
	
	SELECT SUM(QTD_LIN_BLC) QTD_LIN FROM #ROWCOUNT

	DROP TABLE #ROWCOUNT
END