DECLARE @SQL NVARCHAR(MAX)
DECLARE @Base NVARCHAR(MAX)
DECLARE @NumPedido INT

CREATE TABLE #TB_AUX
(
	BASE NVARCHAR(MAX) COLLATE DATABASE_DEFAULT,
	NumPedido INT,
	PN NVARCHAR(MAX) COLLATE DATABASE_DEFAULT,
	Valor NUMERIC(19,6),
	[Status] NVARCHAR(MAX) COLLATE DATABASE_DEFAULT,
	[Log] NVARCHAR(MAX) COLLATE DATABASE_DEFAULT
)

DECLARE mycur CURSOR FORWARD_ONLY FOR
SELECT U_BASE FROM [@CVA_IMP_PED1] GROUP BY U_BASE

OPEN mycur
FETCH NEXT FROM mycur INTO @BASE

WHILE @@FETCH_STATUS = 0
BEGIN
	SET @SQL = N'SELECT U_BASE, U_NUMSAP, U_PN, U_VALOR, ''Pedido Cancelado'', U_LOG FROM [@CVA_IMP_PED1] PED
		INNER JOIN [' + @BASE + '].[dbo].OPOR ON DocEntry = PED.U_NUMSAP AND OPOR.CANCELED = ''Y''
		WHERE PED.U_Base = ''' + @Base + ''''

	INSERT INTO #TB_AUX
	EXEC sp_executesql @SQL

	SET @SQL = N'SELECT U_BASE, U_NUMSAP, U_PN, U_VALOR, ''Nota já gerada'', U_LOG FROM [@CVA_IMP_PED1] PED
		INNER JOIN [' + @BASE + '].[dbo].OPOR ON OPOR.DocEntry = PED.U_NUMSAP
		INNER JOIN [' + @BASE + '].[dbo].PCH1 ON PCH1.BaseEntry = OPOR.DocEntry AND PCH1.BaseType = OPOR.ObjType
		WHERE PED.U_STATUS <> 3
		AND PED.U_Base = ''' + @Base + ''''

	INSERT INTO #TB_AUX
	EXEC sp_executesql @SQL

	FETCH NEXT FROM mycur INTO @BASE
END
	
CLOSE mycur
DEALLOCATE mycur

UPDATE PED 
SET U_LOG = 'NF Gerada com sucesso!',
U_STATUS = 3
FROM [@CVA_IMP_PED1] PED
	INNER JOIN #TB_AUX AUX
		ON AUX.NumPedido = PED.U_NUMSAP
		AND AUX.BASE = PED.U_BASE
WHERE [Status] = 'Nota já gerada'

DELETE PED FROM [@CVA_IMP_PED1] PED
	INNER JOIN #TB_AUX AUX
		ON AUX.NumPedido = PED.U_NUMSAP
		AND AUX.BASE = PED.U_BASE

SELECT * FROM #TB_AUX

DROP TABLE #TB_AUX