//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Core.TransportLCM.SERVICE.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.Core.TransportLCM.SERVICE.Resource.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT BPLName FROM OBPL WHERE BPLId = {0}.
        /// </summary>
        internal static string Branch_GetNameById {
            get {
                return ResourceManager.GetString("Branch_GetNameById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT E_MailL Email FROM OCPR WHERE CardCode = &apos;{0}&apos;.
        /// </summary>
        internal static string BusinessPartnerContact_GetEmail {
            get {
                return ResourceManager.GetString("BusinessPartnerContact_GetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	U_Tipo		&apos;Tipo&apos;,
        ///	U_Servidor	&apos;Servidor&apos;,
        ///	U_Banco		&apos;Banco&apos;,
        ///	U_Usuario	&apos;Usuario&apos;,
        ///	U_Senha		&apos;Senha&apos;
        ///FROM [@CVA_CONFIG_DB] 
        ///WHERE U_Tipo = {0}.
        /// </summary>
        internal static string Config_Get {
            get {
                return ResourceManager.GetString("Config_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AcctCode Conta, AcctName Nome FROM OACT WHERE Postable = &apos;Y&apos; AND LocManTran = &apos;N&apos;
        ///UNION
        ///SELECT CardCode Conta, CardName Nome FROM OCRD WHERE frozenFor = &apos;N&apos;.
        /// </summary>
        internal static string Conta_GetAll {
            get {
                return ResourceManager.GetString("Conta_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID, CODE, NAME FROM [CVA_ATL_PORTAL].[dbo].[CVA_QUF] WHERE [TYPE] = &apos;A&apos;.
        /// </summary>
        internal static string Conta_GetQUF {
            get {
                return ResourceManager.GetString("Conta_GetQUF", resourceCulture);
            }
        }
    }
}
