'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace AddOnInstaller

    Public Class AddOnInstallInfo

        Public StrAddOnInstallPath As String

        Public AddOnName As String

        Public PartnerName As String

        Public ExeFile As String

        Public DIFile As String

        Public UIFile As String

        Public B1WizardBaseFile As String

        Public ExtraFiles As System.String()

        Public ExtraDirectories As System.String()

        Public RestartNeeded As Boolean

        Public Sub New()
            MyBase.New
            'INITIALIZATION CODE	...
            AddOnName = "SAP AddOn Observações Fiscal"
            PartnerName = "CVA"
            RestartNeeded = False
            ExeFile = "CVA.View.DIME.AddOn.exe"
            DIFile = "Interop.SAPbobsCOM.dll"
            UIFile = "Interop.SAPbouiCOM.dll"
            B1WizardBaseFile = ""
            ExtraFiles = New String() {
                "DIME.xlsx",
                "f5010.srf",
                "f5011.srf",
                "f5012.srf",
                "f5013.srf",
                "ClosedXML.dll",
                "ClosedXML.xml",
                "ConverterLib.dll",
                "CVA.AddOn.Common.dll",
                "CVA.AddOn.Common.dll.config",
                "CVA.View.DIME.AddOn.exe.config",
                "CVA.View.DIME.dll",
                "DocumentFormat.OpenXml.dll",
                "DocumentFormat.OpenXml.xml",
                "ExcelNumberFormat.dll",
                "ExcelNumberFormat.xml",
                "FastMember.Signed.dll",
                "Menu.xml",
                "Microsoft.Office.Interop.Word.xml",
                "office.xml"
            }
            ExtraDirectories = New String() {
                "Layout",
                "srfFiles",
                "srfFiles",
                "srfFiles",
                "srfFiles",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                ""
            }
        End Sub
    End Class
End Namespace
