CREATE PROCEDURE SP_CVA_GET_DETALHES_ITEM
(@ItemCode varchar(100))
AS

SELECT 
	CAST(ISNULL(OITM.UserText, '') AS NVARCHAR(MAX)) + ' ' + 
	CAST(ISNULL(OITM.U_EASY_REGISTRO_MAPA, '') AS NVARCHAR(MAX)) + ' ' + 
	CAST(ISNULL(OITM.U_EASY_GARANTIA_PRD, '') AS NVARCHAR(MAX)) + ' ' + 
	CAST(ISNULL(OITM.U_EASY_TipoP, '') AS NVARCHAR(MAX)) + ' ' + 
	CAST(ISNULL(OITM.U_EASY_NAT_FISICA, '') AS NVARCHAR(MAX))
FROM OITM
WHERE ItemCode = @ItemCode
