//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Hybel.Monitor.IntegSkaSap.DAO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.Hybel.Monitor.IntegSkaSap.DAO.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///	PROD.ID,
        ///	PROD.OP,
        ///	CASE TLOG.[TYPE]
        ///		WHEN 0 THEN &apos;Registro de Tempo&apos;
        ///		WHEN 1 THEN &apos;Consumo&apos;
        ///		WHEN 3 THEN &apos;Produto Acabado&apos;
        ///	END	AS TIPO,
        ///	CASE TLOG.[Status]
        ///		WHEN 0 THEN &apos;Aguardando Processamento&apos;
        ///		WHEN 1 THEN &apos;Em Processamento&apos;
        ///		WHEN 2 THEN &apos;Importado com Sucesso&apos;
        ///		WHEN 3 THEN &apos;Qtde. Estoque Insuficiente&apos;
        ///		WHEN 4 THEN &apos;Itens com Posições Inválidas&apos;
        ///		WHEN 5 THEN &apos;Sem Consumo de Material&apos;
        ///		WHEN 6 THEN &apos;Gerar Produto Acabado&apos;
        ///		WHEN 7 THEN &apos;Quantidade Zerada no Cons [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Integracao_Get {
            get {
                return ResourceManager.GetString("Integracao_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE {0}.[dbo].SSPExportProd_Log SET [Status] = 0 WHERE ID = {1}.
        /// </summary>
        internal static string Integracao_UpdateStatus {
            get {
                return ResourceManager.GetString("Integracao_UpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND &apos;{0}&apos; = 
        ///	CASE WHEN PROD.[STATUS] = 0
        ///		THEN &apos;Pendente&apos;
        ///		ELSE CASE WHEN ISNULL(TLOG.Description, &apos;&apos;) &lt;&gt; &apos;&apos; AND PROD.[STATUS] &lt;&gt; 5
        ///			THEN &apos;Erro&apos;
        ///			ELSE &apos;Integrado&apos;
        ///		END
        ///	END.
        /// </summary>
        internal static string Integracao_WhereStatus {
            get {
                return ResourceManager.GetString("Integracao_WhereStatus", resourceCulture);
            }
        }
    }
}
