//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Core.ControlCommon.MODEL.CVACommon
{
    using HELPER;
    using System;
    using System.Collections.Generic;

    public partial class Registro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registro()
        {
            this.CVA_REG_LOG = new HashSet<RegistroLog>();
        }

        public int ID { get; set; }

        [ModelHelper(ColumnName = "INS")]
        public System.DateTime Insert { get; set; }

        [ModelHelper(ColumnName = "UPD")]
        public Nullable<System.DateTime> Update { get; set; }

        [ModelHelper(ColumnName = "STU")]
        public Nullable<int> Status { get; set; }

        [ModelHelper(ColumnName = "BAS")]
        public Nullable<int> CodigoBase { get; set; }

        [ModelHelper(ColumnName = "CODE")]
        public string Codigo { get; set; }

        [ModelHelper(ColumnName = "OBJ")]
        public Nullable<int> Objeto { get; set; }

        [ModelHelper(ColumnName = "FUNC")]
        public Nullable<int> Funcao { get; set; }

        [ModelHelper(ColumnName = "BAS_ERR")]
        public Nullable<int> BaseErro { get; set; }
    
        public virtual Base CVA_BAS { get; set; }
        public virtual Base CVA_BAS1 { get; set; }
        public virtual Funcao CVA_FUNC { get; set; }
        public virtual Objeto CVA_OBJ { get; set; }
        public virtual Status CVA_STU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroLog> CVA_REG_LOG { get; set; }
    }
}
