IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_GIA_ST_DEV')
	DROP PROCEDURE SP_CVA_GIA_ST_DEV
GO
CREATE PROCEDURE SP_CVA_GIA_ST_DEV
(
	@DocKey NVARCHAR(30)
)
AS
BEGIN
	SELECT 
		OBPL.BPLName,
		OBPL.TaxIdNum2	IE_Filial,
		GIAST.U_DtDe	DateDe,
		GIAST.U_UF		UF,
		CRD7.TaxId1		IE,
		ORIN.Serial,
		ORIN.SeriesStr,
		ORIN.DocDate,
		SUM(ICMSDest.TaxSum)		TaxSum
	FROM [@CVA_GIA_ST] GIAST WITH(NOLOCK)
		INNER JOIN OBPL WITH(NOLOCK)
			ON OBPL.BPLId = GIAST.U_Filial
		INNER JOIN RIN12 WITH(NOLOCK)
			ON RIN12.[State] = GIAST.U_UF
		INNER JOIN ORIN WITH(NOLOCK)
			ON ORIN.BPLId = GIAST.U_Filial 
			AND ORIN.DocDate BETWEEN GIAST.U_DtDe AND GIAST.U_DtAte
			AND ORIN.CANCELED = 'N'
		CROSS APPLY 
			(
				SELECT TOP 1 * FROM CRD7 WITH (NOLOCK)
				WHERE CRD7.CardCode = ORIN.CardCode
				AND ISNULL(CRD7.TaxId0, '') <> ''
				AND ISNULL(CRD7.Address, '') <> ''
			) AS CRD7
		INNER JOIN RIN1 WITH(NOLOCK)
			ON RIN1.DocEntry = ORIN.DocEntry
		INNER JOIN (
				SELECT RIN4.DocEntry, RIN4.LineNum, SUM(TaxSum) TaxSum, SUM(BaseSum) BaseSum FROM RIN4 WITH(NOLOCK)
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = RIN4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMS-ST'
				GROUP BY RIN4.DocEntry, RIN4.LineNum
			) ICMSDest
			ON ICMSDest.DocEntry = ORIN.DocEntry
			AND ICMSDest.LineNum = RIN1.LineNum
	GROUP BY
		OBPL.TaxIdNum2,
		GIAST.U_UF,
		GIAST.U_DtDe,
		CRD7.TaxId1,
		OBPL.BPLName,
		ORIN.Serial,
		ORIN.SeriesStr,
		ORIN.DocDate
END