IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SP_CVA_GIA_ST_EC8715')
	DROP PROCEDURE SP_CVA_GIA_ST_EC8715
GO
CREATE PROCEDURE SP_CVA_GIA_ST_EC8715
(
	@DocKey NVARCHAR(30)
)
AS
BEGIN
	SELECT 
		OBPL.BPLName,
		OBPL.TaxIdNum2	IE_Filial,
		GIAST.U_DtVenc	DataVenc,
		GIAST.U_DtDe	DateDe,
		GIAST.U_UF		UF,
		SUM(ICMSDest.TaxSum)	ICMS,
		SUM(FCP.TaxSum)			FCP
	FROM [@CVA_GIA_ST] GIAST WITH(NOLOCK)
		INNER JOIN OBPL WITH(NOLOCK)
			ON OBPL.BPLId = GIAST.U_Filial
		INNER JOIN INV12 WITH(NOLOCK)
			ON INV12.[State] = GIAST.U_UF
		INNER JOIN OINV WITH(NOLOCK)
			ON OINV.BPLId = GIAST.U_Filial 
			AND OINV.DocDate BETWEEN GIAST.U_DtDe AND GIAST.U_DtAte
			AND OINV.CANCELED = 'N'
		INNER JOIN INV1 WITH(NOLOCK)
			ON INV1.DocEntry = OINV.DocEntry
		LEFT JOIN (
				SELECT INV4.DocEntry, INV4.LineNum, SUM(TaxSum) TaxSum, SUM(BaseSum) BaseSum FROM INV4 WITH(NOLOCK)
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = INV4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'ICMSDest'
				GROUP BY INV4.DocEntry, INV4.LineNum
			) ICMSDest
			ON ICMSDest.DocEntry = OINV.DocEntry
			AND ICMSDest.LineNum = INV1.LineNum
		LEFT JOIN (
				SELECT INV4.DocEntry, INV4.LineNum, SUM(TaxSum) TaxSum, SUM(BaseSum) BaseSum FROM INV4 WITH(NOLOCK)
					INNER JOIN OSTT WITH(NOLOCK) ON OSTT.AbsId = INV4.StaType
					INNER JOIN ONFT WITH(NOLOCK) ON ONFT.AbsId = OSTT.NfTaxId AND ONFT.Code = 'FCP'
				GROUP BY INV4.DocEntry, INV4.LineNum
			) FCP
			ON FCP.DocEntry = OINV.DocEntry
	GROUP BY
		OBPL.TaxIdNum2,
		GIAST.U_DtVenc,
		GIAST.U_UF,
		GIAST.U_DtDe,
		OBPL.BPLName
END