//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Cointer.BoePrinter.DAO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hana {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hana() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.Cointer.BoePrinter.DAO.Hana", typeof(Hana).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT BOE.&quot;ID&quot; &quot;IntegrationId&quot;, OINV.&quot;DocNum&quot;, &quot;U_CVA_BancadaConferencia&quot; &quot;Bancada&quot;, &quot;Serial&quot;, &quot;ContractBank&quot;, &quot;OurNumber&quot;, &quot;DateCreate&quot;
        ///FROM &quot;{0}&quot;.OINV
        ///	INNER JOIN &quot;{1}&quot;.&quot;BillOfExchange&quot; BOE
        ///		ON BOE.&quot;DocEntry&quot; = OINV.&quot;DocEntry&quot; AND BOE.&quot;DocType&quot; = 13 AND &quot;CompanyID&quot; = {2}
        ///WHERE IFNULL(BOE.&quot;NumberOfPrints&quot;, &apos;0&apos;) = &apos;0&apos;.
        /// </summary>
        internal static string Boe_GetPending {
            get {
                return ResourceManager.GetString("Boe_GetPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE &quot;{0}&quot;.&quot;BillOfExchange&quot; SET &quot;NumberOfPrints&quot; = &apos;1&apos; WHERE &quot;CompanyID&quot; = {1} AND &quot;DocType&quot; = 13 AND &quot;ID&quot; = {2}.
        /// </summary>
        internal static string Boe_UpdatePrintedStatus {
            get {
                return ResourceManager.GetString("Boe_UpdatePrintedStatus", resourceCulture);
            }
        }
    }
}
