//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.View.ObservacoesFiscais.DAO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.View.ObservacoesFiscais.DAO.Resources.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM OBPL
        ///		WHERE [Disabled] = &apos;N&apos;.
        /// </summary>
        internal static string Branch_Get {
            get {
                return ResourceManager.GetString("Branch_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.Code, T0.Descrip, T0.App FROM OCFP T0.
        /// </summary>
        internal static string CFOP_Get {
            get {
                return ResourceManager.GetString("CFOP_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Name FROM OCNT
        ///		WHERE [State] = $[$mt_Item.cl_UF].
        /// </summary>
        internal static string City_Get {
            get {
                return ResourceManager.GetString("City_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @texto VARCHAR(MAX)
        ///EXEC SP_CVA_ObsAutoNF &apos;{0}&apos;, {1}, @texto output
        ///SELECT @texto.
        /// </summary>
        internal static string Document_GetObservacao {
            get {
                return ResourceManager.GetString("Document_GetObservacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*Pedido de Venda da Nota Fiscal de Saída*/
        ///select distinct top 1
        ///	/*T1.BaseType
        ///	,*/T2.Comments 
        ///from 
        ///	OINV  T0
        ///	inner join INV1 T1 on T1.DocEntry=T0.DocEntry
        ///	inner join ORDR T2 on T2.DocEntry = T1.BaseEntry
        ///where 
        ///	T0.DocEntry={0}
        ///	and T0.ObjType={1}
        ///	and T1.BaseType=17/*Pedido De Venda*/
        ///union all
        ////*Pedido de Venda da Entrega de VEnda*/
        ///select distinct top 1
        ///	/*T1.BaseType
        ///	,*/T2.Comments 
        ///from 
        ///	ODLN T0
        ///	inner join DLN1 T1 on T1.DocEntry=T0.DocEntry
        ///	inner join ORDR T2 on T2.DocEnt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOBSIniciais {
            get {
                return ResourceManager.GetString("GetOBSIniciais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT GroupName FROM OCRG.
        /// </summary>
        internal static string GroupBP_Get {
            get {
                return ResourceManager.GetString("GroupBP_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ItmsGrpNam FROM OITB.
        /// </summary>
        internal static string ItemGroup_Get {
            get {
                return ResourceManager.GetString("ItemGroup_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.NcmCode, T0.Descrip FROM ONCM T0.
        /// </summary>
        internal static string NCM_Get {
            get {
                return ResourceManager.GetString("NCM_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Code, Name FROM OCST.
        /// </summary>
        internal static string State_Get {
            get {
                return ResourceManager.GetString("State_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM OSTC.
        /// </summary>
        internal static string Tax_Get {
            get {
                return ResourceManager.GetString("Tax_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM OUSG.
        /// </summary>
        internal static string Usage_Get {
            get {
                return ResourceManager.GetString("Usage_Get", resourceCulture);
            }
        }
    }
}
