//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Core.DSP.Controle.Resources.Select {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.Core.DSP.Controle.Resources.Select.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select* from[@CVA_MAQ_PARADAS] where code = &apos;{0}&apos;.
        /// </summary>
        internal static string BuscaMaquinaParada {
            get {
                return ResourceManager.GetString("BuscaMaquinaParada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string CarregaGid {
            get {
                return ResourceManager.GetString("CarregaGid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///	T0.U_CVA_Counter AS &apos;Quantity&apos;
        ///	,T0.U_CVA_Tool AS &apos;Tool&apos;
        ///FROM OITM T0
        ///WHERE ItemCode = &apos;{0}&apos;.
        /// </summary>
        internal static string GetCounterToolByItem {
            get {
                return ResourceManager.GetString("GetCounterToolByItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///	T0.ResCode AS Id
        ///	,T0.ResName AS Nome
        ///FROM ORSC T0
        ///WHERE T0.ResCode = (SELECT U_CVA_Tool FROM OITM WHERE ItemCode = &apos;{0}&apos;).
        /// </summary>
        internal static string GetFerramentaItemCode {
            get {
                return ResourceManager.GetString("GetFerramentaItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT ResCode AS Id, ResName AS Nome FROM ORSC T0 WHERE U_CVA_ControlaFerramenta = 1.
        /// </summary>
        internal static string GetFerramentas {
            get {
                return ResourceManager.GetString("GetFerramentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select ResCode ,  ResName from orsc where ResType = &apos;M&apos;.
        /// </summary>
        internal static string GetMaquinas {
            get {
                return ResourceManager.GetString("GetMaquinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select count(code)+1 as &apos;Code&apos;, count(name)+1 as &apos;Name&apos; from [@CVA_MAQ_PARADAS].
        /// </summary>
        internal static string GetMaxValue {
            get {
                return ResourceManager.GetString("GetMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT code, name FROM [@CVA_MOTIVO].
        /// </summary>
        internal static string GetMotivos {
            get {
                return ResourceManager.GetString("GetMotivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select *  from [@CVA_MAQ_PARADAS] where U_Maquina = &apos;{0}&apos;.
        /// </summary>
        internal static string GetMquinaParada {
            get {
                return ResourceManager.GetString("GetMquinaParada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT FIRSTNAME, LASTNAME FROM OHEM.
        /// </summary>
        internal static string GetOperador {
            get {
                return ResourceManager.GetString("GetOperador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT  oitt.Code
        ///       ,oitm.ItemName 
        ///  FROM oitt
        /// INNER JOIN OITM
        ///    ON oitt.Code = oitm.itemcode.
        /// </summary>
        internal static string GetProduto {
            get {
                return ResourceManager.GetString("GetProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT ITT1.Code, Quantity FROM ITT1
        ///	INNER JOIN ORSC
        ///		ON ORSC.ResCode			=	ITT1.Code
        ///		AND ORSC.ObjType		=	ITT1.[Type]
        ///		AND ORSC.U_CVA_Fixed	=	1
        ///WHERE Father = &apos;{0}&apos;.
        /// </summary>
        internal static string GetRecursoValorFixo {
            get {
                return ResourceManager.GetString("GetRecursoValorFixo", resourceCulture);
            }
        }
    }
}
