//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.AddOn.InformacoesNutricionais {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVA.AddOn.InformacoesNutricionais.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select T0.&quot;Code&quot; as &quot;Codigo&quot;
        ///, T0.&quot;Name&quot; as &quot;Nome&quot;
        ///,REPLACE(TO_VARCHAR(TO_DECIMAL((T2.&quot;U_Quantidade&quot;),10,2)),&apos;.&apos;,&apos;,&apos;) as &quot;Quantidade&quot;
        ///,T0.&quot;U_UN&quot; as &quot;Unidade&quot;
        ///,T2.&quot;U_Referencia&quot; as &quot;Referencia&quot;
        ///From &quot;@CVA_NUTRIENTE&quot; T0
        ///Inner Join &quot;@CVA_GRUPONUTRIENTE&quot; T1 On T1.&quot;Code&quot; = T0.&quot;U_GrupoID&quot;
        ///Left Join &quot;@CVA_NUTRIPRODUTO&quot; T2 On T2.&quot;U_NutrienteID&quot; = T0.&quot;Code&quot; And &quot;U_Codigo&quot; = &apos;{1}&apos;
        ///Where T1.&quot;Code&quot; In ({0}) 
        ///Order By 1.
        /// </summary>
        internal static string GetNutrientes {
            get {
                return ResourceManager.GetString("GetNutrientes", resourceCulture);
            }
        }
    }
}
