SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
USE [master]
GO
IF EXISTS(SELECT * FROM sys.databases WHERE name = 'CVA_ATL_REP')
	DROP DATABASE [CVA_ATL_REP]
GO
CREATE DATABASE [CVA_ATL_REP]
GO
USE [CVA_ATL_REP]
GO
IF OBJECT_ID('dbo.CVA_BAS', 'U') IS NOT NULL 
	DROP TABLE [CVA_BAS]
GO
CREATE TABLE [dbo].[CVA_BAS](
	[ID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[INS] [datetime] NOT NULL,
	[UPD] [datetime] NULL,
	[STU] [int] NULL,
	[SRVR] [varchar](200) NULL,
	[PAS] [varchar](200) NULL,
	[COMP] [varchar](200) NULL,
	[USE_TRU] [int] NULL,
	[UNAME] [varchar](200) NULL,
	[DB_UNAME] [varchar](200) NULL,
	[DB_PAS] [varchar](200) NULL,
	[DB_TYP] [int] NULL,
	[DB_SRVR] [varchar](200) NULL
)
GO
IF OBJECT_ID('dbo.CVA_FUNC', 'U') IS NOT NULL
	DROP TABLE [CVA_FUNC]
GO
CREATE TABLE [dbo].[CVA_FUNC](
	[ID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[INS] [datetime] NOT NULL,
	[UPD] [datetime] NULL,
	[STU] [int] NULL,
	[FUNC] [varchar](200) NULL,
	[DSCR] [varchar](2000) NULL
)
GO
IF OBJECT_ID('dbo.CVA_OBJ', 'U') IS NOT NULL
	DROP TABLE [CVA_OBJ]
GO
CREATE TABLE [dbo].[CVA_OBJ](
	[ID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[INS] [datetime] NOT NULL,
	[UPD] [datetime] NULL,
	[OBJ] [varchar](200) NULL,
	[DSCR] [varchar](2000) NULL,
	[STU] [int] NULL
)
GO
IF OBJECT_ID('dbo.CVA_REG', 'U') IS NOT NULL
	DROP TABLE [CVA_REG]
GO
CREATE TABLE [dbo].[CVA_REG](
	[ID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[INS] [datetime] NOT NULL,
	[UPD] [datetime] NULL,
	[STU] [int] NULL,
	[BAS] [int] NULL,
	[CODE] [varchar](200) NULL,
	[OBJ] [int] NULL,
	[FUNC] [int] NULL,
	[BAS_ERR] [int] NULL
)
GO
IF OBJECT_ID('dbo.CVA_REG_LOG', 'U') IS NOT NULL
	DROP TABLE [CVA_REG_LOG]
GO
CREATE TABLE [dbo].[CVA_REG_LOG](
	[ID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[INS] [datetime] NOT NULL,
	[UPD] [datetime] NULL,
	[STU] [int] NULL,
	[REG] [int] NULL,
	[MSG] [varchar](2000) NOT NULL,
	[BAS] [int] NULL
)
GO
IF OBJECT_ID('dbo.CVA_STU', 'U') IS NOT NULL
	DROP TABLE [CVA_STU]
GO
CREATE TABLE [dbo].[CVA_STU](
	[ID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[INS] [datetime] NOT NULL,
	[UPD] [datetime] NULL,
	[STU] [varchar](30) NULL
)
GO
IF OBJECT_ID('dbo.CVA_TIM', 'U') IS NOT NULL
	DROP TABLE [CVA_TIM]
GO
CREATE TABLE [dbo].[CVA_TIM](
	[ID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[INS] [datetime] NOT NULL,
	[UPD] [datetime] NULL,
	[STU] [int] NULL,
	[TIM] [int] NULL,
	[NUM_OBJ] [int] NULL
)
GO
IF OBJECT_ID('dbo.CVA_TIP_REG', 'U') IS NOT NULL
	DROP TABLE [CVA_TIP_REG]
GO
CREATE TABLE [dbo].[CVA_TIP_REG](
	[ID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[INS] [datetime] NOT NULL,
	[UPD] [datetime] NULL,
	[STU] [int] NULL,
	[TIP_REG] [varchar](200) NULL,
	[DSCR] [varchar](2000) NULL
)
GO
IF OBJECT_ID('dbo.CVA_EML', 'U') IS NOT NULL
	DROP TABLE [CVA_EML]
GO
CREATE TABLE [dbo].[CVA_EML](
	[ID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[NOME] [varchar](50) NULL,
	[EMAIL] [varchar](50) NULL
)
GO
USE [CVA_ATL_REP]
GO
ALTER TABLE [dbo].[CVA_BAS]  WITH CHECK ADD FOREIGN KEY([STU]) REFERENCES [dbo].[CVA_STU] ([ID])
GO
ALTER TABLE [dbo].[CVA_FUNC]  WITH CHECK ADD FOREIGN KEY([STU]) REFERENCES [dbo].[CVA_STU] ([ID])
GO
ALTER TABLE [dbo].[CVA_OBJ]  WITH CHECK ADD FOREIGN KEY([STU]) REFERENCES [dbo].[CVA_STU] ([ID])
GO
ALTER TABLE [dbo].[CVA_REG]  WITH CHECK ADD FOREIGN KEY([BAS]) REFERENCES [dbo].[CVA_BAS] ([ID])
GO
ALTER TABLE [dbo].[CVA_REG]  WITH CHECK ADD FOREIGN KEY([FUNC]) REFERENCES [dbo].[CVA_FUNC] ([ID])
GO
ALTER TABLE [dbo].[CVA_REG]  WITH CHECK ADD FOREIGN KEY([OBJ]) REFERENCES [dbo].[CVA_OBJ] ([ID])
GO
ALTER TABLE [dbo].[CVA_REG]  WITH CHECK ADD FOREIGN KEY([STU]) REFERENCES [dbo].[CVA_STU] ([ID])
GO
ALTER TABLE [dbo].[CVA_REG]  WITH CHECK ADD FOREIGN KEY([BAS_ERR]) REFERENCES [dbo].[CVA_BAS] ([ID])
GO
ALTER TABLE [dbo].[CVA_REG_LOG]  WITH CHECK ADD FOREIGN KEY([BAS]) REFERENCES [dbo].[CVA_BAS] ([ID])
GO
ALTER TABLE [dbo].[CVA_REG_LOG]  WITH CHECK ADD FOREIGN KEY([REG]) REFERENCES [dbo].[CVA_REG] ([ID])