--set schema SBO_APETIT_PRODUCAO;

DROP PROCEDURE "SPC_CVA_PLANCARD_REPORT";
CREATE PROCEDURE "SPC_CVA_PLANCARD_REPORT"(
	PlanId varchar(250)
)  
	LANGUAGE SQLSCRIPT AS
BEGIN  

	SELECT  
		*
	FROM "@CVA_PLANEJAMENTO" AS P
	WHERE P."Code" = PlanId 		 
;

END;

call "SPC_CVA_PLANCARD_REPORT"('14');
