//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Tust.Import.PortalDAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalEDM : DbContext
    {
        public PortalEDM()
            : base("name=PortalEDM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TustLogModel> CVA_LOG_TUST { get; set; }
        public virtual DbSet<TustParamModel> CVA_PAR_TUST { get; set; }
        public virtual DbSet<TustModel> CVA_IMP_TUST { get; set; }
    }
}
