//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Tust.Import.PortalDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TustParamModel
    {
        public int ID { get; set; }
        public System.DateTime INS { get; set; }
        public Nullable<System.DateTime> UPD { get; set; }
        public int BASE_ID { get; set; }
        public string BASE_NAME { get; set; }
        public string CNPJ { get; set; }
        public int BPLID { get; set; }
        public string PROJECT { get; set; }
        public string ACC { get; set; }
        public string ACC_TRANS { get; set; }
        public string PAY_METH { get; set; }
        public string PAY_METH_TRANS { get; set; }
        public string ACC_TRANS_COMP { get; set; }
        public string ACC_CONTROL { get; set; }
        public string PAY_METH_TED { get; set; }
        public string ITEMCODE { get; set; }
        public int USAGE { get; set; }
        public string NF_MODEL { get; set; }
        public string INCOTERMS { get; set; }
        public string NAT_BC { get; set; }
        public string REG_PC { get; set; }
        public string IND_OPER { get; set; }
        public string ORIG_CRED { get; set; }
        public string DESC_DOC { get; set; }
        public Nullable<decimal> ALIQIPI { get; set; }
        public string APLIC { get; set; }
        public string COST_CENTER { get; set; }
    }
}
