//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVA.Tust.Import.PortalDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TustModel
    {
        public int ID { get; set; }
        public System.DateTime INS { get; set; }
        public string USER { get; set; }
        public int STATUS { get; set; }
        public string XML { get; set; }
        public string CNPJ { get; set; }
        public System.DateTime DATE { get; set; }
        public string CNPJ_SUPPLIER { get; set; }
        public int NR_DOC { get; set; }
        public double VALUE { get; set; }
        public string DOC_TYPE { get; set; }
        public System.DateTime DOC_DATE { get; set; }
        public System.DateTime DOC_DUE { get; set; }
        public string BOE_NUM { get; set; }
        public string BANK { get; set; }
        public string FILE { get; set; }
        public int LINE { get; set; }
    }
}
