CREATE PROCEDURE SP_CVA_APONTAMENTO_QTDEAPONTADA
(
	@NrOP		INT,
	@CodEtapa	VARCHAR(254),
	@Qtde		INT
)
AS
BEGIN
	UPDATE [@CVA_APONTAMENTO]
	SET U_QtdeApontada += @Qtde
	WHERE U_NrOP = @NrOP
	AND U_CodEtapa =  @CodEtapa

	IF @@ROWCOUNT = 0
	BEGIN
		DECLARE @Code INT
		SELECT @Code = ISNULL(MAX(CAST(Code AS NUMERIC(19, 6))), 0) + 1 FROM [@CVA_APONTAMENTO]

		INSERT INTO [@CVA_APONTAMENTO]
		VALUES (REPLACE(STR(@Code, 10), SPACE(1), '0'), REPLACE(STR(@Code, 10), SPACE(1), '0'), @NrOP, @CodEtapa, @Qtde, 0)
	END
END