//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseModel()
        {
            this.CVA_BASES_DE_PARA = new HashSet<BaseDeParaModel>();
        }
    
        public int ID { get; set; }
        public string BASE { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string DB_SERVER { get; set; }
        public string USERNAME { get; set; }
        public string PASSWD { get; set; }
        public string DB_USERNAME { get; set; }
        public string DB_PASSWD { get; set; }
        public string LICENSE_SERVER { get; set; }
        public Nullable<int> DB_TYPE { get; set; }
        public Nullable<int> USE_TRUSTED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaseDeParaModel> CVA_BASES_DE_PARA { get; set; }
    }
}
