//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseDeParaModel
    {
        public int ID { get; set; }
        public Nullable<int> BASE_DE { get; set; }
        public Nullable<int> FILIAL_DE { get; set; }
        public string CNPJ_FILIAL_DE { get; set; }
        public Nullable<int> FILIAL_PARA { get; set; }
        public string CNPJ_FILIAL_PARA { get; set; }
        public string NOME { get; set; }
    
        public virtual BaseModel CVA_BASES { get; set; }
    }
}
