//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.Data.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AbsEntry FROM ATC1 WITH(NOLOCK)
        ///WHERE (CAST(trgtPath AS NVARCHAR(MAX)) = &apos;{0}&apos; AND CAST(FileName AS NVARCHAR(MAX)) = &apos;{2}&apos; AND FileExt = &apos;{3}&apos;)
        ///OR (CAST(srcPath AS NVARCHAR(MAX)) = &apos;{1}&apos; AND CAST(FileName AS NVARCHAR(MAX)) = &apos;{2}&apos; AND FileExt = &apos;{3}&apos;).
        /// </summary>
        public static string Anexo_GetId {
            get {
                return ResourceManager.GetString("Anexo_GetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	ROW_NUMBER() OVER(ORDER BY PED1.U_LINHA ASC) AS [Row],
        ///	PED.Code,
        ///	&apos;Y&apos;				#,
        ///	PED.U_ARQUIVO	[Arquivo],
        ///	PED1.U_LINHA	[Linha],
        ///	PED1.U_EMPRESA	[Empresa],
        ///	PED1.U_BASE		[Base],
        ///	CASE PED1.U_Status
        ///		WHEN 1 THEN &apos;Pedido gerado&apos;
        ///		WHEN 2 THEN &apos;Erro ao gerar pedido&apos;
        ///		WHEN 3 THEN &apos;NF Gerada&apos;
        ///		WHEN 4 THEN &apos;Erro ao gerar NF&apos;
        ///		WHEN 5 THEN &apos;Pedido cancelado&apos;
        ///		WHEN 6 THEN &apos;Erro ao cancelar pedido&apos;
        ///		WHEN 7 THEN &apos;NF cancelada&apos;
        ///		WHEN 8 THEN &apos;Erro ao cancelar NF&apos;
        ///	END				[Status],
        ///	PED1.U_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ImpPedido_Get {
            get {
                return ResourceManager.GetString("ImpPedido_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	PED.Code,
        ///	CASE WHEN OPOR.DocStatus = &apos;O&apos;
        ///		THEN &apos;Y&apos;
        ///		ELSE &apos;N&apos;
        ///	END #,
        ///	PED.U_ARQUIVO	[Arquivo],
        ///	PED1.U_LINHA	[Linha],
        ///	PED1.U_EMPRESA	[Empresa],
        ///	PED1.U_BASE		[Base],
        ///	CASE WHEN OPOR.DocStatus = &apos;O&apos;
        ///		THEN &apos;Pedido gerado&apos;
        ///		ELSE CASE WHEN OPOR.CANCELED = &apos;Y&apos;
        ///			THEN &apos;Pedido cancelado&apos;
        ///			ELSE CASE WHEN OPOR.InvntSttus = &apos;O&apos;
        ///				THEN &apos;Pedido fechado&apos;
        ///				ELSE &apos;NF Gerada&apos;
        ///			END
        ///		END
        ///	END [Status],
        ///	--CASE PED1.U_Status
        ///		-- WHEN 1 THEN &apos;Pedido gerado&apos;
        ///		-- WHEN 2 THEN &apos;Erro [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ImpPedido_GetByBase {
            get {
                return ResourceManager.GetString("ImpPedido_GetByBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [@CVA_IMP_PED1]
        ///SET U_Status = {0},
        ///U_LOG = &apos;{1}&apos;
        ///WHERE Code = &apos;{2}&apos; AND LineId = {3}.
        /// </summary>
        public static string ImpPedido_Update {
            get {
                return ResourceManager.GetString("ImpPedido_Update", resourceCulture);
            }
        }
    }
}
